import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowPathIcon, BanknotesIcon, CheckCircleIcon, ClockIcon, ExclamationTriangleIcon } from '@heroicons/react/24/outline';
import api from '../api/axiosConfig';
import { BRAND } from '../config/brand';
import { useAdminTheme } from '../contexts/AdminThemeContext';
import { useAppDialog } from '../contexts/DialogContext';

type Charge={id:string;concepto:string;total_clp:number;estado:string;fecha_emision:string;fecha_vencimiento:string;pagado_at?:string|null;metodo_pago?:string|null;referencia?:string|null;checkout_url?:string|null;target_plan_code?:string|null;target_guardian_license?:boolean|null;billing_cycle?:string|null;academias?:{id:string;nombre:string}|null};
type Movement={id:string;tipo:'ingreso'|'egreso';categoria:string;descripcion:string;monto_clp:number;fecha:string;metodo_pago?:string|null;referencia?:string|null;academias?:{nombre:string}|null};
const money=(value:number)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(value)||0);
const dateTime=(value?:string|null)=>value?new Date(value).toLocaleString('es-CL'):'—';

export default function AdminFinanceV3(){
 const {theme}=useAdminTheme();const light=theme==='light';const {notify}=useAppDialog();const qc=useQueryClient();
 const [form,setForm]=useState({tipo:'egreso',categoria:'Operación',descripcion:'',monto_clp:'',fecha:new Date().toISOString().slice(0,10),metodo_pago:'Transferencia'});
 const {data:charges=[],isFetching}=useQuery({queryKey:['saas-cobros'],queryFn:async()=>(await api.get('/api/saas-admin/cobros')).data.data as Charge[]});
 const {data:movements=[]}=useQuery({queryKey:['saas-movimientos'],queryFn:async()=>(await api.get('/api/saas-admin/movimientos')).data.data as Movement[]});
 const panel=light?'border-slate-200 bg-white shadow-sm':'border-white/10 bg-[#1C212D]';const text=light?'text-slate-950':'text-white';const muted=light?'text-slate-500':'text-[#91a0b2]';
 const income=movements.filter(m=>m.tipo==='ingreso').reduce((s,m)=>s+Number(m.monto_clp||0),0);const expenses=movements.filter(m=>m.tipo==='egreso').reduce((s,m)=>s+Number(m.monto_clp||0),0);const paid=charges.filter(c=>String(c.estado).toLowerCase()==='pagado').reduce((s,c)=>s+Number(c.total_clp||0),0);const receivable=charges.filter(c=>['pendiente','vencido'].includes(String(c.estado).toLowerCase())).reduce((s,c)=>s+Number(c.total_clp||0),0);const pending=charges.filter(c=>!['pagado','anulado'].includes(String(c.estado).toLowerCase()));
 const save=async(e:React.FormEvent)=>{e.preventDefault();try{await api.post('/api/saas-admin/movimientos',{...form,monto_clp:Number(form.monto_clp)});setForm(v=>({...v,descripcion:'',monto_clp:''}));await Promise.all([qc.invalidateQueries({queryKey:['saas-movimientos']}),qc.invalidateQueries({queryKey:['saas-resumen']})]);await notify('Movimiento registrado.',{title:`Pagos ${BRAND.name}`});}catch(err:any){await notify(err.response?.data?.error||'No fue posible registrar el movimiento.',{title:`Pagos ${BRAND.name}`});}};
 const refresh=async()=>{await Promise.all([qc.invalidateQueries({queryKey:['saas-cobros']}),qc.invalidateQueries({queryKey:['saas-movimientos']})]);};
 return <div className="space-y-6 pb-12"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#289E9D]">Cobranza de plataforma</p><h1 className={`mt-2 text-4xl font-black ${text}`}>Pagos {BRAND.name}</h1><p className={`mt-2 max-w-3xl ${muted}`}>Planes y complementos cobrados por Lestra. Esta contabilidad permanece separada de las finanzas internas de cada academia.</p></div><button onClick={()=>void refresh()} className={`inline-flex items-center gap-2 rounded-xl border px-4 py-3 text-sm font-black ${light?'border-slate-200':'border-white/10'}`}><ArrowPathIcon className={`h-4 w-4 ${isFetching?'animate-spin':''}`}/>Actualizar</button></header>
 <section className="grid gap-4 md:grid-cols-4"><Kpi panel={panel} muted={muted} label="Cobrado" value={money(paid)} tone="text-emerald-500" icon={<CheckCircleIcon className="h-5 w-5"/>}/><Kpi panel={panel} muted={muted} label="Por cobrar" value={money(receivable)} tone="text-amber-500" icon={<ClockIcon className="h-5 w-5"/>}/><Kpi panel={panel} muted={muted} label="Ingresos libro" value={money(income)} tone="text-sky-500" icon={<BanknotesIcon className="h-5 w-5"/>}/><Kpi panel={panel} muted={muted} label="Resultado" value={money(income-expenses)} tone={income-expenses>=0?'text-emerald-500':'text-red-500'} icon={<BanknotesIcon className="h-5 w-5"/>}/></section>
 <section className={`rounded-2xl border p-5 ${panel}`}><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className={`text-xl font-black ${text}`}>Mercado Pago · conciliación automática</h2><p className={`mt-1 text-sm ${muted}`}>Checkout Pro queda operativo al cargar las credenciales de la aplicación Lestra en Render. La confirmación del webhook es la fuente de verdad; este panel no permite marcar pagos Mercado Pago manualmente.</p></div><span className="rounded-full bg-sky-500/15 px-3 py-2 text-xs font-black text-sky-500">Infraestructura preparada</span></div></section>
 <section className={`rounded-2xl border p-6 ${panel}`}><div className="flex items-center justify-between"><div><h2 className={`text-xl font-black ${text}`}>Cobros a clientes</h2><p className={`mt-1 text-xs ${muted}`}>Suscripciones y complementos emitidos a academias.</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${pending.length?'bg-amber-500/15 text-amber-500':'bg-emerald-500/15 text-emerald-500'}`}>{pending.length} pendientes</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className={muted}><tr><th className="pb-3">Academia</th><th>Concepto</th><th>Vencimiento</th><th>Método</th><th>Referencia</th><th>Estado</th><th className="text-right">Monto</th></tr></thead><tbody>{charges.slice(0,100).map(c=><tr key={c.id} className={light?'border-t border-slate-100':'border-t border-white/10'}><td className="py-4 font-black">{c.academias?.nombre||'Academia'}</td><td><div className="max-w-[320px] font-semibold">{c.concepto}</div>{c.pagado_at?<div className={`mt-1 text-xs ${muted}`}>Confirmado {dateTime(c.pagado_at)}</div>:null}</td><td>{c.fecha_vencimiento}</td><td>{c.metodo_pago||'—'}</td><td className={`max-w-[180px] truncate text-xs ${muted}`}>{c.referencia||'—'}</td><td><Status value={c.estado}/></td><td className="text-right font-black">{money(c.total_clp)}</td></tr>)}</tbody></table>{!charges.length?<p className={`py-10 text-center ${muted}`}>Todavía no existen cobros de plataforma.</p>:null}</div></section>
 <section className="grid gap-6 xl:grid-cols-[.75fr_1.25fr]"><form onSubmit={save} className={`rounded-2xl border p-6 ${panel}`}><h2 className={`text-xl font-black ${text}`}>Movimiento manual</h2><p className={`mt-1 text-xs ${muted}`}>Solo para egresos o ajustes extraordinarios. Los pagos Mercado Pago se registran automáticamente.</p><div className="mt-5 space-y-4"><label><span className="label">Tipo</span><select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})} className="w-full"><option value="egreso">Egreso</option><option value="ingreso">Ingreso extraordinario</option></select></label><label><span className="label">Categoría</span><input value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})} className="w-full"/></label><label><span className="label">Descripción</span><input required value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})} className="w-full"/></label><div className="grid gap-3 sm:grid-cols-2"><label><span className="label">Monto CLP</span><input required min="1" type="number" value={form.monto_clp} onChange={e=>setForm({...form,monto_clp:e.target.value})} className="w-full"/></label><label><span className="label">Fecha</span><input type="date" value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})} className="w-full"/></label></div><button className="btn-primary w-full">Guardar movimiento</button></div></form>
 <div className={`rounded-2xl border p-6 ${panel}`}><h2 className={`text-xl font-black ${text}`}>Libro de movimientos</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className={muted}><tr><th className="pb-3">Fecha</th><th>Tipo</th><th>Detalle</th><th>Academia</th><th>Método</th><th className="text-right">Monto</th></tr></thead><tbody>{movements.slice(0,100).map(m=><tr key={m.id} className={light?'border-t border-slate-100':'border-t border-white/10'}><td className="py-3">{m.fecha}</td><td className={m.tipo==='ingreso'?'text-emerald-500':'text-red-500'}>{m.tipo}</td><td><strong>{m.descripcion}</strong><div className={muted}>{m.categoria}</div></td><td>{m.academias?.nombre||'Plataforma'}</td><td>{m.metodo_pago||'—'}</td><td className={`text-right font-black ${m.tipo==='ingreso'?'text-emerald-500':'text-red-500'}`}>{m.tipo==='ingreso'?'+':'-'}{money(m.monto_clp)}</td></tr>)}</tbody></table></div></div></section>
 <section className={`flex gap-3 rounded-2xl border p-5 ${light?'border-sky-200 bg-sky-50 text-sky-900':'border-sky-400/20 bg-sky-500/10 text-sky-100'}`}><ExclamationTriangleIcon className="h-6 w-6 shrink-0"/><p className="text-sm leading-6">Si Mercado Pago confirma una operación pero no aparece conciliada, se trata como incidencia técnica: se revisa webhook, monto y referencia. No se fuerza el estado “pagado” manualmente para cuadrar la contabilidad.</p></section></div>;
}
function Kpi({panel,muted,label,value,tone,icon}:{panel:string;muted:string;label:string;value:string;tone:string;icon:React.ReactNode}){return <article className={`rounded-2xl border p-5 ${panel}`}><div className={`flex items-center gap-2 text-xs font-black uppercase ${muted}`}>{icon}{label}</div><p className={`mt-3 text-3xl font-black ${tone}`}>{value}</p></article>}
function Status({value}:{value:string}){const v=String(value||'').toLowerCase();const cls=v==='pagado'?'bg-emerald-500/15 text-emerald-500':v==='anulado'?'bg-slate-500/15 text-slate-500':v==='vencido'?'bg-red-500/15 text-red-500':'bg-amber-500/15 text-amber-500';return <span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${cls}`}>{value||'pendiente'}</span>}
