import { useQuery } from '@tanstack/react-query';
import { BanknotesIcon, CalendarDaysIcon, CheckCircleIcon, UserIcon } from '@heroicons/react/24/outline';
import api from '../api/axiosConfig';

type Portal = {
  apoderado: { nombre: string };
  academia: { nombre: string };
  jugadores: { id: string; nombre: string; foto_url?: string | null; avatar_url?: string | null; estado_financiero?: string | null; saldo_pendiente?: number | null }[];
  proximos_partidos: { id: string; rival: string; fecha: string; hora: string; hora_citacion?: string | null; ubicacion?: string | null; categorias?: { nombre: string } | null }[];
  asistencias_recientes: { id: string; jugador_id: string; estado: string; entrenamientos?: { fecha: string } | null }[];
  finanzas: { saldo_pendiente: number; cobros: { id: string; concepto: string; monto: number; monto_pagado: number; estado: string; fecha_vencimiento?: string | null }[] };
};
const money = (value: number) => new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 }).format(value || 0);

const ApoderadoPortal = () => {
  const { data, isLoading, error } = useQuery({ queryKey: ['apoderado-portal'], queryFn: async () => (await api.get('/api/apoderados/me')).data.data as Portal });
  if (isLoading) return <div className="py-20 text-center font-bold text-[#8995a4]">Cargando tu información...</div>;
  if (error || !data) return <div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-6 text-red-200">No fue posible cargar tu portal. Contacta a la dirección de tu academia.</div>;
  return <div className="space-y-6 pb-12"><section className="rounded-[28px] border border-violet-400/20 bg-[radial-gradient(circle_at_top_right,rgba(139,92,246,0.18),transparent_35%),#151b25] p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-violet-300">Portal privado de apoderado</p><h1 className="mt-2 text-3xl font-black text-white">Hola, {data.apoderado.nombre}</h1><p className="mt-2 text-[#9aa6b5]">Información de tus jugadores en {data.academia.nombre}.</p></section>
    <section><h2 className="text-xl font-black text-white">Tus jugadores</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{data.jugadores.map((player) => <article key={player.id} className="rounded-2xl border border-white/10 bg-[#151b25] p-5"><div className="flex items-center gap-4">{player.foto_url || player.avatar_url ? <img src={player.foto_url || player.avatar_url || ''} alt="" className="h-14 w-14 rounded-2xl object-cover" /> : <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#289E9D]/15"><UserIcon className="h-7 w-7 text-[#70e4df]" /></div>}<div><h3 className="text-lg font-black">{player.nombre}</h3><p className="text-sm text-[#8995a4]">Estado de cuenta: {player.estado_financiero || 'Sin observaciones'}</p></div></div></article>)}</div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-[#151b25] p-5"><div className="flex items-center gap-3"><CalendarDaysIcon className="h-7 w-7 text-[#70e4df]" /><h2 className="text-xl font-black">Próximos partidos</h2></div><div className="mt-4 space-y-3">{data.proximos_partidos.length ? data.proximos_partidos.map((match) => <article key={match.id} className="rounded-2xl border border-white/10 bg-[#101620] p-4"><div className="flex justify-between gap-3"><p className="font-black">vs {match.rival}</p><p className="text-sm text-[#8995a4]">{match.fecha}</p></div><p className="mt-1 text-sm text-[#8995a4]">{match.categorias?.nombre} · {match.ubicacion || 'Lugar por confirmar'}</p><div className="mt-3 flex gap-4 text-sm font-black"><span className="text-[#70e4df]">Citación {match.hora_citacion?.slice(0, 5) || 'Por definir'}</span><span>Inicio {match.hora?.slice(0, 5)}</span></div></article>) : <p className="py-8 text-center text-[#8995a4]">No hay partidos próximos.</p>}</div></div>
      <div className="rounded-3xl border border-white/10 bg-[#151b25] p-5"><div className="flex items-center gap-3"><BanknotesIcon className="h-7 w-7 text-violet-300" /><h2 className="text-xl font-black">Estado de cuenta familiar</h2></div><p className="mt-6 text-sm text-[#8995a4]">Saldo pendiente</p><p className={`mt-1 text-3xl font-black ${data.finanzas.saldo_pendiente > 0 ? 'text-amber-300' : 'text-emerald-300'}`}>{money(data.finanzas.saldo_pendiente)}</p><div className="mt-5 space-y-2">{data.finanzas.cobros.filter((item) => Number(item.monto) - Number(item.monto_pagado) > 0).slice(0, 6).map((charge) => <div key={charge.id} className="flex justify-between gap-3 rounded-xl border border-white/10 p-3"><div><p className="text-sm font-black">{charge.concepto}</p><p className="text-xs text-[#8995a4]">Vence: {charge.fecha_vencimiento || 'Sin fecha'}</p></div><p className="text-sm font-black text-amber-300">{money(Number(charge.monto) - Number(charge.monto_pagado))}</p></div>)}</div></div></section>
    <section className="rounded-3xl border border-white/10 bg-[#151b25] p-5"><div className="flex items-center gap-3"><CheckCircleIcon className="h-7 w-7 text-emerald-300" /><h2 className="text-xl font-black">Asistencia reciente</h2></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.asistencias_recientes.slice(0, 12).map((item) => { const player = data.jugadores.find((candidate) => candidate.id === item.jugador_id); return <div key={item.id} className="flex items-center justify-between rounded-xl border border-white/10 p-3"><div><p className="text-sm font-black">{player?.nombre || 'Jugador'}</p><p className="text-xs text-[#8995a4]">{item.entrenamientos?.fecha || 'Entrenamiento'}</p></div><span className={`rounded-full px-2 py-1 text-xs font-black ${item.estado === 'Presente' ? 'bg-emerald-500/15 text-emerald-300' : item.estado === 'Justificado' ? 'bg-amber-500/15 text-amber-300' : 'bg-red-500/15 text-red-300'}`}>{item.estado}</span></div>; })}</div></section>
  </div>;
};

export default ApoderadoPortal;
