import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import api from '../api/axiosConfig';
import { Logo } from '../components/Logo';

type Quota={id:string;numero:number;total_cuotas:number;monto:number;monto_pagado:number;fecha_vencimiento:string;estado:string;saldo:number;vencida:boolean};
type Reported={id:string;monto:number;fecha_pago_informada:string;estado:string;created_at:string};
type Charge={id:string;jugador_id:string;concepto:string;tipo_concepto?:string|null;monto:number;monto_pagado:number;estado:string;fecha_vencimiento?:string|null;saldo:number;vencido:boolean;cuotas:Quota[];pagos_informados_pendientes:Reported[]};
type Statement={academia:{nombre:string;slug:string;logo?:string|null;colores:{primario:string;secundario:string;fondo:string}};jugadores:{id:string;nombre:string;estado_financiero?:string|null}[];cobros:Charge[];saldo_total:number;metodos_pago?:{acepta_efectivo?:boolean;acepta_transferencia?:boolean;acepta_pago_online?:boolean;transferencia_banco?:string|null;transferencia_tipo_cuenta?:string|null;transferencia_numero?:string|null;transferencia_rut?:string|null;transferencia_correo?:string|null;link_pago_online?:string|null}|null;expira_at:string};

type SelectedPayment={charge:Charge;quota?:Quota|null};
const money=(value:number)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(value)||0);
const today=()=>new Date().toISOString().slice(0,10);
const validUrl=(value?:string|null)=>{try{const url=new URL(value||'');return ['https:','http:'].includes(url.protocol)?url.toString():null;}catch{return null;}};

export default function CollectionPortal(){
  const {slug='',token:routeToken=''}=useParams();
  const navigate=useNavigate();
  const [token,setToken]=useState(routeToken);
  const [rut,setRut]=useState('');
  const [verificationId,setVerificationId]=useState('');
  const [code,setCode]=useState('');
  const [statement,setStatement]=useState<Statement|null>(null);
  const [loading,setLoading]=useState(Boolean(routeToken));
  const [saving,setSaving]=useState(false);
  const [message,setMessage]=useState('');
  const [error,setError]=useState('');
  const [selected,setSelected]=useState<SelectedPayment|null>(null);
  const [paymentForm,setPaymentForm]=useState({monto:'',fecha_pago:today(),comprobante_ref:'',observaciones:'',idempotency_key:''});

  const loadStatement=async(activeToken:string)=>{
    setLoading(true);setError('');
    try{const response=await api.get(`/api/cobranza/public/estado/${encodeURIComponent(activeToken)}`);setStatement(response.data.data);}
    catch(err:any){setError(err.response?.data?.error||'No fue posible cargar el estado de cuenta.');}
    finally{setLoading(false);}
  };
  useEffect(()=>{if(routeToken){setToken(routeToken);void loadStatement(routeToken);}},[routeToken]);

  const playerNames=useMemo(()=>new Map((statement?.jugadores||[]).map((player)=>[player.id,player.nombre])),[statement]);
  const begin=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');setMessage('');try{const response=await api.post(`/api/cobranza/public/${encodeURIComponent(slug)}/iniciar`,{rut});setVerificationId(response.data.verification_id);setMessage(response.data.message||'Revisa el contacto registrado en la academia.');}catch(err:any){setError(err.response?.data?.error||'No fue posible iniciar la consulta.');}finally{setSaving(false);}};
  const verify=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{const response=await api.post(`/api/cobranza/public/${encodeURIComponent(slug)}/verificar`,{verification_id:verificationId,codigo:code});const nextToken=response.data.token;setToken(nextToken);navigate(`/pagar/${encodeURIComponent(nextToken)}`,{replace:true});await loadStatement(nextToken);}catch(err:any){setError(err.response?.data?.error||'Código inválido o vencido.');}finally{setSaving(false);}};
  const openReport=(charge:Charge,quota?:Quota|null)=>{const amount=quota?quota.saldo:charge.saldo;setSelected({charge,quota});setPaymentForm({monto:String(Math.round(amount)),fecha_pago:today(),comprobante_ref:'',observaciones:'',idempotency_key:crypto.randomUUID()});};
  const reportPayment=async(event:FormEvent)=>{event.preventDefault();if(!selected||!token)return;setSaving(true);setError('');try{const response=await api.post(`/api/cobranza/public/pagos-informados/${encodeURIComponent(token)}`,{...paymentForm,monto:Number(paymentForm.monto)||0,cobro_id:selected.charge.id,cuota_id:selected.quota?.id||null});setSelected(null);setMessage(response.data.message||'Pago informado.');await loadStatement(token);}catch(err:any){setError(err.response?.data?.error||'No fue posible informar el pago.');}finally{setSaving(false);}};

  if(!routeToken&&!statement&&!verificationId)return <div className="min-h-screen bg-[#0d1117] px-5 py-12 text-white"><div className="mx-auto max-w-lg"><div className="text-center"><Logo variant="mark" className="mx-auto h-14 w-14"/><p className="mt-4 text-xs font-black uppercase tracking-[.2em] text-[#70e4df]">Portal seguro de pagos</p><h1 className="mt-2 text-3xl font-black">Consulta tu estado de cuenta</h1><p className="mt-3 text-sm leading-6 text-[#8995a4]">Ingresa el RUT del apoderado o del alumno. Por seguridad, no mostraremos información financiera hasta verificar el contacto registrado en la academia.</p></div><form onSubmit={begin} className="mt-8 rounded-3xl border border-white/10 bg-[#151b25] p-6"><label className="text-sm font-bold text-[#b6c0cc]">RUT<input autoFocus required value={rut} onChange={(e)=>setRut(e.target.value)} placeholder="12.345.678-9" className="mt-2 w-full rounded-xl border border-white/10 bg-[#0d1117] px-4 py-3 text-white outline-none focus:border-[#289E9D]"/></label><button disabled={saving} className="mt-5 w-full rounded-xl bg-[#289E9D] px-4 py-3 font-black text-white disabled:opacity-50">{saving?'Verificando...':'Continuar de forma segura'}</button>{error?<p className="mt-4 text-sm text-red-300">{error}</p>:null}</form><p className="mt-5 text-center text-xs leading-5 text-[#657181]">El RUT por sí solo no permite acceder a la deuda. Lestra exige un segundo factor enviado al contacto registrado.</p></div></div>;

  if(!routeToken&&!statement&&verificationId)return <div className="min-h-screen bg-[#0d1117] px-5 py-12 text-white"><div className="mx-auto max-w-lg"><Logo variant="mark" className="mx-auto h-14 w-14"/><div className="mt-7 rounded-3xl border border-white/10 bg-[#151b25] p-6"><h1 className="text-2xl font-black">Ingresa el código temporal</h1><p className="mt-2 text-sm leading-6 text-[#8995a4]">{message}</p><form onSubmit={verify} className="mt-6"><input required inputMode="numeric" maxLength={6} value={code} onChange={(e)=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000" className="w-full rounded-xl border border-white/10 bg-[#0d1117] px-4 py-4 text-center text-2xl font-black tracking-[.35em] text-white outline-none focus:border-[#289E9D]"/><button disabled={saving||code.length!==6} className="mt-4 w-full rounded-xl bg-[#289E9D] px-4 py-3 font-black text-white disabled:opacity-50">{saving?'Validando...':'Ver estado de cuenta'}</button></form>{error?<p className="mt-4 text-sm text-red-300">{error}</p>:null}<button onClick={()=>{setVerificationId('');setCode('');setMessage('');setError('');}} className="mt-4 w-full text-xs font-bold text-[#8995a4]">Volver e ingresar otro RUT</button></div></div></div>;

  if(loading)return <div className="grid min-h-screen place-items-center bg-[#0d1117] font-bold text-[#70e4df]">Cargando estado de cuenta...</div>;
  if(error&&!statement)return <div className="grid min-h-screen place-items-center bg-[#0d1117] p-6 text-center text-white"><div><Logo variant="mark" className="mx-auto h-14 w-14"/><h1 className="mt-5 text-2xl font-black">Enlace no disponible</h1><p className="mt-2 text-[#8995a4]">{error}</p></div></div>;
  if(!statement)return null;

  const primary=statement.academia.colores?.primario||'#289E9D';
  const onlineUrl=validUrl(statement.metodos_pago?.link_pago_online);
  return <div className="min-h-screen bg-[#0d1117] text-white"><header className="border-b border-white/10 bg-[#101620] px-5"><div className="mx-auto flex max-w-5xl items-center justify-between py-4"><div className="flex items-center gap-3">{statement.academia.logo?<img src={statement.academia.logo} alt="" className="h-10 w-10 rounded-xl object-contain"/>:<Logo variant="mark" className="h-10 w-10"/>}<div><p className="text-[10px] font-black uppercase tracking-[.18em]" style={{color:primary}}>Estado de cuenta</p><p className="font-black">{statement.academia.nombre}</p></div></div><span className="text-xs text-[#657181]">Protegido por Lestra</span></div></header><main className="mx-auto max-w-5xl space-y-6 px-5 py-8 sm:py-10">
    {message?<div className="rounded-2xl border border-emerald-400/20 bg-emerald-500/10 p-4 text-sm text-emerald-200">{message}</div>:null}{error?<div className="rounded-2xl border border-red-400/20 bg-red-500/10 p-4 text-sm text-red-200">{error}</div>:null}
    <section className="rounded-[28px] border border-white/10 bg-[#151b25] p-6 sm:p-7"><p className="text-xs font-black uppercase tracking-[.18em] text-[#8995a4]">Total pendiente</p><p className={`mt-2 text-4xl font-black ${statement.saldo_total>0?'text-amber-300':'text-emerald-300'}`}>{money(statement.saldo_total)}</p><p className="mt-2 text-sm text-[#8995a4]">{statement.jugadores.map((player)=>player.nombre).join(' · ')}</p></section>
    {!statement.cobros.length?<section className="rounded-3xl border border-emerald-400/20 bg-emerald-500/10 p-8 text-center"><p className="text-4xl">✓</p><h2 className="mt-3 text-2xl font-black text-emerald-200">Sin pagos pendientes</h2><p className="mt-2 text-sm text-emerald-100/70">Según los registros actuales de la academia, tu cuenta no tiene saldo pendiente.</p></section>:<section className="space-y-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#70e4df]">Detalle</p><h2 className="mt-1 text-2xl font-black">Conceptos por pagar</h2></div>{statement.cobros.map((charge)=><article key={charge.id} className="rounded-3xl border border-white/10 bg-[#151b25] p-5 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold text-[#8995a4]">{playerNames.get(charge.jugador_id)||'Alumno'} · {charge.tipo_concepto||'Cobro'}</p><h3 className="mt-1 text-lg font-black">{charge.concepto}</h3></div><div className="sm:text-right"><p className="text-xs text-[#8995a4]">Saldo</p><p className="text-xl font-black text-amber-300">{money(charge.saldo)}</p></div></div>{charge.pagos_informados_pendientes?.length?<div className="mt-4 rounded-xl border border-sky-400/20 bg-sky-500/10 p-3 text-xs text-sky-200">Hay {charge.pagos_informados_pendientes.length} pago(s) informado(s) esperando validación de la academia. La deuda se mantiene hasta que Dirección confirme.</div>:null}{charge.cuotas?.length?<div className="mt-4 space-y-2">{charge.cuotas.filter((q)=>q.saldo>0).map((quota)=><div key={quota.id} className="flex flex-col gap-3 rounded-xl border border-white/10 bg-[#0d1117] p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-black">Cuota {quota.numero} de {quota.total_cuotas}</p><p className={`text-xs ${quota.vencida?'text-red-300':'text-[#8995a4]'}`}>{quota.vencida?'Vencida':'Vence'} · {quota.fecha_vencimiento}</p></div><div className="flex items-center gap-3"><strong className="text-amber-300">{money(quota.saldo)}</strong><button onClick={()=>openReport(charge,quota)} className="rounded-lg border border-[#289E9D]/30 px-3 py-2 text-xs font-black text-[#70e4df]">Informar transferencia</button></div></div>)}</div>:<div className="mt-4 flex items-center justify-between rounded-xl border border-white/10 bg-[#0d1117] p-3"><p className={`text-xs ${charge.vencido?'text-red-300':'text-[#8995a4]'}`}>{charge.vencido?'Vencido':'Vence'} · {charge.fecha_vencimiento||'Sin fecha'}</p><button onClick={()=>openReport(charge,null)} className="rounded-lg border border-[#289E9D]/30 px-3 py-2 text-xs font-black text-[#70e4df]">Informar transferencia</button></div>}</article>)}</section>}
    {statement.metodos_pago?<section className="rounded-3xl border border-white/10 bg-[#151b25] p-5 sm:p-6"><h2 className="text-xl font-black">Opciones habilitadas por la academia</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{statement.metodos_pago.acepta_efectivo?<div className="rounded-2xl border border-white/10 bg-[#0d1117] p-4"><p className="text-2xl">💵</p><h3 className="mt-2 font-black">Efectivo</h3><p className="mt-1 text-sm text-[#8995a4]">Pago presencial. Debe ser registrado por la academia.</p></div>:null}{statement.metodos_pago.acepta_transferencia?<div className="rounded-2xl border border-white/10 bg-[#0d1117] p-4"><p className="text-2xl">🏦</p><h3 className="mt-2 font-black">Transferencia</h3><p className="mt-2 text-sm text-[#b6c0cc]">{statement.metodos_pago.transferencia_banco||'Banco por confirmar'}<br/>{statement.metodos_pago.transferencia_tipo_cuenta||''} {statement.metodos_pago.transferencia_numero||''}<br/>RUT: {statement.metodos_pago.transferencia_rut||'Consultar academia'}</p></div>:null}{statement.metodos_pago.acepta_pago_online&&onlineUrl?<a href={onlineUrl} target="_blank" rel="noreferrer" className="rounded-2xl border border-violet-400/20 bg-violet-500/10 p-4"><p className="text-2xl">💳</p><h3 className="mt-2 font-black text-violet-200">Pago en línea</h3><p className="mt-1 text-sm text-violet-200/70">Abrir medio de pago definido por la academia.</p></a>:null}</div><p className="mt-4 text-xs leading-5 text-[#657181]">Lestra registra la cuenta corriente. Una transferencia informada permanece pendiente hasta que la academia comprueba la recepción del dinero.</p></section>:null}
  </main>{selected?<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form onSubmit={reportPayment} className="w-full max-w-lg rounded-3xl border border-white/10 bg-[#151b25] p-6 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-[#70e4df]">Pago por validar</p><h2 className="mt-1 text-xl font-black">Informar transferencia</h2><p className="mt-1 text-xs text-[#8995a4]">{selected.charge.concepto}{selected.quota?` · Cuota ${selected.quota.numero} de ${selected.quota.total_cuotas}`:''}</p></div><button type="button" onClick={()=>setSelected(null)} className="text-[#8995a4]">✕</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm text-[#b6c0cc]">Monto<input required type="number" min="1" value={paymentForm.monto} onChange={(e)=>setPaymentForm({...paymentForm,monto:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0d1117] px-3 py-3 text-white"/></label><label className="text-sm text-[#b6c0cc]">Fecha transferencia<input required type="date" max={today()} value={paymentForm.fecha_pago} onChange={(e)=>setPaymentForm({...paymentForm,fecha_pago:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0d1117] px-3 py-3 text-white"/></label></div><label className="mt-4 block text-sm text-[#b6c0cc]">N° operación o referencia<input value={paymentForm.comprobante_ref} onChange={(e)=>setPaymentForm({...paymentForm,comprobante_ref:e.target.value})} placeholder="Ej. 98451236" className="mt-2 w-full rounded-xl border border-white/10 bg-[#0d1117] px-3 py-3 text-white"/></label><label className="mt-4 block text-sm text-[#b6c0cc]">Observación opcional<textarea value={paymentForm.observaciones} onChange={(e)=>setPaymentForm({...paymentForm,observaciones:e.target.value})} className="mt-2 min-h-20 w-full rounded-xl border border-white/10 bg-[#0d1117] px-3 py-3 text-white"/></label><div className="mt-5 rounded-xl border border-amber-400/20 bg-amber-500/10 p-3 text-xs leading-5 text-amber-100">Informar el pago <strong>no lo marcará como pagado</strong>. La academia debe validar primero que recibió el dinero.</div><button disabled={saving} className="mt-5 w-full rounded-xl bg-[#289E9D] px-4 py-3 font-black text-white disabled:opacity-50">{saving?'Enviando...':'Enviar para validación'}</button></form></div>:null}</div>;
}