import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import api from '../api/axiosConfig';
import { Logo } from '../components/Logo';

type Quota={id:string;numero:number;total_cuotas:number;monto:number;monto_pagado:number;fecha_vencimiento:string;estado:string;saldo:number;vencida:boolean};
type Reported={id:string;monto:number;fecha_pago_informada:string;estado:string;created_at:string};
type Charge={id:string;jugador_id:string;concepto:string;tipo_concepto?:string|null;monto:number;monto_pagado:number;estado:string;fecha_vencimiento?:string|null;saldo:number;vencido:boolean;cuotas:Quota[];pagos_informados_pendientes:Reported[]};
type Statement={academia:{nombre:string;slug:string;logo?:string|null;colores:{primario:string;secundario:string;fondo:string}};jugadores:{id:string;nombre:string;estado_financiero?:string|null}[];cobros:Charge[];saldo_total:number;metodos_pago?:{acepta_efectivo?:boolean;acepta_transferencia?:boolean;acepta_pago_online?:boolean;transferencia_banco?:string|null;transferencia_tipo_cuenta?:string|null;transferencia_numero?:string|null;transferencia_rut?:string|null;transferencia_correo?:string|null}|null;expira_at:string};
type Target={key:string;cobro_id:string;cuota_id:string|null;label:string;amount:number;charge:Charge;quota?:Quota|null};
const money=(value:number)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(value)||0);
const today=()=>new Date().toISOString().slice(0,10);
const apiBase=String(import.meta.env.VITE_API_URL||'http://localhost:8080').replace(/\/$/,'');

export default function CollectionPortalV2(){
 const {slug='',token:routeToken=''}=useParams();const navigate=useNavigate();
 const [token,setToken]=useState(routeToken);const [rut,setRut]=useState('');const [verificationId,setVerificationId]=useState('');const [code,setCode]=useState('');
 const [statement,setStatement]=useState<Statement|null>(null);const [loading,setLoading]=useState(Boolean(routeToken));const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 const [selectedKeys,setSelectedKeys]=useState<string[]>([]);const [transferTarget,setTransferTarget]=useState<Target|null>(null);const [receipt,setReceipt]=useState<File|null>(null);const [transfer,setTransfer]=useState({monto:'',fecha_pago:today(),observaciones:''});
 const load=async(activeToken:string)=>{setLoading(true);setError('');try{const r=await api.get(`/api/cobranza/public/estado/${encodeURIComponent(activeToken)}`);setStatement(r.data.data);}catch(err:any){setError(err.response?.data?.error||'No fue posible cargar el estado de cuenta.');}finally{setLoading(false);}};
 useEffect(()=>{if(routeToken){setToken(routeToken);void load(routeToken);}},[routeToken]);
 const names=useMemo(()=>new Map((statement?.jugadores||[]).map(p=>[p.id,p.nombre])),[statement]);
 const targets=useMemo<Target[]>(()=>{const out:Target[]=[];for(const c of statement?.cobros||[]){if(c.cuotas?.length){for(const q of c.cuotas){if(q.saldo>0)out.push({key:`${c.id}:${q.id}`,cobro_id:c.id,cuota_id:q.id,label:`${c.concepto} · Cuota ${q.numero}/${q.total_cuotas}`,amount:q.saldo,charge:c,quota:q});}}else if(c.saldo>0)out.push({key:`${c.id}:`,cobro_id:c.id,cuota_id:null,label:c.concepto,amount:c.saldo,charge:c,quota:null});}return out;},[statement]);
 const selected=useMemo(()=>targets.filter(t=>selectedKeys.includes(t.key)),[targets,selectedKeys]);const totalSelected=selected.reduce((s,t)=>s+t.amount,0);
 const begin=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');setMessage('');try{const r=await api.post(`/api/cobranza/public/${encodeURIComponent(slug)}/iniciar`,{rut});setVerificationId(r.data.verification_id);setMessage(r.data.message||'Revisa el contacto registrado.');}catch(err:any){setError(err.response?.data?.error||'No fue posible iniciar la consulta.');}finally{setSaving(false);}};
 const verify=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{const r=await api.post(`/api/cobranza/public/${encodeURIComponent(slug)}/verificar`,{verification_id:verificationId,codigo:code});const next=r.data.token;setToken(next);navigate(`/pagar/${encodeURIComponent(next)}`,{replace:true});await load(next);}catch(err:any){setError(err.response?.data?.error||'Código inválido o vencido.');}finally{setSaving(false);}};
 const toggle=(key:string)=>setSelectedKeys(prev=>prev.includes(key)?prev.filter(v=>v!==key):[...prev,key]);
 const payOnline=async()=>{if(!token||!selected.length)return;setSaving(true);setError('');try{const r=await api.post(`/api/mercadopago/academy/checkout/${encodeURIComponent(token)}`,{items:selected.map(t=>({cobro_id:t.cobro_id,cuota_id:t.cuota_id}))});window.location.assign(r.data.data.checkoutUrl);}catch(err:any){setError(err.response?.data?.error||'No fue posible preparar el pago en línea.');}finally{setSaving(false);}};
 const openTransfer=(target:Target)=>{setTransferTarget(target);setTransfer({monto:String(Math.round(target.amount)),fecha_pago:today(),observaciones:''});setReceipt(null);setError('');};
 const reportTransfer=async(e:FormEvent)=>{e.preventDefault();if(!token||!transferTarget||!receipt)return;setSaving(true);setError('');try{const form=new FormData();form.append('comprobante',receipt);form.append('cobro_id',transferTarget.cobro_id);if(transferTarget.cuota_id)form.append('cuota_id',transferTarget.cuota_id);form.append('monto',String(Number(transfer.monto)||0));form.append('fecha_pago',transfer.fecha_pago);form.append('observaciones',transfer.observaciones);form.append('idempotency_key',crypto.randomUUID());const response=await fetch(`${apiBase}/api/cobranza/recibos/public/transferencia/${encodeURIComponent(token)}`,{method:'POST',body:form});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'No fue posible informar la transferencia.');setTransferTarget(null);setReceipt(null);setMessage(payload.message||'Transferencia informada para validación.');await load(token);}catch(err:any){setError(err.message||'No fue posible informar la transferencia.');}finally{setSaving(false);}};
 if(!routeToken&&!statement&&!verificationId)return <Shell><div className="mx-auto max-w-lg text-center"><Logo variant="mark" className="mx-auto h-14 w-14"/><p className="mt-4 text-xs font-black uppercase tracking-[.2em] text-[#70e4df]">Portal seguro de pagos</p><h1 className="mt-2 text-3xl font-black text-white">Consulta tu estado de cuenta</h1><p className="mt-3 text-sm leading-6 text-[#8995a4]">Ingresa el RUT del apoderado o alumno. Antes de mostrar información financiera verificaremos el contacto registrado.</p><form onSubmit={begin} className="mt-8 rounded-3xl border border-white/10 bg-[#151b25] p-6 text-left"><label className="text-sm font-bold text-[#b6c0cc]">RUT<input required autoFocus value={rut} onChange={e=>setRut(e.target.value)} placeholder="12.345.678-9" className="mt-2 w-full rounded-xl border border-white/10 bg-[#0d1117] px-4 py-3 text-white outline-none focus:border-[#289E9D]"/></label><button disabled={saving} className="mt-5 w-full rounded-xl bg-[#289E9D] px-4 py-3 font-black text-white disabled:opacity-50">{saving?'Verificando...':'Continuar de forma segura'}</button>{error?<ErrorBox text={error}/>:null}</form></div></Shell>;
 if(!routeToken&&!statement&&verificationId)return <Shell><div className="mx-auto max-w-lg"><Logo variant="mark" className="mx-auto h-14 w-14"/><div className="mt-7 rounded-3xl border border-white/10 bg-[#151b25] p-6"><h1 className="text-2xl font-black text-white">Ingresa el código temporal</h1><p className="mt-2 text-sm text-[#8995a4]">{message}</p><form onSubmit={verify} className="mt-6"><input required inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000" className="w-full rounded-xl border border-white/10 bg-[#0d1117] px-4 py-4 text-center text-2xl font-black tracking-[.35em] text-white"/><button disabled={saving||code.length!==6} className="mt-4 w-full rounded-xl bg-[#289E9D] px-4 py-3 font-black text-white disabled:opacity-50">Validar y continuar</button></form>{error?<ErrorBox text={error}/>:null}</div></div></Shell>;
 if(loading)return <Shell><p className="text-center font-bold text-[#70e4df]">Cargando estado de cuenta...</p></Shell>;
 if(error&&!statement)return <Shell><div className="text-center"><h1 className="text-2xl font-black text-white">Enlace no disponible</h1><ErrorBox text={error}/></div></Shell>;
 if(!statement)return null;
 const primary=statement.academia.colores?.primario||'#289E9D';
 return <div className="min-h-screen bg-[#0d1117] text-white"><header className="border-b border-white/10 bg-[#101620] px-5"><div className="mx-auto flex max-w-5xl items-center justify-between py-4"><div className="flex items-center gap-3">{statement.academia.logo?<img src={statement.academia.logo} className="h-10 w-10 rounded-xl object-contain" alt=""/>:<Logo variant="mark" className="h-10 w-10"/>}<div><p className="text-[10px] font-black uppercase tracking-[.18em]" style={{color:primary}}>Estado de cuenta</p><p className="font-black">{statement.academia.nombre}</p></div></div><span className="text-xs text-[#657181]">Protegido por Lestra</span></div></header><main className="mx-auto max-w-5xl space-y-6 px-5 py-8">
 {message?<div className="rounded-2xl border border-emerald-400/20 bg-emerald-500/10 p-4 text-sm text-emerald-200">{message}</div>:null}{error?<ErrorBox text={error}/>:null}
 <section className="rounded-[28px] border border-white/10 bg-[#151b25] p-6"><p className="text-xs font-black uppercase tracking-[.18em] text-[#8995a4]">Total pendiente</p><p className={`mt-2 text-4xl font-black ${statement.saldo_total?'text-amber-300':'text-emerald-300'}`}>{money(statement.saldo_total)}</p><p className="mt-2 text-sm text-[#8995a4]">{statement.jugadores.map(p=>p.nombre).join(' · ')}</p></section>
 {!targets.length?<section className="rounded-3xl border border-emerald-400/20 bg-emerald-500/10 p-8 text-center"><p className="text-4xl">✓</p><h2 className="mt-3 text-2xl font-black text-emerald-200">Sin pagos pendientes</h2></section>:<section className="space-y-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#70e4df]">Selecciona qué pagar</p><h2 className="mt-1 text-2xl font-black">Obligaciones pendientes</h2></div>{targets.map(t=><article key={t.key} className={`rounded-2xl border p-4 ${selectedKeys.includes(t.key)?'border-[#289E9D] bg-[#289E9D]/10':'border-white/10 bg-[#151b25]'}`}><div className="flex gap-3"><input type="checkbox" checked={selectedKeys.includes(t.key)} onChange={()=>toggle(t.key)} className="mt-1 h-5 w-5 accent-[#289E9D]"/><div className="min-w-0 flex-1"><p className="text-xs text-[#8995a4]">{names.get(t.charge.jugador_id)||'Alumno'} · {t.charge.tipo_concepto||'Cobro'}</p><h3 className="font-black">{t.label}</h3><p className={`mt-1 text-xs ${t.quota?.vencida||(!t.quota&&t.charge.vencido)?'text-red-300':'text-[#8995a4]'}`}>{t.quota?`${t.quota.vencida?'Vencida':'Vence'} ${t.quota.fecha_vencimiento}`:`${t.charge.vencido?'Vencido':'Vence'} ${t.charge.fecha_vencimiento||'Sin fecha'}`}</p></div><div className="text-right"><p className="text-lg font-black text-amber-300">{money(t.amount)}</p>{statement.metodos_pago?.acepta_transferencia?<button onClick={()=>openTransfer(t)} className="mt-2 text-xs font-black text-[#70e4df]">Informar transferencia</button>:null}</div></div></article>)}</section>}
 {selected.length?<section className="sticky bottom-4 rounded-3xl border border-[#289E9D]/30 bg-[#101820]/95 p-5 shadow-2xl backdrop-blur"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs uppercase tracking-wider text-[#8995a4]">{selected.length} concepto(s)</p><p className="text-2xl font-black">Total {money(totalSelected)}</p></div>{statement.metodos_pago?.acepta_pago_online?<button disabled={saving} onClick={()=>void payOnline()} className="rounded-xl bg-[#009ee3] px-6 py-3 font-black text-white disabled:opacity-50">💳 Pagar {money(totalSelected)} con Mercado Pago</button>:<p className="text-sm text-[#8995a4]">La academia no tiene pago online habilitado.</p>}</div></section>:null}
 <section className="grid gap-3 md:grid-cols-2">{statement.metodos_pago?.acepta_efectivo?<div className="rounded-2xl border border-white/10 bg-[#151b25] p-4"><p className="text-2xl">💵</p><h3 className="mt-2 font-black">Efectivo</h3><p className="mt-1 text-sm text-[#8995a4]">Pago presencial. La academia lo registra directamente.</p></div>:null}{statement.metodos_pago?.acepta_transferencia?<div className="rounded-2xl border border-white/10 bg-[#151b25] p-4"><p className="text-2xl">🏦</p><h3 className="mt-2 font-black">Transferencia</h3><p className="mt-1 text-sm text-[#b6c0cc]">{statement.metodos_pago.transferencia_banco||'Banco por confirmar'} · {statement.metodos_pago.transferencia_tipo_cuenta||''} {statement.metodos_pago.transferencia_numero||''}</p><p className="mt-2 text-xs text-[#8995a4]">Para informar una transferencia debes adjuntar el comprobante. No se descuenta la deuda hasta que la academia la valide.</p></div>:null}</section>
 </main>{transferTarget?<div className="fixed inset-0 z-[100] grid place-items-center overflow-y-auto bg-black/80 p-4"><form onSubmit={reportTransfer} className="w-full max-w-lg rounded-3xl border border-[#289E9D]/30 bg-[#151b25] p-6"><h2 className="text-xl font-black">Informar transferencia</h2><p className="mt-1 text-sm text-[#8995a4]">{transferTarget.label}</p><label className="mt-5 block text-xs font-bold text-[#8995a4]">Monto<input type="number" min="1" max={Math.round(transferTarget.amount)} required value={transfer.monto} onChange={e=>setTransfer({...transfer,monto:e.target.value})} className="mt-1 w-full rounded-xl border border-white/10 bg-[#0d1117] p-3 text-white"/></label><label className="mt-3 block text-xs font-bold text-[#8995a4]">Fecha de transferencia<input type="date" required value={transfer.fecha_pago} onChange={e=>setTransfer({...transfer,fecha_pago:e.target.value})} className="mt-1 w-full rounded-xl border border-white/10 bg-[#0d1117] p-3 text-white"/></label><label className="mt-3 block text-xs font-bold text-[#8995a4]">Comprobante PDF o imagen · máximo 5 MB<input type="file" required accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>setReceipt(e.target.files?.[0]||null)} className="mt-1 block w-full rounded-xl border border-dashed border-white/20 bg-[#0d1117] p-3 text-sm"/></label><label className="mt-3 block text-xs font-bold text-[#8995a4]">Observación opcional<textarea value={transfer.observaciones} onChange={e=>setTransfer({...transfer,observaciones:e.target.value})} className="mt-1 w-full rounded-xl border border-white/10 bg-[#0d1117] p-3 text-white"/></label><p className="mt-3 text-xs text-amber-200">Este aviso quedará pendiente. Solo Dirección puede validarlo y convertirlo en un pago contable.</p><div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={()=>setTransferTarget(null)} className="rounded-xl border border-white/10 px-4 py-3 font-black">Cancelar</button><button disabled={saving||!receipt} className="rounded-xl bg-[#289E9D] px-4 py-3 font-black disabled:opacity-50">{saving?'Enviando...':'Enviar comprobante'}</button></div></form></div>:null}</div>;
}
function Shell({children}:{children:React.ReactNode}){return <div className="min-h-screen bg-[#0d1117] px-5 py-12 text-white">{children}</div>}
function ErrorBox({text}:{text:string}){return <div className="mt-4 rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-200">{text}</div>}
