import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useSearchParams } from 'react-router-dom';
import api from '../api/axiosConfig';

type FinanceConfig={acepta_efectivo:boolean;acepta_transferencia:boolean;transferencia_banco:string;transferencia_tipo_cuenta:string;transferencia_numero:string;transferencia_rut:string;transferencia_correo:string};
type MpStatus={capabilities:{platformCheckout:boolean;marketplaceOAuth:boolean;webhookValidation:boolean};academy:{connected:boolean;status:string;mp_user_id?:number|null;connected_at?:string|null;token_expires_at?:string|null}};

const BANK_OPTIONS = [
 'BancoEstado',
 'Banco de Chile / Edwards',
 'Banco Internacional',
 'Scotiabank Chile',
 'BCI - Banco de Crédito e Inversiones',
 'Banco BICE',
 'Banco Santander-Chile',
 'Itaú Chile',
 'Banco Security',
 'Banco Falabella',
 'Banco Ripley',
 'Banco Consorcio',
 'Coopeuch',
 'Tenpo',
 'Mercado Pago',
 'MACH / Bci',
] as const;
const OTHER_BANK='__otra__';
const empty:FinanceConfig={acepta_efectivo:true,acepta_transferencia:false,transferencia_banco:'',transferencia_tipo_cuenta:'',transferencia_numero:'',transferencia_rut:'',transferencia_correo:''};

export default function FinanzasConfigV2(){
 const [params]=useSearchParams();const [config,setConfig]=useState<FinanceConfig>(empty);const [mp,setMp]=useState<MpStatus|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 const bankIsCatalogued=useMemo(()=>BANK_OPTIONS.some(bank=>bank===config.transferencia_banco),[config.transferencia_banco]);
 const bankSelectValue=config.transferencia_banco?(bankIsCatalogued?config.transferencia_banco:OTHER_BANK):'';
 const load=async()=>{setLoading(true);setError('');try{const [cfg,mpStatus]=await Promise.all([api.get('/api/finanzas/configuracion'),api.get('/api/mercadopago/status')]);setConfig(prev=>({...prev,...cfg.data.data,acepta_efectivo:cfg.data.data?.acepta_efectivo!==false,acepta_transferencia:cfg.data.data?.acepta_transferencia===true}));setMp(mpStatus.data.data);}catch(err:any){setError(err.response?.data?.error||'No fue posible cargar la configuración financiera.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);useEffect(()=>{if(params.get('mp')==='connected')setMessage('Mercado Pago conectado correctamente. Los pagos online podrán conciliarse de forma automática.');else if(params.get('mp')==='error')setError('Mercado Pago no pudo completar la vinculación. Intenta nuevamente.');},[params]);
 const save=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await api.put('/api/finanzas/configuracion',{...config,acepta_pago_online:Boolean(mp?.academy.connected),link_pago_online:''});setMessage('Configuración de recaudación guardada.');}catch(err:any){setError(err.response?.data?.error||'No fue posible guardar la configuración.');}finally{setSaving(false);}};
 const connect=async()=>{setSaving(true);setError('');try{const r=await api.post('/api/mercadopago/oauth/connect');window.location.assign(r.data.url);}catch(err:any){setError(err.response?.data?.error||'No fue posible iniciar la conexión con Mercado Pago.');setSaving(false);}};
 const disconnect=async()=>{if(!window.confirm('¿Desconectar Mercado Pago de esta academia? Los pagos online quedarán deshabilitados.'))return;setSaving(true);try{await api.post('/api/mercadopago/disconnect');setMessage('Mercado Pago fue desconectado.');await load();}catch(err:any){setError(err.response?.data?.error||'No fue posible desconectar Mercado Pago.');}finally{setSaving(false);}};
 const onBankChange=(value:string)=>{if(value===OTHER_BANK){setConfig(current=>({...current,transferencia_banco:bankIsCatalogued?'':current.transferencia_banco}));return;}setConfig(current=>({...current,transferencia_banco:value}));};
 if(loading)return <div className="py-16 text-center font-bold text-[#70e4df]">Cargando recaudación...</div>;
 return <div className="mx-auto max-w-5xl space-y-6 pb-12"><header><p className="text-xs font-black uppercase tracking-[.18em] text-[#70e4df]">Recaudación</p><h1 className="mt-1 text-3xl font-black text-white">Cómo recibe pagos tu academia</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#8995a4]">El dinero siempre llega a los medios de pago de la academia. Lestra organiza la deuda, valida transferencias y concilia automáticamente los pagos confirmados por Mercado Pago.</p></header>{message?<div className="rounded-2xl border border-emerald-400/20 bg-emerald-500/10 p-4 text-sm text-emerald-200">{message}</div>:null}{error?<div className="rounded-2xl border border-red-400/20 bg-red-500/10 p-4 text-sm text-red-200">{error}</div>:null}
 <form onSubmit={save} className="space-y-5"><section className="rounded-3xl border border-white/10 bg-[#151b25] p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-black text-white">💵 Efectivo</h2><p className="mt-1 text-sm text-[#8995a4]">Dirección registra el pago cuando recibe el dinero.</p></div><input type="checkbox" checked={config.acepta_efectivo} onChange={e=>setConfig({...config,acepta_efectivo:e.target.checked})} className="h-6 w-6 accent-[#289E9D]"/></div></section>
 <section className="rounded-3xl border border-white/10 bg-[#151b25] p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-black text-white">🏦 Transferencia bancaria</h2><p className="mt-1 text-sm text-[#8995a4]">El apoderado debe adjuntar comprobante. El saldo solo cambia cuando Dirección valida el pago.</p></div><input type="checkbox" checked={config.acepta_transferencia} onChange={e=>setConfig({...config,acepta_transferencia:e.target.checked})} className="h-6 w-6 accent-[#289E9D]"/></div>{config.acepta_transferencia?<div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-xs font-bold text-[#8995a4]">Banco / institución<select value={bankSelectValue} onChange={e=>onBankChange(e.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-[#0d1117] p-3 text-white"><option value="">Seleccionar banco o institución...</option>{BANK_OPTIONS.map(bank=><option key={bank} value={bank}>{bank}</option>)}<option value={OTHER_BANK}>Otra institución</option></select></label>{bankSelectValue===OTHER_BANK?<Field label="Otra institución" value={config.transferencia_banco} onChange={v=>setConfig({...config,transferencia_banco:v})}/>:<label className="text-xs font-bold text-[#8995a4]">Tipo de cuenta<select value={config.transferencia_tipo_cuenta} onChange={e=>setConfig({...config,transferencia_tipo_cuenta:e.target.value})} className="mt-1 w-full rounded-xl border border-white/10 bg-[#0d1117] p-3 text-white"><option value="">Seleccionar...</option><option>Cuenta Corriente</option><option>Cuenta Vista</option><option>Cuenta RUT</option><option>Chequera Electrónica</option></select></label>}{bankSelectValue===OTHER_BANK?<label className="text-xs font-bold text-[#8995a4]">Tipo de cuenta<select value={config.transferencia_tipo_cuenta} onChange={e=>setConfig({...config,transferencia_tipo_cuenta:e.target.value})} className="mt-1 w-full rounded-xl border border-white/10 bg-[#0d1117] p-3 text-white"><option value="">Seleccionar...</option><option>Cuenta Corriente</option><option>Cuenta Vista</option><option>Cuenta RUT</option><option>Chequera Electrónica</option></select></label>:null}<Field label="N° de cuenta" value={config.transferencia_numero} onChange={v=>setConfig({...config,transferencia_numero:v})}/><Field label="RUT titular" value={config.transferencia_rut} onChange={v=>setConfig({...config,transferencia_rut:v})}/><div className="md:col-span-2"><Field label="Correo de pagos (opcional)" type="email" value={config.transferencia_correo} onChange={v=>setConfig({...config,transferencia_correo:v})}/></div></div>:null}</section>
 <section className={`rounded-3xl border p-6 ${mp?.academy.connected?'border-sky-400/30 bg-sky-500/10':'border-white/10 bg-[#151b25]'}`}><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-xl font-black text-white">💳 Mercado Pago</h2><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${mp?.academy.connected?'bg-emerald-500/15 text-emerald-300':'bg-white/5 text-[#8995a4]'}`}>{mp?.academy.connected?'Conectado':'No conectado'}</span></div>{mp?.academy.connected?<><p className="mt-2 text-sm text-[#b9c5d2]">Los apoderados pagan el monto exacto de sus obligaciones y Mercado Pago confirma el resultado directamente a Lestra.</p><p className="mt-2 text-xs text-[#7f8b99]">Cuenta Mercado Pago: {mp.academy.mp_user_id||'vinculada'} · Conciliación automática activa</p></>:<p className="mt-2 max-w-2xl text-sm text-[#8995a4]">Conecta la cuenta Mercado Pago de la academia. El dinero llegará directamente a esa cuenta; Lestra no custodiará los fondos.</p>}</div>{mp?.academy.connected?<button type="button" disabled={saving} onClick={()=>void disconnect()} className="rounded-xl border border-red-400/20 px-5 py-3 font-black text-red-300">Desconectar</button>:<button type="button" disabled={saving||!mp?.capabilities.marketplaceOAuth} onClick={()=>void connect()} className="rounded-xl bg-[#009ee3] px-5 py-3 font-black text-white disabled:opacity-40">Conectar Mercado Pago</button>}</div>{!mp?.capabilities.marketplaceOAuth?<p className="mt-4 rounded-xl border border-amber-400/20 bg-amber-500/10 p-3 text-xs text-amber-200">La integración OAuth todavía necesita las credenciales de la aplicación Mercado Pago de Lestra.</p>:null}</section>
 <div className="flex justify-end"><button disabled={saving} className="rounded-xl bg-[#289E9D] px-7 py-3 font-black text-white disabled:opacity-50">{saving?'Guardando...':'Guardar configuración'}</button></div></form></div>;
}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="block text-xs font-bold text-[#8995a4]">{label}<input type={type} value={value||''} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-[#0d1117] p-3 text-white"/></label>}
