import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import api from '../api/axiosConfig';
import { useAcademyMessages } from '../hooks/useAcademyMessages';

type Branch={id:string;nombre:string;disciplina:string;sedes?:{id:string;nombre:string}|null};
type Summary={totalIngresosReales:number;totalPorCobrar:number;totalVencido:number;totalPorVencer:number;totalEgresos:number;balanceNeto:number;totalAlumnos:number;alumnosMorosos:number;tasaMorosidad:number;calendarioMensual?:{configured?:boolean;dueDay?:number;warningDays?:number}};
type Charge={id:string;concepto:string;tipo_concepto?:string|null;monto:number;monto_pagado:number;estado:string;fecha_vencimiento?:string|null;rama_id?:string|null;inscripcion_id?:string|null};
type Account={id:string;nombre:string;foto_base64?:string|null;foto_url?:string|null;avatar_url?:string|null;tutores?:{nombre_completo?:string|null;telefono?:string|null}|null;inscripcion?:{id:string;rama_id:string;categoria_id?:string|null}|null;cobros:Charge[];saldoTotalPendiente:number;saldoPendiente:number;alDia:boolean};
type Payment={id:string;monto:number;metodo_pago?:string|null;fecha_pago?:string|null;observaciones?:string|null;cobro?:{concepto?:string|null;tipo_concepto?:string|null}|null;jugador?:{nombre?:string|null}|null};
type Expense={id:string;concepto:string;categoria_gasto?:string|null;centro_costo?:string|null;monto:number;metodo_pago?:string|null;fecha_gasto?:string|null;rama_id?:string|null;ramas?:{id:string;nombre:string;disciplina:string}|null};
type FlowRow={id:string;tipo:'Ingreso'|'Egreso';concepto:string;monto:number;fecha?:string|null;metodo?:string|null;categoria?:string|null};
type Tab='cuentas'|'pagos'|'egresos'|'flujo';
const panel='rounded-[24px] border border-white/10 bg-[#151b25]';
const field='w-full rounded-xl border border-[#30363d] bg-[#0d1117] px-3 py-2.5 text-sm text-white outline-none focus:border-[#289E9D]';
const money=(value:number)=>`$${Math.round(Number(value)||0).toLocaleString('es-CL')}`;

export default function FinanzasMultirama(){
  const {confirmAction,notify}=useAcademyMessages();
  const [branches,setBranches]=useState<Branch[]>([]);
  const [branchId,setBranchId]=useState('');
  const [activeTab,setActiveTab]=useState<Tab>('cuentas');
  const [summary,setSummary]=useState<Summary|null>(null);
  const [accounts,setAccounts]=useState<Account[]>([]);
  const [payments,setPayments]=useState<Payment[]>([]);
  const [expenses,setExpenses]=useState<Expense[]>([]);
  const [flow,setFlow]=useState<FlowRow[]>([]);
  const [loading,setLoading]=useState(true);
  const [search,setSearch]=useState('');
  const [chargeModal,setChargeModal]=useState(false);
  const [expenseModal,setExpenseModal]=useState(false);
  const [paymentCharge,setPaymentCharge]=useState<Charge|null>(null);
  const [saving,setSaving]=useState(false);
  const [chargeForm,setChargeForm]=useState({jugador_id:'',concepto:'',tipo_concepto:'Otro',monto:'0',fecha_vencimiento:new Date().toISOString().slice(0,10),observaciones:''});
  const [expenseForm,setExpenseForm]=useState({concepto:'',categoria_gasto:'Otros',centro_costo:'',monto:'0',metodo_pago:'Transferencia',fecha_gasto:new Date().toISOString().slice(0,10),observaciones:''});
  const [paymentForm,setPaymentForm]=useState({monto_abono:'0',metodo_pago:'Transferencia',observaciones:'',idempotency_key:''});

  const params=useMemo(()=>branchId?{rama_id:branchId}:undefined,[branchId]);
  const load=useCallback(async()=>{
    setLoading(true);
    try{
      const [primaryResponse,summaryResponse,accountsResponse,paymentsResponse,expensesResponse,flowResponse]=await Promise.all([
        api.get('/api/academias/rama-principal'),
        api.get('/api/finanzas/resumen',{params}),
        api.get('/api/finanzas/cuentas-corrientes',{params}),
        api.get('/api/finanzas/pagos',{params}),
        api.get('/api/finanzas/egresos',{params}),
        api.get('/api/finanzas/flujo-caja',{params}),
      ]);
      setBranches(primaryResponse.data.data?.ramas||[]);
      setSummary(summaryResponse.data.data||null);
      setAccounts(accountsResponse.data.data||[]);
      setPayments(paymentsResponse.data.data||[]);
      setExpenses(expensesResponse.data.data||[]);
      setFlow(flowResponse.data.data||[]);
    }catch(error:any){await notify(error.response?.data?.error||'No fue posible cargar Finanzas.');}
    finally{setLoading(false);}
  },[params,notify]);
  useEffect(()=>{void load();},[load]);

  const branch=branches.find((item)=>item.id===branchId)||null;
  const filteredAccounts=accounts.filter((item)=>!search||item.nombre.toLowerCase().includes(search.toLowerCase())||item.tutores?.nombre_completo?.toLowerCase().includes(search.toLowerCase()));
  const openCharge=()=>{if(!branchId)return void notify('Selecciona una rama antes de asignar un cobro manual; así el cargo queda asociado a la inscripción deportiva correcta.');setChargeForm({jugador_id:'',concepto:'',tipo_concepto:'Otro',monto:'0',fecha_vencimiento:new Date().toISOString().slice(0,10),observaciones:''});setChargeModal(true);};
  const saveCharge=async(event:FormEvent)=>{event.preventDefault();if(!branchId)return;setSaving(true);try{await api.post('/api/finanzas/cobros',{...chargeForm,rama_id:branchId,monto:Number(chargeForm.monto)||0});setChargeModal(false);await load();await notify('Cobro creado en la inscripción deportiva seleccionada.');}catch(error:any){await notify(error.response?.data?.error||'No fue posible crear el cobro.');}finally{setSaving(false);}};
  const saveExpense=async(event:FormEvent)=>{event.preventDefault();setSaving(true);try{await api.post('/api/finanzas/egresos',{...expenseForm,rama_id:branchId||undefined,monto:Number(expenseForm.monto)||0,centro_costo:expenseForm.centro_costo||branch?.nombre||'General'});setExpenseModal(false);await load();await notify(branchId?'Egreso registrado en la rama.':'Egreso general registrado.');}catch(error:any){await notify(error.response?.data?.error||'No fue posible registrar el egreso.');}finally{setSaving(false);}};
  const openPayment=(charge:Charge)=>{const pending=Math.max(Number(charge.monto||0)-Number(charge.monto_pagado||0),0);setPaymentCharge(charge);setPaymentForm({monto_abono:String(pending),metodo_pago:'Transferencia',observaciones:'',idempotency_key:`finance-${charge.id}-${Date.now()}`});};
  const savePayment=async(event:FormEvent)=>{event.preventDefault();if(!paymentCharge)return;setSaving(true);try{await api.put(`/api/finanzas/cobros/${paymentCharge.id}/pagar`,{...paymentForm,monto_abono:Number(paymentForm.monto_abono)||0});setPaymentCharge(null);await load();await notify('Pago registrado.');}catch(error:any){await notify(error.response?.data?.error||'No fue posible registrar el pago.');}finally{setSaving(false);}};
  const removeExpense=async(expense:Expense)=>{const accepted=await confirmAction(`¿Anular el egreso “${expense.concepto}”?`);if(!accepted)return;try{await api.delete(`/api/finanzas/egresos/${expense.id}`);await load();}catch(error:any){await notify(error.response?.data?.error||'No fue posible anular el egreso.');}};

  return <div className="mx-auto max-w-7xl space-y-6 pb-16">
    <section className="rounded-[28px] border border-emerald-400/20 bg-[radial-gradient(circle_at_top_right,rgba(16,185,129,.14),transparent_38%),#151b25] p-6 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">ERP financiero multirrama</p><h1 className="mt-2 text-3xl font-black text-white">Finanzas</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#8b949e]">Puedes ver la academia consolidada o aislar una rama. Los cobros manuales, torneos, uniformes y competencias conservan la inscripción, sede y rama que los originaron.</p></div><select value={branchId} onChange={(event)=>setBranchId(event.target.value)} className={`${field} lg:max-w-md`}><option value="">Vista consolidada · toda la academia</option>{branches.map((item)=><option key={item.id} value={item.id}>{item.disciplina} · {item.nombre}{item.sedes?.nombre?` · ${item.sedes.nombre}`:''}</option>)}</select></div></section>

    {loading?<div className={`${panel} p-10 text-center text-emerald-300`}>Cargando estado financiero...</div>:<>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className={`${panel} p-5`}><p className="text-[10px] font-black uppercase text-[#697586]">Recaudado</p><p className="mt-1 text-2xl font-black text-emerald-300">{money(summary?.totalIngresosReales||0)}</p></div><div className={`${panel} p-5`}><p className="text-[10px] font-black uppercase text-[#697586]">Por cobrar</p><p className="mt-1 text-2xl font-black text-amber-300">{money(summary?.totalPorCobrar||0)}</p></div><div className={`${panel} p-5`}><p className="text-[10px] font-black uppercase text-[#697586]">Egresos</p><p className="mt-1 text-2xl font-black text-red-300">{money(summary?.totalEgresos||0)}</p></div><div className={`${panel} p-5`}><p className="text-[10px] font-black uppercase text-[#697586]">Balance {branch?`· ${branch.nombre}`:'consolidado'}</p><p className={`mt-1 text-2xl font-black ${(summary?.balanceNeto||0)>=0?'text-[#70e4df]':'text-red-300'}`}>{money(summary?.balanceNeto||0)}</p></div></section>
      <section className="grid gap-3 sm:grid-cols-3"><div className={`${panel} p-4 text-center`}><p className="text-[10px] uppercase text-[#697586]">Alumnos en alcance</p><p className="mt-1 text-xl font-black text-white">{summary?.totalAlumnos||0}</p></div><div className={`${panel} p-4 text-center`}><p className="text-[10px] uppercase text-[#697586]">Con deuda vencida</p><p className="mt-1 text-xl font-black text-red-300">{summary?.alumnosMorosos||0}</p></div><div className={`${panel} p-4 text-center`}><p className="text-[10px] uppercase text-[#697586]">Morosidad</p><p className="mt-1 text-xl font-black text-amber-300">{summary?.tasaMorosidad||0}%</p></div></section>

      <div className="flex flex-wrap gap-2"><button onClick={openCharge} className="rounded-xl bg-[#289E9D] px-4 py-2.5 text-sm font-black text-white">+ Cobro {branch?'de rama':'manual'}</button><button onClick={()=>setExpenseModal(true)} className="rounded-xl border border-red-400/20 bg-red-500/10 px-4 py-2.5 text-sm font-black text-red-300">- Registrar egreso</button>{!branchId?<span className="self-center text-xs text-[#697586]">Para crear un cobro manual selecciona una rama; los egresos sí pueden ser generales.</span>:null}</div>

      <div className="flex overflow-hidden rounded-xl border border-white/10 bg-[#0d1117]">{([['cuentas','Cuentas'],['pagos','Pagos'],['egresos','Egresos'],['flujo','Flujo']] as Array<[Tab,string]>).map(([key,label])=><button key={key} onClick={()=>setActiveTab(key)} className={`flex-1 px-3 py-3 text-sm font-black ${activeTab===key?'bg-[#289E9D] text-white':'text-[#8995a4]'}`}>{label}</button>)}</div>

      {activeTab==='cuentas'?<section className="space-y-4"><div className={`${panel} flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between`}><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Buscar alumno o apoderado" className={`${field} sm:max-w-md`}/><span className="text-xs text-[#8995a4]">{filteredAccounts.length} alumnos</span></div>{filteredAccounts.map((account)=><article key={account.id} className={`${panel} p-5`}><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="font-black text-white">{account.nombre}</h2><p className="mt-1 text-xs text-[#8995a4]">{account.tutores?.nombre_completo||'Sin apoderado'}{branch?` · ${branch.disciplina} · ${branch.nombre}`:''}</p></div><div className="text-right"><p className="text-[10px] uppercase text-[#697586]">Saldo pendiente</p><p className={`text-xl font-black ${Number(account.saldoTotalPendiente||0)>0?'text-amber-300':'text-emerald-300'}`}>{money(account.saldoTotalPendiente||0)}</p></div></div><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{(account.cobros||[]).filter((charge)=>charge.estado!=='Anulado').map((charge)=><div key={charge.id} className="rounded-xl border border-white/10 bg-[#0d1117] p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-black text-white">{charge.concepto}</p><p className="mt-1 text-[10px] uppercase text-[#697586]">{charge.tipo_concepto||'Cobro'} · {charge.fecha_vencimiento||'Sin vencimiento'}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-black ${charge.estado==='Pagado'?'bg-emerald-500/10 text-emerald-300':'bg-amber-500/10 text-amber-300'}`}>{charge.estado}</span></div><div className="mt-3 flex items-end justify-between"><div><p className="text-xs text-[#8995a4]">{money(charge.monto_pagado||0)} / {money(charge.monto||0)}</p></div>{charge.estado!=='Pagado'?<button onClick={()=>openPayment(charge)} className="rounded-lg border border-[#289E9D]/30 px-2.5 py-1.5 text-[10px] font-black text-[#70e4df]">Abonar</button>:null}</div></div>)}</div></article>)}{!filteredAccounts.length?<div className={`${panel} p-8 text-center text-sm text-[#697586]`}>No hay alumnos/cuentas en este alcance.</div>:null}</section>:null}

      {activeTab==='pagos'?<section className={`${panel} overflow-hidden`}><div className="border-b border-white/10 p-5"><h2 className="text-xl font-black text-white">Pagos registrados</h2><p className="text-xs text-[#8995a4]">{branch?`Solo ${branch.nombre}`:'Consolidado de la academia'}</p></div><div className="divide-y divide-white/10">{payments.map((payment)=><div key={payment.id} className="grid gap-2 p-4 md:grid-cols-[1fr_1.2fr_.6fr_.7fr]"><div><p className="font-black text-white">{payment.jugador?.nombre||'General'}</p><p className="text-xs text-[#697586]">{payment.fecha_pago?new Date(payment.fecha_pago).toLocaleString('es-CL'):'—'}</p></div><p className="text-sm text-[#c3ccd6]">{payment.cobro?.concepto||'Pago'}</p><p className="font-black text-emerald-300">{money(payment.monto)}</p><p className="text-sm text-[#8995a4]">{payment.metodo_pago||'—'}</p></div>)}{!payments.length?<div className="p-8 text-center text-sm text-[#697586]">Sin pagos en este alcance.</div>:null}</div></section>:null}

      {activeTab==='egresos'?<section className={`${panel} overflow-hidden`}><div className="border-b border-white/10 p-5"><h2 className="text-xl font-black text-white">Egresos</h2><p className="text-xs text-[#8995a4]">{branch?`Costos de ${branch.nombre}`:'Gastos generales y de todas las ramas'}</p></div><div className="divide-y divide-white/10">{expenses.map((expense)=><div key={expense.id} className="grid gap-2 p-4 md:grid-cols-[1.2fr_1fr_.6fr_auto]"><div><p className="font-black text-white">{expense.concepto}</p><p className="text-xs text-[#697586]">{expense.fecha_gasto||'—'} · {expense.ramas?.nombre||expense.centro_costo||'General'}</p></div><p className="text-sm text-[#c3ccd6]">{expense.categoria_gasto||'Otros'}</p><p className="font-black text-red-300">-{money(expense.monto)}</p><button onClick={()=>void removeExpense(expense)} className="rounded-lg border border-red-400/15 px-2.5 py-1.5 text-xs font-black text-red-300">Anular</button></div>)}{!expenses.length?<div className="p-8 text-center text-sm text-[#697586]">Sin egresos en este alcance.</div>:null}</div></section>:null}

      {activeTab==='flujo'?<section className={`${panel} overflow-hidden`}><div className="border-b border-white/10 p-5"><h2 className="text-xl font-black text-white">Flujo de caja</h2><p className="text-xs text-[#8995a4]">Ingresos y egresos ordenados cronológicamente.</p></div><div className="divide-y divide-white/10">{flow.map((row)=><div key={`${row.tipo}-${row.id}`} className="grid gap-2 p-4 md:grid-cols-[.5fr_1.5fr_.6fr_.7fr]"><span className={`w-fit rounded-full px-2 py-1 text-[10px] font-black ${row.tipo==='Ingreso'?'bg-emerald-500/10 text-emerald-300':'bg-red-500/10 text-red-300'}`}>{row.tipo}</span><div><p className="text-sm font-black text-white">{row.concepto}</p><p className="text-xs text-[#697586]">{row.categoria||''}</p></div><p className={`font-black ${row.tipo==='Ingreso'?'text-emerald-300':'text-red-300'}`}>{row.tipo==='Ingreso'?'+':'-'}{money(row.monto)}</p><p className="text-sm text-[#8995a4]">{row.fecha?new Date(row.fecha).toLocaleDateString('es-CL'):'—'} · {row.metodo||'—'}</p></div>)}{!flow.length?<div className="p-8 text-center text-sm text-[#697586]">Sin movimientos en este alcance.</div>:null}</div></section>:null}
    </>}

    {chargeModal?<div className="fixed inset-0 z-[70] grid place-items-center bg-black/80 p-4"><form onSubmit={saveCharge} className="w-full max-w-lg rounded-[26px] border border-white/10 bg-[#151b25] p-6"><h2 className="text-2xl font-black text-white">Cobro · {branch?.nombre}</h2><p className="mt-1 text-xs text-[#8995a4]">Solo alumnos con inscripción activa en esta rama.</p><div className="mt-5 space-y-3"><select required value={chargeForm.jugador_id} onChange={(event)=>setChargeForm({...chargeForm,jugador_id:event.target.value})} className={field}><option value="">Selecciona alumno</option>{accounts.map((account)=><option key={account.id} value={account.id}>{account.nombre}</option>)}</select><input required value={chargeForm.concepto} onChange={(event)=>setChargeForm({...chargeForm,concepto:event.target.value})} className={field} placeholder="Concepto"/><div className="grid grid-cols-2 gap-3"><select value={chargeForm.tipo_concepto} onChange={(event)=>setChargeForm({...chargeForm,tipo_concepto:event.target.value})} className={field}><option>Otro</option><option>Mensualidad</option><option>Matrícula</option><option>Indumentaria</option><option>Torneo</option><option>Partido</option></select><input type="number" min="1" required value={chargeForm.monto} onChange={(event)=>setChargeForm({...chargeForm,monto:event.target.value})} className={field}/></div><input type="date" value={chargeForm.fecha_vencimiento} onChange={(event)=>setChargeForm({...chargeForm,fecha_vencimiento:event.target.value})} className={field}/><textarea value={chargeForm.observaciones} onChange={(event)=>setChargeForm({...chargeForm,observaciones:event.target.value})} className={`${field} min-h-20`} placeholder="Observaciones"/></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setChargeModal(false)} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-black">Cancelar</button><button disabled={saving} className="rounded-xl bg-[#289E9D] px-4 py-2.5 text-sm font-black text-white disabled:opacity-40">Guardar cobro</button></div></form></div>:null}

    {expenseModal?<div className="fixed inset-0 z-[70] grid place-items-center bg-black/80 p-4"><form onSubmit={saveExpense} className="w-full max-w-lg rounded-[26px] border border-white/10 bg-[#151b25] p-6"><h2 className="text-2xl font-black text-white">Registrar egreso</h2><p className="mt-1 text-xs text-[#8995a4]">{branch?`Se imputará a ${branch.nombre}.`:'Se registrará como gasto general de la academia.'}</p><div className="mt-5 space-y-3"><input required value={expenseForm.concepto} onChange={(event)=>setExpenseForm({...expenseForm,concepto:event.target.value})} className={field} placeholder="Concepto"/><div className="grid grid-cols-2 gap-3"><input value={expenseForm.categoria_gasto} onChange={(event)=>setExpenseForm({...expenseForm,categoria_gasto:event.target.value})} className={field} placeholder="Categoría de gasto"/><input type="number" min="1" required value={expenseForm.monto} onChange={(event)=>setExpenseForm({...expenseForm,monto:event.target.value})} className={field}/></div><input value={expenseForm.centro_costo} onChange={(event)=>setExpenseForm({...expenseForm,centro_costo:event.target.value})} className={field} placeholder={branch?.nombre||'Centro de costo general'}/><div className="grid grid-cols-2 gap-3"><select value={expenseForm.metodo_pago} onChange={(event)=>setExpenseForm({...expenseForm,metodo_pago:event.target.value})} className={field}><option>Transferencia</option><option>Efectivo</option><option>Tarjeta</option><option>Otro</option></select><input type="date" value={expenseForm.fecha_gasto} onChange={(event)=>setExpenseForm({...expenseForm,fecha_gasto:event.target.value})} className={field}/></div><textarea value={expenseForm.observaciones} onChange={(event)=>setExpenseForm({...expenseForm,observaciones:event.target.value})} className={`${field} min-h-20`} placeholder="Observaciones"/></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setExpenseModal(false)} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-black">Cancelar</button><button disabled={saving} className="rounded-xl bg-red-600 px-4 py-2.5 text-sm font-black text-white disabled:opacity-40">Guardar egreso</button></div></form></div>:null}

    {paymentCharge?<div className="fixed inset-0 z-[80] grid place-items-center bg-black/80 p-4"><form onSubmit={savePayment} className="w-full max-w-md rounded-[26px] border border-white/10 bg-[#151b25] p-6"><h2 className="text-2xl font-black text-white">Registrar abono</h2><p className="mt-1 text-sm text-[#8995a4]">{paymentCharge.concepto}</p><div className="mt-5 space-y-3"><input type="number" min="1" required value={paymentForm.monto_abono} onChange={(event)=>setPaymentForm({...paymentForm,monto_abono:event.target.value})} className={field}/><select value={paymentForm.metodo_pago} onChange={(event)=>setPaymentForm({...paymentForm,metodo_pago:event.target.value})} className={field}><option>Transferencia</option><option>Efectivo</option><option>Tarjeta</option><option>Otro</option></select><textarea value={paymentForm.observaciones} onChange={(event)=>setPaymentForm({...paymentForm,observaciones:event.target.value})} className={`${field} min-h-20`} placeholder="Observaciones"/></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setPaymentCharge(null)} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-black">Cancelar</button><button disabled={saving} className="rounded-xl bg-[#289E9D] px-4 py-2.5 text-sm font-black text-white disabled:opacity-40">Registrar pago</button></div></form></div>:null}
  </div>;
}
