import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import api from '../api/axiosConfig';
import { useAppDialog } from '../contexts/DialogContext';
import { DIRECTOR_BUTTON, DIRECTOR_BUTTON_DARK, DIRECTOR_FIELD, DirectorHero, DirectorPage, DirectorPanel, DirectorStat } from '../components/director/DirectorModule';

type Tournament={id:string;nombre:string;fecha_inicio?:string|null;fecha_fin?:string|null;costo_inscripcion:number;permite_cuotas:boolean;max_cuotas:number;rama_id?:string|null;sede_id?:string|null;organizador?:string|null;ubicacion?:string|null;reglamento_url?:string|null;ramas?:{id:string;nombre:string;disciplina:string}|null;sedes?:{id:string;nombre:string}|null};
type Category={id:string;nombre:string;rama_id?:string|null;sede_id?:string|null;ramas?:{id:string;nombre:string;disciplina:string}|null};
type Student={id:string;nombre:string;foto_url?:string|null;avatar_url?:string|null;foto_base64?:string|null;inscripcion?:{id:string;rama_id:string;categoria_id?:string|null;rol_especialidad?:string|null}|null};
type Participant={id:string;jugador_id:string;categoria_id?:string|null;respuesta_participacion:string;estado_pago:string;numero_cuotas?:number|null;jugadores?:{id:string;nombre:string;foto_url?:string|null;foto_base64?:string|null}|null;categorias?:{id:string;nombre:string}|null};
type CompetitionEvent={id:string;rival:string;fecha:string;hora:string;estado:string;goles_favor?:number|null;goles_contra?:number|null;categorias?:{id?:string;nombre:string}|null;sport_profile?:{icon?:string;activityLabel?:string;scoreLabel?:string;usesHeadToHeadScore?:boolean}|null};
const money=(value:number)=>`$${Math.round(Number(value)||0).toLocaleString('es-CL')}`;
const photo=(student?:{foto_url?:string|null;foto_base64?:string|null}|null)=>student?.foto_url||student?.foto_base64||'';

export default function GestionarTorneoMultirama(){
  const {id}=useParams();
  const {notify,confirmAction}=useAppDialog();
  const [tournament,setTournament]=useState<Tournament|null>(null);
  const [categories,setCategories]=useState<Category[]>([]);
  const [categoryId,setCategoryId]=useState('');
  const [eligible,setEligible]=useState<Student[]>([]);
  const [participants,setParticipants]=useState<Participant[]>([]);
  const [events,setEvents]=useState<CompetitionEvent[]>([]);
  const [selected,setSelected]=useState<string[]>([]);
  const [loading,setLoading]=useState(true);
  const [sending,setSending]=useState(false);

  const reloadParticipants=async()=>{if(!id)return;const response=await api.get(`/api/torneos/${id}/participantes`);setParticipants(response.data.data||[]);};
  useEffect(()=>{const load=async()=>{if(!id)return;setLoading(true);try{const tournamentResponse=await api.get(`/api/torneos/${id}`);const t=tournamentResponse.data.data as Tournament;setTournament(t);const requests:Promise<any>[]=[api.get(`/api/torneos/${id}/participantes`),api.get('/api/partidos',{params:{torneo_id:id}})];if(t.rama_id)requests.push(api.get('/api/jugadores/categorias',{params:{rama_id:t.rama_id}}));const responses=await Promise.all(requests);setParticipants(responses[0].data.data||[]);setEvents(responses[1].data.data||[]);if(t.rama_id)setCategories(responses[2]?.data?.data||[]);}catch(error:any){await notify(error.response?.data?.error||'No fue posible cargar la competencia.');}finally{setLoading(false);}};void load();},[id,notify]);
  useEffect(()=>{const loadEligible=async()=>{if(!id||!categoryId){setEligible([]);setSelected([]);return;}try{const response=await api.get(`/api/torneos/${id}/elegibles`,{params:{categoria_id:categoryId}});const students=response.data.data||[];setEligible(students);const already=new Set(participants.filter(item=>item.categoria_id===categoryId).map(item=>String(item.jugador_id)));setSelected(students.filter((student:Student)=>!already.has(String(student.id))).map((student:Student)=>student.id));}catch(error:any){await notify(error.response?.data?.error||'No fue posible cargar alumnos elegibles.');}};void loadEligible();},[id,categoryId,participants,notify]);
  const selectedCategory=categories.find(category=>category.id===categoryId)||null;
  const stats=useMemo(()=>({total:participants.length,confirmados:participants.filter(item=>item.respuesta_participacion==='Si').length,rechazados:participants.filter(item=>item.respuesta_participacion==='No').length,pagados:participants.filter(item=>item.estado_pago==='Pagado').length}),[participants]);
  const eventStats=useMemo(()=>({total:events.length,jugados:events.filter(item=>item.estado==='Jugado').length,pendientes:events.filter(item=>item.estado!=='Jugado').length}),[events]);
  const toggle=(studentId:string)=>setSelected(current=>current.includes(studentId)?current.filter(item=>item!==studentId):[...current,studentId]);
  const send=async()=>{if(!id||!categoryId||!selected.length)return void notify('Selecciona categoría y al menos un alumno.');const accepted=await confirmAction(`Se convocará a ${selected.length} alumno(s) de ${selectedCategory?.nombre||'la categoría'}. La inscripción del campeonato se cobrará una sola vez por alumno, aunque participe en más de una categoría.`,{confirmLabel:'Enviar convocatoria'});if(!accepted)return;setSending(true);try{const response=await api.post(`/api/torneos/${id}/convocar`,{categoria_id:categoryId,jugadoresIds:selected});await notify(response.data.message||'Convocatorias enviadas.');await reloadParticipants();setSelected([]);}catch(error:any){await notify(error.response?.data?.error||'No fue posible convocar.');}finally{setSending(false);}};

  if(loading)return <DirectorPanel className="mx-auto max-w-6xl p-12 text-center text-sm font-bold text-[#697468]">Cargando competencia...</DirectorPanel>;
  if(!tournament)return <div className="rounded-[18px] border border-red-200 bg-red-50 p-5 text-red-700">Competencia no encontrada.</div>;

  return <DirectorPage>
    <DirectorHero eyebrow={tournament.ramas?.disciplina||'Competencia'} title={tournament.nombre} description={<>{tournament.ramas?.nombre||'Sin rama'}{tournament.sedes?.nombre?` · ${tournament.sedes.nombre}`:''} · {tournament.fecha_inicio||'Fecha por definir'}{tournament.fecha_fin&&tournament.fecha_fin!==tournament.fecha_inicio?` → ${tournament.fecha_fin}`:''}{tournament.organizador?<><br/>Organiza: {tournament.organizador}</>:null}</>} actions={<><Link to="/torneos" className={DIRECTOR_BUTTON_DARK}>← Competencias</Link><Link to={`/partidos?torneo_id=${tournament.id}`} className={DIRECTOR_BUTTON}>+ Agregar evento</Link></>} aside={<div className="rounded-[20px] border border-white/15 bg-white/[.055] p-5"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#b7ff00]">Inscripción por alumno</p><p className="mt-2 text-xl font-black text-white">{Number(tournament.costo_inscripcion)>0?money(tournament.costo_inscripcion):'Gratuita'}</p><p className="mt-1 text-xs font-semibold text-[#c7d0c8]">{tournament.permite_cuotas?`Hasta ${tournament.max_cuotas} cuotas`:'Pago único'}</p></div>}/>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><DirectorStat label="Convocados" value={stats.total}/><DirectorStat label="Confirmados" value={stats.confirmados} tone="lime"/><DirectorStat label="Eventos" value={eventStats.total}/><DirectorStat label="Pagados" value={stats.pagados} tone="dark"/></section>

    <DirectorPanel className="p-5 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-black uppercase tracking-[.14em] text-[#789600]">Eventos de esta competencia</p><h2 className="mt-1 text-2xl font-black tracking-[-.03em] text-[#111711]">Partidos, duelos, pruebas y presentaciones</h2><p className="mt-1 text-sm text-[#697468]">Cada evento alimenta los resultados de la academia y el rendimiento de sus alumnos.</p></div><div className="flex gap-2"><span className="rounded-full border border-[#cde995] bg-[#f3fadf] px-3 py-1 text-xs font-black text-[#5f7900]">{eventStats.jugados} finalizados</span><span className="rounded-full border border-[#d9e0d6] bg-[#f5f7f3] px-3 py-1 text-xs font-black text-[#697468]">{eventStats.pendientes} pendientes</span></div></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{events.slice(0,9).map(event=><article key={event.id} className="rounded-[18px] border border-[#dfe5dc] bg-[#f8faf6] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#789600]">{event.sport_profile?.icon||'🏅'} {event.sport_profile?.activityLabel||'Evento'}</p><h3 className="mt-1 font-black text-[#111711]">{event.rival}</h3><p className="mt-1 text-xs text-[#697468]">{event.categorias?.nombre||'Sin categoría'} · {event.fecha} · {String(event.hora||'').slice(0,5)}</p></div><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${event.estado==='Jugado'?'bg-[#e8f6d0] text-[#416400]':'bg-white text-[#697468]'}`}>{event.estado}</span></div>{event.estado==='Jugado'&&event.sport_profile?.usesHeadToHeadScore?<p className="mt-3 rounded-xl bg-[#111711] p-2 text-center text-sm font-black text-white">{event.goles_favor||0} — {event.goles_contra||0} {event.sport_profile?.scoreLabel||''}</p>:null}</article>)}{!events.length?<div className="col-span-full rounded-[18px] border border-dashed border-[#d9e0d6] p-8 text-center"><p className="text-sm font-black text-[#111711]">Aún no hay eventos registrados.</p><p className="mt-1 text-xs text-[#697468]">Agrega el primer evento de esta competencia.</p><Link to={`/partidos?torneo_id=${tournament.id}`} className={`${DIRECTOR_BUTTON} mt-4`}>Agregar evento</Link></div>:null}</div>{events.length>9?<div className="mt-4 text-right"><Link to={`/partidos?torneo_id=${tournament.id}`} className="text-xs font-black text-[#5f7900]">Ver todos los eventos →</Link></div>:null}</DirectorPanel>

    <DirectorPanel className="p-5 sm:p-6"><div><p className="text-[11px] font-black uppercase tracking-[.14em] text-[#789600]">Convocatoria al campeonato</p><h2 className="mt-1 text-2xl font-black tracking-[-.03em] text-[#111711]">Seleccionar alumnos por categoría</h2><p className="mt-1 text-sm text-[#697468]">Esta convocatoria controla la inscripción al campeonato. Las citaciones de fecha y hora se gestionan después desde cada evento.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><select value={categoryId} onChange={(event)=>setCategoryId(event.target.value)} className={DIRECTOR_FIELD}><option value="">Selecciona categoría</option>{categories.map(category=><option key={category.id} value={category.id}>{category.nombre}</option>)}</select><button disabled={!selected.length||sending} onClick={()=>void send()} className={DIRECTOR_BUTTON}>{sending?'Enviando...':`Convocar ${selected.length||''}`}</button></div>{categoryId?<div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{eligible.map(student=>{const checked=selected.includes(student.id);const already=participants.some(item=>item.categoria_id===categoryId&&String(item.jugador_id)===String(student.id));return <button type="button" disabled={already} onClick={()=>toggle(student.id)} key={student.id} className={`flex items-center gap-3 rounded-[16px] border p-3 text-left transition ${already?'border-[#cde995] bg-[#f3fadf] opacity-75':checked?'border-[#9fcf00] bg-[#f3fadf]':'border-[#dfe5dc] bg-[#f8faf6] hover:border-[#aebaa9]'}`}>{photo(student)?<img src={photo(student)} alt="" className="h-10 w-10 rounded-xl object-cover"/>:<div className="grid h-10 w-10 place-items-center rounded-xl bg-[#111711] text-sm font-black text-white">{student.nombre?.slice(0,1)||'A'}</div>}<div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-[#111711]">{student.nombre}</p><p className="text-[10px] text-[#697468]">{already?'Ya convocado':student.inscripcion?.rol_especialidad||'Disponible'}</p></div><span className={`grid h-5 w-5 place-items-center rounded-full border text-[10px] ${already||checked?'border-[#9fcf00] bg-[#b7ff00] text-[#111711]':'border-[#b8c1b6] bg-white'}`}>{already||checked?'✓':''}</span></button>})}{!eligible.length?<div className="col-span-full rounded-[16px] border border-dashed border-[#d9e0d6] p-6 text-center text-xs text-[#697468]">No hay alumnos elegibles en esta categoría.</div>:null}</div>:null}</DirectorPanel>

    <DirectorPanel className="p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[11px] font-black uppercase tracking-[.14em] text-[#789600]">Participación registrada</p><h2 className="mt-1 text-2xl font-black tracking-[-.03em] text-[#111711]">Alumnos del campeonato</h2></div><div className="flex flex-wrap gap-2"><span className="rounded-full border border-[#cde995] bg-[#f3fadf] px-3 py-1 text-xs font-black text-[#5f7900]">{stats.confirmados} confirmados</span><span className="rounded-full border border-[#d9e0d6] bg-[#f5f7f3] px-3 py-1 text-xs font-black text-[#111711]">{stats.pagados} pagados</span>{stats.rechazados?<span className="rounded-full border border-red-200 bg-red-50 px-3 py-1 text-xs font-black text-red-700">{stats.rechazados} no participan</span>:null}</div></div><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{participants.map(participant=><div key={participant.id} className="flex items-center gap-3 rounded-[16px] border border-[#dfe5dc] bg-[#f8faf6] p-3">{photo(participant.jugadores)?<img src={photo(participant.jugadores)} alt="" className="h-10 w-10 rounded-xl object-cover"/>:<div className="grid h-10 w-10 place-items-center rounded-xl bg-[#111711] text-sm font-black text-white">{participant.jugadores?.nombre?.slice(0,1)||'A'}</div>}<div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-[#111711]">{participant.jugadores?.nombre||'Alumno'}</p><p className="text-[10px] text-[#697468]">{participant.categorias?.nombre||'Categoría'} · {participant.respuesta_participacion==='Si'?'Confirmado':participant.respuesta_participacion==='No'?'No participa':'Pendiente'} · {participant.estado_pago||'Pendiente'}</p></div></div>)}{!participants.length?<div className="col-span-full rounded-[16px] border border-dashed border-[#d9e0d6] p-8 text-center text-sm text-[#697468]">Aún no hay alumnos convocados.</div>:null}</div></DirectorPanel>
    {tournament.reglamento_url?<DirectorPanel className="border-[#cde995] bg-[#f3fadf] p-4"><p className="text-sm font-black text-[#435b00]">Bases o reglamento</p><a href={tournament.reglamento_url} target="_blank" rel="noreferrer" className="mt-1 block break-all text-xs font-semibold text-[#5f6900] underline">{tournament.reglamento_url}</a></DirectorPanel>:null}
  </DirectorPage>;
}
