import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import api from '../api/axiosConfig';
import { useAppDialog } from '../contexts/DialogContext';

type Tournament={id:string;nombre:string;fecha_inicio?:string|null;fecha_fin?:string|null;costo_inscripcion:number;permite_cuotas:boolean;max_cuotas:number;rama_id?:string|null;sede_id?:string|null;tipo_gestion?:'externo'|'organizado';formato_competencia?:string;estructura_estado?:string;organizador?:string|null;ubicacion?:string|null;reglamento_url?:string|null;ramas?:{id:string;nombre:string;disciplina:string}|null;sedes?:{id:string;nombre:string}|null};
type Category={id:string;nombre:string;rama_id?:string|null;sede_id?:string|null;ramas?:{id:string;nombre:string;disciplina:string}|null};
type Student={id:string;nombre:string;foto_url?:string|null;avatar_url?:string|null;foto_base64?:string|null;inscripcion?:{id:string;rama_id:string;categoria_id?:string|null;rol_especialidad?:string|null}|null};
type Participant={id:string;jugador_id:string;categoria_id?:string|null;respuesta_participacion:string;estado_pago:string;numero_cuotas?:number|null;jugadores?:{id:string;nombre:string;foto_url?:string|null;foto_base64?:string|null}|null;categorias?:{id:string;nombre:string}|null};
type Division={id:string;nombre:string;modalidad?:string|null;categoria_id?:string|null;orden:number;categorias?:{id:string;nombre:string}|null};
type Phase={id:string;division_id?:string|null;nombre:string;tipo:string;orden:number;estado:string};
type CompetitionFormat={code:string;label:string;description:string;blueprint?:string[]};
type StructureResponse={torneo:Tournament;arquitectura?:{formats?:CompetitionFormat[]};divisiones:Division[];fases:Phase[];competidores?:unknown[]};
const panel='rounded-[24px] border border-white/10 bg-[#151b25]';
const field='w-full rounded-xl border border-[#30363d] bg-[#0d1117] px-3 py-2.5 text-sm text-white outline-none focus:border-[#C8A96B]';
const money=(value:number)=>`$${Math.round(Number(value)||0).toLocaleString('es-CL')}`;
const formatLabel=(code?:string)=>({seguimiento:'Seguimiento externo',liga:'Liga / todos contra todos',grupos_eliminacion:'Grupos + eliminación',eliminacion_directa:'Eliminación directa',doble_eliminacion:'Doble eliminación',pools:'Pools',repechaje:'Llaves con repechaje',rondas_clasificacion:'Rondas de clasificación',pruebas_ranking:'Pruebas + ranking',personalizado:'Estructura personalizada'}[code||'']||'Sin formato');

export default function GestionarTorneoMultirama(){
  const {id}=useParams();
  const {notify,confirmAction}=useAppDialog();
  const [tournament,setTournament]=useState<Tournament|null>(null);
  const [categories,setCategories]=useState<Category[]>([]);
  const [categoryId,setCategoryId]=useState('');
  const [eligible,setEligible]=useState<Student[]>([]);
  const [participants,setParticipants]=useState<Participant[]>([]);
  const [selected,setSelected]=useState<string[]>([]);
  const [structure,setStructure]=useState<StructureResponse|null>(null);
  const [divisionForm,setDivisionForm]=useState({nombre:'',categoria_id:'',modalidad:''});
  const [phaseForm,setPhaseForm]=useState({division_id:'',nombre:'',tipo:'ronda'});
  const [loading,setLoading]=useState(true);
  const [sending,setSending]=useState(false);
  const [savingStructure,setSavingStructure]=useState(false);

  const reloadStructure=async()=>{
    if(!id)return;
    const response=await api.get(`/api/torneos/${id}/estructura`);
    setStructure(response.data.data||null);
  };

  useEffect(()=>{const load=async()=>{if(!id)return;setLoading(true);try{const tournamentResponse=await api.get(`/api/torneos/${id}`);const t=tournamentResponse.data.data as Tournament;setTournament(t);const requests:Promise<any>[]=[api.get(`/api/torneos/${id}/participantes`),api.get(`/api/torneos/${id}/estructura`)];if(t.rama_id)requests.push(api.get('/api/jugadores/categorias',{params:{rama_id:t.rama_id}}));const responses=await Promise.all(requests);setParticipants(responses[0].data.data||[]);setStructure(responses[1].data.data||null);if(t.rama_id)setCategories(responses[2]?.data?.data||[]);}catch(error:any){await notify(error.response?.data?.error||'No fue posible cargar la competencia.');}finally{setLoading(false);}};void load();},[id,notify]);

  useEffect(()=>{const loadEligible=async()=>{if(!id||!categoryId){setEligible([]);setSelected([]);return;}try{const response=await api.get(`/api/torneos/${id}/elegibles`,{params:{categoria_id:categoryId}});const students=response.data.data||[];setEligible(students);const already=new Set(participants.filter((item)=>item.categoria_id===categoryId).map((item)=>String(item.jugador_id)));setSelected(students.filter((student:Student)=>!already.has(String(student.id))).map((student:Student)=>student.id));}catch(error:any){await notify(error.response?.data?.error||'No fue posible cargar alumnos elegibles.');}};void loadEligible();},[id,categoryId,participants,notify]);

  const selectedCategory=categories.find((category)=>category.id===categoryId)||null;
  const stats=useMemo(()=>({total:participants.length,confirmados:participants.filter((item)=>item.respuesta_participacion==='Si').length,rechazados:participants.filter((item)=>item.respuesta_participacion==='No').length,pagados:participants.filter((item)=>item.estado_pago==='Pagado').length}),[participants]);
  const selectedFormat=structure?.arquitectura?.formats?.find((item)=>item.code===(tournament?.formato_competencia||'seguimiento'))||null;
  const toggle=(studentId:string)=>setSelected((current)=>current.includes(studentId)?current.filter((item)=>item!==studentId):[...current,studentId]);

  const send=async()=>{
    if(!id||!categoryId||!selected.length)return void notify('Selecciona categoría y al menos un alumno.');
    const accepted=await confirmAction(`Se convocará a ${selected.length} alumno(s) de ${selectedCategory?.nombre||'la categoría'} y se generarán los cobros del torneo en esta rama.`,{confirmLabel:'Enviar convocatoria'});if(!accepted)return;
    setSending(true);try{const response=await api.post(`/api/torneos/${id}/convocar`,{categoria_id:categoryId,jugadoresIds:selected});await notify(response.data.message||'Convocatorias enviadas.');const participantsResponse=await api.get(`/api/torneos/${id}/participantes`);setParticipants(participantsResponse.data.data||[]);setSelected([]);}catch(error:any){await notify(error.response?.data?.error||'No fue posible convocar.');}finally{setSending(false);}
  };

  const addDivision=async()=>{
    if(!id||!divisionForm.nombre.trim())return void notify('Ingresa el nombre de la división o modalidad.');
    setSavingStructure(true);try{await api.post(`/api/torneos/${id}/divisiones`,divisionForm);setDivisionForm({nombre:'',categoria_id:'',modalidad:''});await reloadStructure();await notify('División agregada a la estructura.');}catch(error:any){await notify(error.response?.data?.error||'No fue posible crear la división.');}finally{setSavingStructure(false);}
  };

  const addPhase=async()=>{
    if(!id||!phaseForm.nombre.trim())return void notify('Ingresa el nombre de la fase.');
    setSavingStructure(true);try{await api.post(`/api/torneos/${id}/fases`,phaseForm);setPhaseForm((current)=>({...current,nombre:''}));await reloadStructure();await notify('Fase agregada.');}catch(error:any){await notify(error.response?.data?.error||'No fue posible crear la fase.');}finally{setSavingStructure(false);}
  };

  const removeDivision=async(division:Division)=>{
    if(!id)return;const accepted=await confirmAction(`Eliminar la división “${division.nombre}” y sus fases configuradas?`,{confirmLabel:'Eliminar división'});if(!accepted)return;try{await api.delete(`/api/torneos/${id}/divisiones/${division.id}`);if(phaseForm.division_id===division.id)setPhaseForm({division_id:'',nombre:'',tipo:'ronda'});await reloadStructure();}catch(error:any){await notify(error.response?.data?.error||'No fue posible eliminar la división.');}
  };

  const removePhase=async(phase:Phase)=>{
    if(!id)return;try{await api.delete(`/api/torneos/${id}/fases/${phase.id}`);await reloadStructure();}catch(error:any){await notify(error.response?.data?.error||'No fue posible eliminar la fase.');}
  };

  if(loading)return <div className="grid min-h-[50vh] place-items-center text-[#D8BE87]">Cargando competencia...</div>;
  if(!tournament)return <div className="rounded-xl border border-red-500/20 bg-red-500/10 p-5 text-red-200">Competencia no encontrada.</div>;
  const organized=tournament.tipo_gestion==='organizado';

  return <div className="mx-auto max-w-7xl space-y-6 pb-16"><div className="flex flex-wrap items-center justify-between gap-3"><Link to="/torneos" className="rounded-xl border border-white/10 px-4 py-2 text-sm font-black text-[#c3ccd6]">← Competencias</Link><Link to="/partidos" className="rounded-xl border border-[#C8A96B]/30 bg-[#C8A96B]/10 px-4 py-2 text-sm font-black text-[#D8BE87]">Ir a encuentros</Link></div>
    <section className="rounded-[28px] border border-[#C8A96B]/25 bg-[radial-gradient(circle_at_top_right,rgba(200,169,107,.16),transparent_36%),#151b25] p-6 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-violet-500/10 px-3 py-1 text-[10px] font-black uppercase text-violet-300">{tournament.ramas?.disciplina||'Competencia histórica'}</span><span className={`rounded-full px-3 py-1 text-[10px] font-black uppercase ${organized?'bg-emerald-500/10 text-emerald-300':'bg-sky-500/10 text-sky-300'}`}>{organized?'Organizada por la academia':'Campeonato externo'}</span></div><h1 className="mt-3 text-3xl font-black text-white">{tournament.nombre}</h1><p className="mt-2 text-sm text-[#8b949e]">{tournament.ramas?.nombre||'Sin rama'}{tournament.sedes?.nombre?` · ${tournament.sedes.nombre}`:''} · {tournament.fecha_inicio||'Fecha por definir'} · {Number(tournament.costo_inscripcion)>0?money(tournament.costo_inscripcion):'Gratuito'}</p><p className="mt-1 text-xs text-[#697586]">{formatLabel(tournament.formato_competencia)}{tournament.organizador?` · Organiza: ${tournament.organizador}`:''}</p></div><div className="grid grid-cols-4 gap-2 text-center"><div className="rounded-xl bg-[#0d1117] p-3"><p className="text-[9px] uppercase text-[#697586]">Convocados</p><p className="font-black text-white">{stats.total}</p></div><div className="rounded-xl bg-emerald-500/10 p-3"><p className="text-[9px] uppercase text-emerald-300">Sí</p><p className="font-black text-emerald-200">{stats.confirmados}</p></div><div className="rounded-xl bg-red-500/10 p-3"><p className="text-[9px] uppercase text-red-300">No</p><p className="font-black text-red-200">{stats.rechazados}</p></div><div className="rounded-xl bg-[#C8A96B]/10 p-3"><p className="text-[9px] uppercase text-[#D8BE87]">Pagados</p><p className="font-black text-[#D8BE87]">{stats.pagados}</p></div></div></div></section>

    {organized?<section className={`${panel} p-5 sm:p-6`}><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#70e4df]">Arquitectura competitiva</p><h2 className="mt-1 text-2xl font-black text-white">{selectedFormat?.label||formatLabel(tournament.formato_competencia)}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#8b949e]">{selectedFormat?.description||'Configura divisiones y fases antes de generar competidores, fixture o llaves.'}</p></div><span className="rounded-full border border-white/10 bg-[#0d1117] px-3 py-1 text-xs font-black text-[#D8BE87]">{tournament.estructura_estado==='publicada'?'Publicada':tournament.estructura_estado==='configurada'?'Configurada':'Borrador'}</span></div>{selectedFormat?.blueprint?.length?<div className="mt-5 flex flex-wrap items-center gap-2">{selectedFormat.blueprint.map((step,index)=><div key={`${step}-${index}`} className="flex items-center gap-2"><span className="rounded-xl border border-[#C8A96B]/20 bg-[#C8A96B]/10 px-3 py-2 text-xs font-black text-[#D8BE87]">{index+1}. {step}</span>{index<selectedFormat.blueprint!.length-1?<span className="text-[#596575]">→</span>:null}</div>)}</div>:null}

      <div className="mt-6 grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl border border-white/10 bg-[#0d1117] p-4"><p className="text-xs font-black uppercase tracking-[.14em] text-[#D8BE87]">Agregar división / modalidad</p><div className="mt-3 space-y-3"><input value={divisionForm.nombre} onChange={(event)=>setDivisionForm({...divisionForm,nombre:event.target.value})} className={field} placeholder="Ej. Juvenil, Sub-11, Kumite -60 kg"/><select value={divisionForm.categoria_id} onChange={(event)=>setDivisionForm({...divisionForm,categoria_id:event.target.value})} className={field}><option value="">Sin categoría vinculada</option>{categories.map((category)=><option key={category.id} value={category.id}>{category.nombre}</option>)}</select><input value={divisionForm.modalidad} onChange={(event)=>setDivisionForm({...divisionForm,modalidad:event.target.value})} className={field} placeholder="Modalidad opcional · Ej. Kumite, 50 m libre"/><button disabled={savingStructure} onClick={()=>void addDivision()} className="min-h-11 w-full rounded-xl bg-[#C8A96B] px-4 text-sm font-black text-[#15120c] disabled:opacity-40">Agregar división</button></div></div><div><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#70e4df]">Divisiones configuradas</p><p className="mt-1 text-xs text-[#697586]">Cada división puede tener sus propias fases.</p></div><span className="rounded-full bg-[#289E9D]/10 px-2.5 py-1 text-xs font-black text-[#70e4df]">{structure?.divisiones?.length||0}</span></div><div className="mt-3 space-y-3">{(structure?.divisiones||[]).map((division)=>{const phases=(structure?.fases||[]).filter((phase)=>phase.division_id===division.id);return <article key={division.id} className="rounded-2xl border border-white/10 bg-[#0d1117] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-white">{division.nombre}</h3><p className="mt-1 text-xs text-[#697586]">{division.modalidad||division.categorias?.nombre||'División independiente'} · {phases.length} fase(s)</p></div><button onClick={()=>void removeDivision(division)} className="text-xs font-black text-red-300">Eliminar</button></div><div className="mt-3 flex flex-wrap gap-2">{phases.map((phase)=><button key={phase.id} onClick={()=>void removePhase(phase)} title="Eliminar fase" className="rounded-lg border border-violet-400/20 bg-violet-500/10 px-2.5 py-1.5 text-xs font-bold text-violet-200">{phase.orden}. {phase.nombre} · {phase.tipo} ×</button>)}{!phases.length?<span className="text-xs text-[#596575]">Aún sin fases.</span>:null}</div></article>})}{!structure?.divisiones?.length?<div className="rounded-2xl border border-dashed border-white/10 p-7 text-center text-sm text-[#697586]">Crea la primera división para comenzar la estructura.</div>:null}</div></div></div>

      {structure?.divisiones?.length?<div className="mt-5 rounded-2xl border border-violet-400/20 bg-violet-500/10 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-end"><label className="flex-1"><span className="mb-1 block text-xs font-black text-violet-200">División</span><select value={phaseForm.division_id} onChange={(event)=>setPhaseForm({...phaseForm,division_id:event.target.value})} className={field}><option value="">Selecciona división</option>{structure.divisiones.map((division)=><option key={division.id} value={division.id}>{division.nombre}</option>)}</select></label><label className="flex-1"><span className="mb-1 block text-xs font-black text-violet-200">Nombre de la fase</span><input value={phaseForm.nombre} onChange={(event)=>setPhaseForm({...phaseForm,nombre:event.target.value})} className={field} placeholder="Ej. Grupo A, Cuartos, Clasificatoria"/></label><label className="flex-1"><span className="mb-1 block text-xs font-black text-violet-200">Tipo</span><select value={phaseForm.tipo} onChange={(event)=>setPhaseForm({...phaseForm,tipo:event.target.value})} className={field}><option value="grupo">Grupo / pool</option><option value="liga">Fecha de liga</option><option value="ronda">Ronda</option><option value="llave">Llave</option><option value="clasificacion">Clasificación</option><option value="semifinal">Semifinal</option><option value="final">Final</option><option value="prueba">Prueba / aparato</option><option value="ranking">Ranking</option><option value="repechaje">Repechaje</option><option value="personalizado">Personalizado</option></select></label><button disabled={savingStructure||!phaseForm.division_id} onClick={()=>void addPhase()} className="min-h-11 rounded-xl bg-violet-400 px-4 text-sm font-black text-[#17121e] disabled:opacity-40">Agregar fase</button></div></div>:null}

      <div className="mt-5 rounded-xl border border-amber-400/20 bg-amber-500/10 p-4 text-xs leading-5 text-amber-100/80"><strong className="text-amber-200">Siguiente capa:</strong> una vez definidas divisiones y fases, Lestra podrá incorporar competidores propios/externos y generar fixture, llaves o ranking según este formato. Esta separación evita crear partidos antes de revisar la estructura.</div></section>:<section className={`${panel} p-5`}><p className="text-xs font-black uppercase tracking-[.14em] text-sky-300">Seguimiento externo</p><h2 className="mt-1 text-xl font-black text-white">La estructura oficial pertenece al organizador</h2><p className="mt-2 text-sm leading-6 text-[#8b949e]">Lestra no intenta reemplazar las llaves, grupos o ranking de un tercero. Aquí gestionamos a nuestros alumnos, sus categorías, cobros, citaciones y resultados a medida que avance el campeonato.</p>{tournament.reglamento_url?<a href={tournament.reglamento_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex text-sm font-black text-[#70e4df]">Abrir bases / reglamento ↗</a>:null}</section>}

    {!tournament.rama_id?<div className="rounded-2xl border border-amber-400/20 bg-amber-500/10 p-5 text-sm leading-6 text-amber-200">Este torneo es anterior al modelo multirrama y no tiene rama asociada. No se permiten nuevas convocatorias hasta contextualizarlo. Los datos históricos siguen visibles.</div>:<section className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><div className={`${panel} p-5`}><p className="text-xs font-black uppercase tracking-[.15em] text-[#D8BE87]">1 · Selecciona categoría</p><select value={categoryId} onChange={(event)=>setCategoryId(event.target.value)} className={`${field} mt-3`}><option value="">Categoría de {tournament.ramas?.nombre}</option>{categories.map((category)=><option key={category.id} value={category.id}>{category.nombre}</option>)}</select><p className="mt-3 text-xs leading-5 text-[#697586]">Solo se cargan categorías de la rama <strong className="text-violet-300">{tournament.ramas?.nombre}</strong>. Un alumno debe tener una inscripción activa en esa misma rama para aparecer.</p></div><div className={`${panel} p-5`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[#70e4df]">2 · Plantel elegible</p><h2 className="mt-1 text-xl font-black text-white">{selectedCategory?.nombre||'Selecciona categoría'}</h2></div>{eligible.length?<button onClick={()=>setSelected(selected.length===eligible.length?[]:eligible.map((student)=>student.id))} className="text-xs font-black text-[#70e4df]">{selected.length===eligible.length?'Limpiar':'Seleccionar todos'}</button>:null}</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{eligible.map((student)=>{const checked=selected.includes(student.id);return <button key={student.id} onClick={()=>toggle(student.id)} className={`flex items-center gap-3 rounded-xl border p-3 text-left ${checked?'border-[#289E9D]/50 bg-[#289E9D]/10':'border-white/10 bg-[#0d1117]'}`}><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-500/10 font-black text-violet-300">{student.nombre.slice(0,1)}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-white">{student.nombre}</p><p className="text-[10px] text-[#697586]">{student.inscripcion?.rol_especialidad||'Inscripción activa'}</p></div><span className={`grid h-5 w-5 place-items-center rounded border ${checked?'border-[#289E9D] bg-[#289E9D] text-white':'border-[#596575]'}`}>{checked?'✓':''}</span></button>})}{categoryId&&!eligible.length?<p className="col-span-full py-5 text-center text-sm text-[#697586]">No hay alumnos activos en esta categoría.</p>:null}</div><button disabled={!selected.length||sending} onClick={()=>void send()} className="mt-4 min-h-11 w-full rounded-xl bg-[#289E9D] px-4 text-sm font-black text-white disabled:opacity-40">{sending?'Enviando...':`Convocar ${selected.length||''} alumno${selected.length===1?'':'s'}`}</button></div></section>}

    <section className={`${panel} overflow-hidden`}><div className="border-b border-white/10 p-5"><h2 className="text-xl font-black text-white">Historial de convocatorias</h2><p className="mt-1 text-xs text-[#8b949e]">La categoría y rama quedan guardadas en cada participación. Un mismo alumno puede participar en varias categorías manteniendo una sola inscripción económica al torneo.</p></div><div className="divide-y divide-white/10">{participants.map((participant)=><article key={participant.id} className="grid gap-3 p-4 md:grid-cols-[1.2fr_1fr_.7fr_.7fr]"><div><p className="font-black text-white">{participant.jugadores?.nombre||'Alumno'}</p><p className="text-xs text-[#697586]">{participant.categorias?.nombre||'Histórico sin categoría'}</p></div><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-black ${participant.respuesta_participacion==='Si'?'bg-emerald-500/10 text-emerald-300':participant.respuesta_participacion==='No'?'bg-red-500/10 text-red-300':'bg-amber-500/10 text-amber-300'}`}>{participant.respuesta_participacion}</span><span className="text-sm font-bold text-[#c3ccd6]">{participant.estado_pago||'Pendiente'}</span><span className="text-sm text-[#8995a4]">{participant.numero_cuotas&&participant.numero_cuotas>1?`${participant.numero_cuotas} cuotas`:'Pago único'}</span></article>)}{!participants.length?<div className="p-8 text-center text-sm text-[#697586]">Aún no hay convocatorias.</div>:null}</div></section>
  </div>;
}
