import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import api from '../api/axiosConfig';
import { useAppDialog } from '../contexts/DialogContext';

type Tournament={id:string;nombre:string;fecha_inicio?:string|null;fecha_fin?:string|null;costo_inscripcion:number;permite_cuotas:boolean;max_cuotas:number;rama_id?:string|null;sede_id?:string|null;ramas?:{id:string;nombre:string;disciplina:string}|null;sedes?:{id:string;nombre:string}|null};
type Category={id:string;nombre:string;rama_id?:string|null;sede_id?:string|null;ramas?:{id:string;nombre:string;disciplina:string}|null};
type Student={id:string;nombre:string;foto_url?:string|null;avatar_url?:string|null;foto_base64?:string|null;inscripcion?:{id:string;rama_id:string;categoria_id?:string|null;rol_especialidad?:string|null}|null};
type Participant={id:string;jugador_id:string;categoria_id?:string|null;respuesta_participacion:string;estado_pago:string;numero_cuotas?:number|null;jugadores?:{id:string;nombre:string;foto_url?:string|null;foto_base64?:string|null}|null;categorias?:{id:string;nombre:string}|null};
const panel='rounded-[24px] border border-white/10 bg-[#151b25]';
const field='w-full rounded-xl border border-[#30363d] bg-[#0d1117] px-3 py-2.5 text-sm text-white outline-none focus:border-[#C8A96B]';
const money=(value:number)=>`$${Math.round(Number(value)||0).toLocaleString('es-CL')}`;

export default function GestionarTorneoMultirama(){
  const {id}=useParams();
  const {notify,confirmAction}=useAppDialog();
  const [tournament,setTournament]=useState<Tournament|null>(null);
  const [categories,setCategories]=useState<Category[]>([]);
  const [categoryId,setCategoryId]=useState('');
  const [eligible,setEligible]=useState<Student[]>([]);
  const [participants,setParticipants]=useState<Participant[]>([]);
  const [selected,setSelected]=useState<string[]>([]);
  const [loading,setLoading]=useState(true);
  const [sending,setSending]=useState(false);

  useEffect(()=>{const load=async()=>{if(!id)return;setLoading(true);try{const tournamentResponse=await api.get(`/api/torneos/${id}`);const t=tournamentResponse.data.data as Tournament;setTournament(t);if(t.rama_id){const categoriesResponse=await api.get('/api/jugadores/categorias',{params:{rama_id:t.rama_id}});setCategories(categoriesResponse.data.data||[]);}const participantsResponse=await api.get(`/api/torneos/${id}/participantes`);setParticipants(participantsResponse.data.data||[]);}catch(error:any){await notify(error.response?.data?.error||'No fue posible cargar el torneo.');}finally{setLoading(false);}};void load();},[id,notify]);

  useEffect(()=>{const loadEligible=async()=>{if(!id||!categoryId){setEligible([]);setSelected([]);return;}try{const response=await api.get(`/api/torneos/${id}/elegibles`,{params:{categoria_id:categoryId}});const students=response.data.data||[];setEligible(students);const already=new Set(participants.filter((item)=>item.categoria_id===categoryId).map((item)=>String(item.jugador_id)));setSelected(students.filter((student:Student)=>!already.has(String(student.id))).map((student:Student)=>student.id));}catch(error:any){await notify(error.response?.data?.error||'No fue posible cargar alumnos elegibles.');}};void loadEligible();},[id,categoryId,participants,notify]);

  const selectedCategory=categories.find((category)=>category.id===categoryId)||null;
  const stats=useMemo(()=>({total:participants.length,confirmados:participants.filter((item)=>item.respuesta_participacion==='Si').length,rechazados:participants.filter((item)=>item.respuesta_participacion==='No').length,pagados:participants.filter((item)=>item.estado_pago==='Pagado').length}),[participants]);
  const toggle=(studentId:string)=>setSelected((current)=>current.includes(studentId)?current.filter((item)=>item!==studentId):[...current,studentId]);
  const send=async()=>{
    if(!id||!categoryId||!selected.length)return void notify('Selecciona categoría y al menos un alumno.');
    const accepted=await confirmAction(`Se convocará a ${selected.length} alumno(s) de ${selectedCategory?.nombre||'la categoría'} y se generarán los cobros del torneo en esta rama.`,{confirmLabel:'Enviar convocatoria'});if(!accepted)return;
    setSending(true);try{const response=await api.post(`/api/torneos/${id}/convocar`,{categoria_id:categoryId,jugadoresIds:selected});await notify(response.data.message||'Convocatorias enviadas.');const participantsResponse=await api.get(`/api/torneos/${id}/participantes`);setParticipants(participantsResponse.data.data||[]);setSelected([]);}catch(error:any){await notify(error.response?.data?.error||'No fue posible convocar.');}finally{setSending(false);}
  };

  if(loading)return <div className="grid min-h-[50vh] place-items-center text-[#D8BE87]">Cargando torneo...</div>;
  if(!tournament)return <div className="rounded-xl border border-red-500/20 bg-red-500/10 p-5 text-red-200">Torneo no encontrado.</div>;

  return <div className="mx-auto max-w-7xl space-y-6 pb-16"><div className="flex flex-wrap items-center justify-between gap-3"><Link to="/torneos" className="rounded-xl border border-white/10 px-4 py-2 text-sm font-black text-[#c3ccd6]">← Torneos</Link><Link to="/partidos" className="rounded-xl border border-[#C8A96B]/30 bg-[#C8A96B]/10 px-4 py-2 text-sm font-black text-[#D8BE87]">Ir a encuentros</Link></div>
    <section className="rounded-[28px] border border-[#C8A96B]/25 bg-[radial-gradient(circle_at_top_right,rgba(200,169,107,.16),transparent_36%),#151b25] p-6 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><span className="rounded-full bg-violet-500/10 px-3 py-1 text-[10px] font-black uppercase text-violet-300">{tournament.ramas?.disciplina||'Torneo histórico'}</span><h1 className="mt-3 text-3xl font-black text-white">{tournament.nombre}</h1><p className="mt-2 text-sm text-[#8b949e]">{tournament.ramas?.nombre||'Sin rama'}{tournament.sedes?.nombre?` · ${tournament.sedes.nombre}`:''} · {tournament.fecha_inicio||'Fecha por definir'} · {Number(tournament.costo_inscripcion)>0?money(tournament.costo_inscripcion):'Gratuito'}</p></div><div className="grid grid-cols-4 gap-2 text-center"><div className="rounded-xl bg-[#0d1117] p-3"><p className="text-[9px] uppercase text-[#697586]">Convocados</p><p className="font-black text-white">{stats.total}</p></div><div className="rounded-xl bg-emerald-500/10 p-3"><p className="text-[9px] uppercase text-emerald-300">Sí</p><p className="font-black text-emerald-200">{stats.confirmados}</p></div><div className="rounded-xl bg-red-500/10 p-3"><p className="text-[9px] uppercase text-red-300">No</p><p className="font-black text-red-200">{stats.rechazados}</p></div><div className="rounded-xl bg-[#C8A96B]/10 p-3"><p className="text-[9px] uppercase text-[#D8BE87]">Pagados</p><p className="font-black text-[#D8BE87]">{stats.pagados}</p></div></div></div></section>

    {!tournament.rama_id?<div className="rounded-2xl border border-amber-400/20 bg-amber-500/10 p-5 text-sm leading-6 text-amber-200">Este torneo es anterior al modelo multirrama y no tiene rama asociada. No se permiten nuevas convocatorias hasta contextualizarlo. Los datos históricos siguen visibles.</div>:<section className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><div className={`${panel} p-5`}><p className="text-xs font-black uppercase tracking-[.15em] text-[#D8BE87]">1 · Selecciona categoría</p><select value={categoryId} onChange={(event)=>setCategoryId(event.target.value)} className={`${field} mt-3`}><option value="">Categoría de {tournament.ramas?.nombre}</option>{categories.map((category)=><option key={category.id} value={category.id}>{category.nombre}</option>)}</select><p className="mt-3 text-xs leading-5 text-[#697586]">Solo se cargan categorías de la rama <strong className="text-violet-300">{tournament.ramas?.nombre}</strong>. Un alumno debe tener una inscripción activa en esa misma rama para aparecer.</p></div><div className={`${panel} p-5`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[#70e4df]">2 · Plantel elegible</p><h2 className="mt-1 text-xl font-black text-white">{selectedCategory?.nombre||'Selecciona categoría'}</h2></div>{eligible.length?<button onClick={()=>setSelected(selected.length===eligible.length?[]:eligible.map((student)=>student.id))} className="text-xs font-black text-[#70e4df]">{selected.length===eligible.length?'Limpiar':'Seleccionar todos'}</button>:null}</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{eligible.map((student)=>{const checked=selected.includes(student.id);return <button key={student.id} onClick={()=>toggle(student.id)} className={`flex items-center gap-3 rounded-xl border p-3 text-left ${checked?'border-[#289E9D]/50 bg-[#289E9D]/10':'border-white/10 bg-[#0d1117]'}`}><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-500/10 font-black text-violet-300">{student.nombre.slice(0,1)}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-white">{student.nombre}</p><p className="text-[10px] text-[#697586]">{student.inscripcion?.rol_especialidad||'Inscripción activa'}</p></div><span className={`grid h-5 w-5 place-items-center rounded border ${checked?'border-[#289E9D] bg-[#289E9D] text-white':'border-[#596575]'}`}>{checked?'✓':''}</span></button>})}{categoryId&&!eligible.length?<p className="col-span-full py-5 text-center text-sm text-[#697586]">No hay alumnos activos en esta categoría.</p>:null}</div><button disabled={!selected.length||sending} onClick={()=>void send()} className="mt-4 min-h-11 w-full rounded-xl bg-[#289E9D] px-4 text-sm font-black text-white disabled:opacity-40">{sending?'Enviando...':`Convocar ${selected.length||''} alumno${selected.length===1?'':'s'}`}</button></div></section>}

    <section className={`${panel} overflow-hidden`}><div className="border-b border-white/10 p-5"><h2 className="text-xl font-black text-white">Historial de convocatorias</h2><p className="mt-1 text-xs text-[#8b949e]">La categoría y rama quedan guardadas en cada participación.</p></div><div className="divide-y divide-white/10">{participants.map((participant)=><article key={participant.id} className="grid gap-3 p-4 md:grid-cols-[1.2fr_1fr_.7fr_.7fr]"><div><p className="font-black text-white">{participant.jugadores?.nombre||'Alumno'}</p><p className="text-xs text-[#697586]">{participant.categorias?.nombre||'Histórico sin categoría'}</p></div><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-black ${participant.respuesta_participacion==='Si'?'bg-emerald-500/10 text-emerald-300':participant.respuesta_participacion==='No'?'bg-red-500/10 text-red-300':'bg-amber-500/10 text-amber-300'}`}>{participant.respuesta_participacion}</span><span className="text-sm font-bold text-[#c3ccd6]">{participant.estado_pago||'Pendiente'}</span><span className="text-sm text-[#8995a4]">{participant.numero_cuotas&&participant.numero_cuotas>1?`${participant.numero_cuotas} cuotas`:'Pago único'}</span></article>)}{!participants.length?<div className="p-8 text-center text-sm text-[#697586]">Aún no hay convocatorias.</div>:null}</div></section>
  </div>;
}
