import React, { useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import api from '../api/axiosConfig';
import {
  DIRECTOR_BUTTON,
  DIRECTOR_BUTTON_DARK,
  DIRECTOR_BUTTON_GHOST,
  DIRECTOR_FIELD,
  DirectorHero,
  DirectorPage,
  DirectorPanel,
  DirectorStat,
} from '../components/director/DirectorModule';

type CanonicalKey = 'nombre_alumno'|'rut_alumno'|'fecha_nacimiento'|'sexo'|'posicion'|'categoria'|'nombre_apoderado'|'rut_apoderado'|'telefono_apoderado'|'email_apoderado'|'monto_matricula'|'mensualidad'|'saldo_pendiente'|'talla_uniforme'|'numero_camiseta'|'estado';
type Branch = { id:string; sede_id:string; nombre:string; disciplina:string; principal?:boolean; sedes?:{id:string;nombre:string;principal?:boolean;activa?:boolean}|null };
type PreviewRow = Record<string,any> & { fila:number; valido:boolean; errors:string[]; warnings:string[]; modo?:'crear_alumno'|'inscribir_existente'; jugador_existente_id?:string|null; jugador_existente_nombre?:string|null };

const fields:Array<{key:CanonicalKey;label:string;required?:boolean;aliases:string[]}>= [
 {key:'nombre_alumno',label:'Nombre del alumno',required:true,aliases:['nombre alumno','alumno','jugador','nombre jugador','nombre deportista','nombre niño','nombre nino']},
 {key:'rut_alumno',label:'RUT / documento alumno',aliases:['rut alumno','rut jugador','rut niño','rut nino','documento alumno','dni alumno']},
 {key:'fecha_nacimiento',label:'Fecha de nacimiento',aliases:['fecha nacimiento','f nacimiento','nacimiento','fecha nac','fnacimiento']},
 {key:'sexo',label:'Sexo',aliases:['sexo','genero','género']},
 {key:'posicion',label:'Posición / especialidad',aliases:['posicion','posición','puesto','rol cancha','especialidad','rol','grado']},
 {key:'categoria',label:'Categoría',aliases:['categoria','categoría','serie','division','división','grupo','nivel']},
 {key:'nombre_apoderado',label:'Nombre apoderado',aliases:['apoderado','nombre apoderado','tutor','nombre tutor','padre','madre']},
 {key:'rut_apoderado',label:'RUT apoderado',aliases:['rut apoderado','rut tutor','documento apoderado','dni apoderado']},
 {key:'telefono_apoderado',label:'Teléfono apoderado',aliases:['telefono','teléfono','celular','fono','telefono apoderado','celular apoderado']},
 {key:'email_apoderado',label:'Correo apoderado',aliases:['email','correo','mail','correo apoderado','email apoderado']},
 {key:'monto_matricula',label:'Valor matrícula',aliases:['matricula','matrícula','valor matricula','valor matrícula']},
 {key:'mensualidad',label:'Mensualidad',aliases:['mensualidad','valor mensualidad','cuota mensual']},
 {key:'saldo_pendiente',label:'Saldo pendiente actual',aliases:['saldo','saldo pendiente','deuda','deuda actual']},
 {key:'talla_uniforme',label:'Talla uniforme',aliases:['talla','talla uniforme','talla polera']},
 {key:'numero_camiseta',label:'Número / dorsal',aliases:['numero camiseta','número camiseta','dorsal','numero','nro camiseta','número','numero dorsal']},
 {key:'estado',label:'Estado alumno',aliases:['estado','estado alumno','activo']},
];
const normalizeHeader=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const suggestMapping=(headers:string[])=>{const result:Partial<Record<CanonicalKey,string>>={};const normalized=headers.map(h=>({raw:h,norm:normalizeHeader(h)}));fields.forEach(field=>{const aliasSet=[field.label,...field.aliases].map(normalizeHeader);const exact=normalized.find(h=>aliasSet.includes(h.norm));if(exact)result[field.key]=exact.raw;else{const loose=normalized.find(h=>aliasSet.some(a=>h.norm.includes(a)||a.includes(h.norm)));if(loose)result[field.key]=loose.raw;}});return result;};
const branchLabel=(branch?:Branch|null)=>{if(!branch)return '';const site=branch.sedes?.nombre?` · ${branch.sedes.nombre}`:'';const discipline=branch.disciplina&&branch.disciplina!==branch.nombre?` · ${branch.disciplina}`:'';return `${branch.nombre}${discipline}${site}`;};
const labelClass='mb-1.5 block text-[11px] font-black uppercase tracking-[.09em] text-[#697468]';

const Importacion:React.FC=()=>{
 const [fileName,setFileName]=useState('');const [headers,setHeaders]=useState<string[]>([]);const [rawRows,setRawRows]=useState<Record<string,any>[]>([]);const [mapping,setMapping]=useState<Partial<Record<CanonicalKey,string>>>({});const [preview,setPreview]=useState<PreviewRow[]>([]);const [summary,setSummary]=useState<any>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [history,setHistory]=useState<any[]>([]);const [result,setResult]=useState<any>(null);const [branches,setBranches]=useState<Branch[]>([]);const [selectedBranchId,setSelectedBranchId]=useState('');const [contextLoading,setContextLoading]=useState(true);
 const selectedBranch=useMemo(()=>branches.find(branch=>branch.id===selectedBranchId)||null,[branches,selectedBranchId]);

 const downloadTemplate=()=>{const humanLabels=fields.map(field=>field.label);const example=['Ejemplo Alumno','12.345.678-5',new Date(2014,4,20),'Masculino','Delantero / Cinturón amarillo','Sub-12 / Infantil','Ejemplo Apoderado','9.876.543-2','+56 9 1234 5678','apoderado@ejemplo.cl',50000,35000,0,'Talla 12',10,'Activo'];const book=XLSX.utils.book_new();const matrix=XLSX.utils.aoa_to_sheet([humanLabels,example]);matrix['!cols']=[24,18,18,16,26,22,26,18,20,28,16,16,20,16,16,16].map(wch=>({wch}));XLSX.utils.book_append_sheet(book,matrix,'Alumnos');const instructions=XLSX.utils.aoa_to_sheet([['LESTRA · Guía de importación multirrama'],['Regla','Qué hacer'],['Rama deportiva','Antes de subir el archivo, selecciona en Lestra una sola rama destino. Cada lote pertenece a una rama y sede.'],['Nombre del alumno','Obligatorio. Un alumno por fila.'],['RUT alumno','Recomendado. Si el alumno ya existe en la academia, Lestra reutiliza su ficha y agrega la nueva rama sin duplicarlo.'],['Fecha nacimiento','Usa una fecha real de Excel o formato AAAA-MM-DD.'],['Posición / especialidad','Es el rol dentro de la rama seleccionada.'],['Apoderado','Para alumnos nuevos, idealmente completa nombre, RUT, teléfono y correo.'],['Montos','Usa números. Los valores quedan asociados a la inscripción deportiva de la rama.'],['Saldo pendiente','Solo deuda real ya existente al migrar.'],['Categoría','Si no existe, Lestra la crea en esa misma sede y rama.'],['Estado','Usa Activo, Inactivo o Retirado.'],['Flujo','Selecciona rama → sube → valida → corrige → importa. Máximo 3.000 filas por lote.']]);instructions['!cols']=[{wch:26},{wch:100}];XLSX.utils.book_append_sheet(book,instructions,'Instrucciones');XLSX.writeFile(book,'Matriz_Importacion_Multirrama_Lestra.xlsx');};
 const loadHistory=()=>api.get('/api/importaciones/lotes').then(response=>setHistory(response.data?.data||[])).catch(()=>setHistory([]));
 const loadContext=async()=>{setContextLoading(true);try{const response=await api.get('/api/importaciones/contexto');const data=response.data?.data||{};const nextBranches:Branch[]=data.ramas||[];setBranches(nextBranches);setSelectedBranchId(current=>{if(current&&nextBranches.some(branch=>branch.id===current))return current;const preferred=data.rama_principal_id&&nextBranches.find(branch=>branch.id===data.rama_principal_id);return preferred?.id||nextBranches[0]?.id||'';});}catch(err:any){setError(err?.response?.data?.error||'No fue posible cargar las ramas de la academia.');setBranches([]);}finally{setContextLoading(false);}};
 useEffect(()=>{void loadContext();void loadHistory();},[]);
 const resetValidation=()=>{setPreview([]);setSummary(null);setResult(null);setError('');};
 const onBranchChange=(branchId:string)=>{setSelectedBranchId(branchId);resetValidation();};
 const onFile=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setError('');setPreview([]);setSummary(null);setResult(null);setFileName(file.name);try{const buffer=await file.arrayBuffer();const workbook=XLSX.read(buffer,{type:'array',cellDates:true});const sheet=workbook.Sheets[workbook.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Record<string,any>>(sheet,{defval:''});if(!rows.length)throw new Error('El archivo no contiene filas de datos.');if(rows.length>3000)throw new Error(`El archivo contiene ${rows.length.toLocaleString('es-CL')} filas. El máximo permitido por lote es 3.000.`);const hs=Object.keys(rows[0]);setHeaders(hs);setRawRows(rows);setMapping(suggestMapping(hs));}catch(err:any){setHeaders([]);setRawRows([]);setMapping({});setError(err?.message||'No fue posible leer el archivo.');}};
 const mappedRows=useMemo(()=>rawRows.map(row=>{const out:Record<string,any>={};fields.forEach(field=>{const source=mapping[field.key];out[field.key]=source?row[source]:'';});return out;}),[rawRows,mapping]);
 const runPreview=async()=>{if(!selectedBranchId)return setError('Selecciona primero la rama deportiva de destino.');if(!mapping.nombre_alumno)return setError('Debes asignar la columna que contiene el nombre del alumno.');setLoading(true);setError('');setResult(null);try{const response=await api.post('/api/importaciones/preview',{rama_id:selectedBranchId,rows:mappedRows});setPreview(response.data?.data||[]);setSummary(response.data?.summary||null);}catch(err:any){setError(err?.response?.data?.error||'No fue posible validar la importación.');}finally{setLoading(false);}};
 const commit=async()=>{if(!preview.length||!selectedBranchId)return;setLoading(true);setError('');try{const response=await api.post('/api/importaciones/commit',{rama_id:selectedBranchId,file_name:fileName,rows:mappedRows});setResult(response.data);await loadHistory();}catch(err:any){setError(err?.response?.data?.error||'No fue posible importar los registros.');}finally{setLoading(false);}};
 const revert=async(id:string)=>{if(!window.confirm('Se eliminarán las inscripciones, cobros y vínculos creados por este lote. Los alumnos que ya existían antes de importar conservarán su ficha personal. ¿Continuar?'))return;setLoading(true);setError('');try{await api.post(`/api/importaciones/lotes/${id}/revertir`);await loadHistory();}catch(err:any){setError(err?.response?.data?.error||'No fue posible revertir la importación.');}finally{setLoading(false);}};
 const validCount=preview.filter(row=>row.valido).length;const invalidCount=preview.length-validCount;

 return <DirectorPage>
  <DirectorHero eyebrow="Migración multirrama" title="Importar alumnos" description="Cada lote pertenece a una rama concreta. Si el RUT ya existe, Lestra reutiliza la ficha personal y crea solo la nueva inscripción deportiva." actions={<button type="button" onClick={downloadTemplate} className={DIRECTOR_BUTTON_GHOST}>Descargar matriz Excel</button>} aside={<div className="rounded-[20px] border border-white/15 bg-white/[.055] p-5"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#b7ff00]">Límite por lote</p><p className="mt-2 text-xl font-black text-white">3.000 filas</p><p className="mt-1 text-xs font-semibold text-[#c7d0c8]">Validación previa antes de escribir datos.</p></div>}/>
  {error?<div className="rounded-[18px] border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>:null}
  {result?<div className="rounded-[18px] border border-[#cde995] bg-[#f3fadf] p-5 text-[#435b00]"><p className="font-black">Importación terminada · {result.scope?.rama_nombre||selectedBranch?.nombre}</p><p className="mt-2 text-sm">Procesados: <b>{result.summary?.imported||0}</b> · Alumnos nuevos: <b>{result.summary?.created_players||0}</b> · Existentes inscritos: <b>{result.summary?.enrolled_existing||0}</b> · Omitidos: <b>{result.summary?.skipped||0}</b> · Con error: <b>{result.summary?.failed||0}</b></p></div>:null}
  <section className="grid gap-3 sm:grid-cols-3"><DirectorStat label="Filas cargadas" value={rawRows.length}/><DirectorStat label="Válidas" value={validCount} tone="lime"/><DirectorStat label="Con observaciones" value={invalidCount} tone={invalidCount?'dark':'default'}/></section>

  <DirectorPanel className="p-5 sm:p-6"><div><p className="text-[11px] font-black uppercase tracking-[.14em] text-[#789600]">Paso 1</p><h2 className="mt-1 text-2xl font-black tracking-[-.03em] text-[#111711]">Destino del lote</h2><p className="mt-1 text-sm text-[#697468]">Selecciona una sola rama antes de subir el archivo.</p></div><div className="mt-5 grid gap-3 md:grid-cols-[1.25fr_.75fr]"><label><span className={labelClass}>Rama deportiva</span><select disabled={contextLoading} value={selectedBranchId} onChange={e=>onBranchChange(e.target.value)} className={DIRECTOR_FIELD}><option value="">Selecciona rama</option>{branches.map(branch=><option key={branch.id} value={branch.id}>{branchLabel(branch)}</option>)}</select></label><label><span className={labelClass}>Archivo Excel / CSV</span><input type="file" accept=".xlsx,.xls,.csv" onChange={onFile} className="block min-h-12 w-full rounded-[14px] border border-[#d6ddd2] bg-[#f3f6f0] px-3 py-2 text-sm font-bold text-[#111711] file:mr-3 file:rounded-lg file:border-0 file:bg-[#111711] file:px-3 file:py-2 file:text-xs file:font-black file:text-white"/></label></div>{fileName?<p className="mt-3 text-xs font-semibold text-[#697468]">Archivo: <strong className="text-[#111711]">{fileName}</strong> · {rawRows.length.toLocaleString('es-CL')} filas</p>:null}</DirectorPanel>

  {headers.length?<DirectorPanel className="p-5 sm:p-6"><div><p className="text-[11px] font-black uppercase tracking-[.14em] text-[#789600]">Paso 2</p><h2 className="mt-1 text-2xl font-black tracking-[-.03em] text-[#111711]">Relaciona las columnas</h2><p className="mt-1 text-sm text-[#697468]">Lestra propone coincidencias. Revisa especialmente nombre, RUT y categoría.</p></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{fields.map(field=><label key={field.key}><span className={labelClass}>{field.label}{field.required?' *':''}</span><select value={mapping[field.key]||''} onChange={e=>setMapping({...mapping,[field.key]:e.target.value||undefined})} className={DIRECTOR_FIELD}><option value="">No importar</option>{headers.map(header=><option key={header} value={header}>{header}</option>)}</select></label>)}</div><div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" onClick={resetValidation} className={DIRECTOR_BUTTON_DARK}>Limpiar validación</button><button type="button" disabled={loading||!rawRows.length} onClick={()=>void runPreview()} className={DIRECTOR_BUTTON}>{loading?'Validando...':'Validar lote'}</button></div></DirectorPanel>:null}

  {preview.length?<DirectorPanel className="overflow-hidden"><div className="flex flex-col gap-4 border-b border-[#e2e7df] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><p className="text-[11px] font-black uppercase tracking-[.14em] text-[#789600]">Paso 3</p><h2 className="mt-1 text-2xl font-black tracking-[-.03em] text-[#111711]">Revisión previa</h2><p className="mt-1 text-sm text-[#697468]">{summary?.validos??validCount} válidos · {summary?.invalidos??invalidCount} con errores</p></div><button type="button" disabled={loading||invalidCount>0} onClick={()=>void commit()} className={DIRECTOR_BUTTON}>{loading?'Procesando...':'Importar registros válidos'}</button></div><div className="max-h-[620px] overflow-auto"><table className="min-w-full text-left text-xs"><thead className="sticky top-0 bg-[#f5f7f3] text-[10px] uppercase tracking-[.08em] text-[#697468]"><tr><th className="px-4 py-3">Fila</th><th className="px-4 py-3">Alumno</th><th className="px-4 py-3">RUT</th><th className="px-4 py-3">Categoría</th><th className="px-4 py-3">Modo</th><th className="px-4 py-3">Estado</th></tr></thead><tbody className="divide-y divide-[#e7ebe4]">{preview.map(row=><tr key={row.fila} className="bg-white"><td className="px-4 py-3 font-black text-[#111711]">{row.fila}</td><td className="px-4 py-3 font-bold text-[#111711]">{row.nombre_alumno||'—'}</td><td className="px-4 py-3 text-[#697468]">{row.rut_alumno||'—'}</td><td className="px-4 py-3 text-[#697468]">{row.categoria||'—'}</td><td className="px-4 py-3"><span className="rounded-full border border-[#d9e0d6] bg-[#f5f7f3] px-2 py-1 font-bold text-[#596458]">{row.modo==='inscribir_existente'?'Ficha existente':'Alumno nuevo'}</span></td><td className="max-w-[360px] px-4 py-3">{row.valido?<span className="font-black text-[#5f7900]">Lista</span>:<div><p className="font-black text-red-700">Revisar</p>{row.errors?.map((err:string)=><p key={err} className="mt-1 text-[10px] leading-4 text-red-600">{err}</p>)}</div>}{row.warnings?.map((warning:string)=><p key={warning} className="mt-1 text-[10px] leading-4 text-amber-700">{warning}</p>)}</td></tr>)}</tbody></table></div></DirectorPanel>:null}

  <DirectorPanel className="overflow-hidden"><div className="border-b border-[#e2e7df] p-5 sm:p-6"><p className="text-[11px] font-black uppercase tracking-[.14em] text-[#789600]">Trazabilidad</p><h2 className="mt-1 text-2xl font-black tracking-[-.03em] text-[#111711]">Importaciones anteriores</h2></div><div className="divide-y divide-[#e7ebe4]">{history.length?history.map(item=><article key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black text-[#111711]">{item.file_name||item.nombre_archivo||'Lote de importación'}</p><p className="mt-1 text-xs text-[#697468]">{item.rama_nombre||item.ramas?.nombre||'Rama'} · {item.created_at?new Date(item.created_at).toLocaleString('es-CL'):'Fecha no disponible'}</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-[#d9e0d6] bg-[#f5f7f3] px-3 py-1 text-xs font-black text-[#596458]">{item.estado||'Procesado'}</span>{!item.reverted_at&&item.estado!=='Revertido'?<button type="button" disabled={loading} onClick={()=>void revert(item.id)} className={DIRECTOR_BUTTON_DARK}>Revertir</button>:null}</div></article>):<p className="p-8 text-center text-sm text-[#697468]">Todavía no hay importaciones registradas.</p>}</div></DirectorPanel>
 </DirectorPage>;
};

export default Importacion;
