import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import api from '../api/axiosConfig';
import { Logo } from '../components/Logo';

type Order={id:string;scope:'academia'|'plataforma';amount_expected:number;amount_approved?:number|null;status:string;approved_at?:string|null;created_at:string};
const money=(value:number)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(value)||0);
export default function PaymentResult(){
 const [params]=useSearchParams();const orderId=params.get('order')||'';const providerStatus=params.get('status')||'';const [order,setOrder]=useState<Order|null>(null);const [error,setError]=useState('');
 useEffect(()=>{if(!orderId){setError('No se encontró la orden de pago.');return;}let stopped=false;let timer:number|undefined;const poll=async()=>{try{const r=await api.get(`/api/mercadopago/order/${encodeURIComponent(orderId)}`);if(stopped)return;setOrder(r.data.data);if(!['approved','rejected','cancelled','refunded'].includes(String(r.data.data.status)))timer=window.setTimeout(poll,2500);}catch(err:any){if(!stopped)setError(err.response?.data?.error||'No fue posible consultar el estado del pago.');}};void poll();return()=>{stopped=true;if(timer)window.clearTimeout(timer);};},[orderId]);
 const state=useMemo(()=>{if(order?.status==='approved')return{icon:'✓',title:'Pago confirmado',text:'Mercado Pago confirmó la operación y Lestra actualizó el estado de cuenta automáticamente.',tone:'emerald'};if(['rejected','cancelled'].includes(order?.status||'')||providerStatus==='failure')return{icon:'×',title:'Pago no completado',text:'No se registró ningún pago en Lestra. Puedes volver a intentarlo desde tu estado de cuenta.',tone:'red'};if(order?.status==='refunded')return{icon:'↩',title:'Pago reembolsado',text:'Mercado Pago informó un reembolso. El movimiento quedó registrado para revisión.',tone:'amber'};return{icon:'…',title:'Confirmando pago',text:'Mercado Pago todavía está procesando la operación. Esta pantalla se actualizará automáticamente.',tone:'sky'};},[order?.status,providerStatus]);
 const cls=state.tone==='emerald'?'border-emerald-400/25 bg-emerald-500/10 text-emerald-200':state.tone==='red'?'border-red-400/25 bg-red-500/10 text-red-200':state.tone==='amber'?'border-amber-400/25 bg-amber-500/10 text-amber-200':'border-sky-400/25 bg-sky-500/10 text-sky-200';
 return <div className="grid min-h-screen place-items-center bg-[#0d1117] p-5 text-white"><div className="w-full max-w-xl"><Logo variant="mark" className="mx-auto h-14 w-14"/><div className={`mt-6 rounded-3xl border p-7 text-center ${cls}`}><div className="mx-auto grid h-16 w-16 place-items-center rounded-full border border-current text-3xl font-black">{state.icon}</div><h1 className="mt-4 text-3xl font-black">{state.title}</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 opacity-80">{state.text}</p>{order?<div className="mt-6 rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-xs uppercase tracking-wider opacity-70">Monto de la orden</p><p className="mt-1 text-3xl font-black">{money(order.amount_expected)}</p>{order.status==='approved'?<p className="mt-2 text-xs">Confirmado {order.approved_at?new Date(order.approved_at).toLocaleString('es-CL'):''}</p>:null}</div>:null}{error?<p className="mt-4 text-sm text-red-200">{error}</p>:null}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link to="/" className="rounded-xl border border-white/10 px-4 py-3 text-center font-black text-[#b6c0cc]">Ir a Lestra</Link><button onClick={()=>window.history.back()} className="rounded-xl bg-[#289E9D] px-4 py-3 font-black text-white">Volver</button></div></div></div>;
}
