import { useEffect, useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowPathIcon, CheckCircleIcon, DocumentCheckIcon, HeartIcon, ShieldCheckIcon, UserIcon } from '@heroicons/react/24/outline';
import api from '../api/axiosConfig';
import { useAppDialog } from '../contexts/DialogContext';
import { DIRECTOR_BUTTON, DIRECTOR_BUTTON_GHOST, DIRECTOR_FIELD, DIRECTOR_TEXTAREA, DirectorHero, DirectorPage, DirectorPanel } from '../components/director/DirectorModule';

type Availability='Sin evaluar'|'Disponible'|'Disponible con restricción'|'En recuperación'|'No disponible';
type SummaryItem={id:string;nombre:string;foto?:string|null;estado_disponibilidad:Availability;restriccion?:string|null;lesiones_activas:number;retorno_estimado?:string|null;certificados_vencidos:number;certificados_por_vencer:number};
type SummaryPayload={items:SummaryItem[];resumen:{total:number;por_estado:Record<string,number>;lesiones_activas:number;certificados_vencidos:number}};
type Injury={id:string;tipo:string;zona?:string|null;descripcion?:string|null;estado:string;fecha_inicio:string;fecha_retorno_estimada?:string|null;fecha_cierre?:string|null;restriccion?:string|null;observaciones?:string|null;ramas?:{nombre?:string;disciplina?:string}|null};
type Certificate={id:string;tipo:string;fecha_emision?:string|null;fecha_vencimiento?:string|null;archivo_url?:string|null;observaciones?:string|null;estado_calculado:string};
type Enrollment={id:string;estado:string;rama_id?:string|null;ramas?:{nombre?:string;disciplina?:string;activa?:boolean}|null;categorias?:{nombre?:string}|null};
type PlayerDetail={jugador:{id:string;nombre:string;foto?:string|null;fecha_nacimiento?:string|null};salud:{estado_disponibilidad:Availability;restriccion?:string|null;grupo_sanguineo?:string|null;alergias?:string|null;medicamentos?:string|null;enfermedades_cronicas?:string|null;observaciones?:string|null;contacto_emergencia_nombre?:string|null;contacto_emergencia_telefono?:string|null;contacto_emergencia_parentesco?:string|null};lesiones:Injury[];certificados:Certificate[];inscripciones:Enrollment[];perfil_360:{asistencia:{porcentaje:number|null;registros:number;presentes:number};evaluacion:{promedio_actual:number|null;variacion:number|null;evaluaciones:number};competencia:{eventos:number;participaciones:number;titularidades:number;minutos:number;destacados:number};marcas:{pb_vigentes:number;sb_vigentes:number;recientes:any[]};salud:{estado:Availability;lesiones_activas:number;dias_fuera_temporada:number;certificados_vencidos:number;certificados_por_vencer:number}}};
type ProfileDraft={estado_disponibilidad:Availability;motivo_disponibilidad:string;restriccion:string;grupo_sanguineo:string;alergias:string;medicamentos:string;enfermedades_cronicas:string;observaciones:string;contacto_emergencia_nombre:string;contacto_emergencia_telefono:string;contacto_emergencia_parentesco:string};

const emptyProfile:ProfileDraft={estado_disponibilidad:'Sin evaluar',motivo_disponibilidad:'',restriccion:'',grupo_sanguineo:'',alergias:'',medicamentos:'',enfermedades_cronicas:'',observaciones:'',contacto_emergencia_nombre:'',contacto_emergencia_telefono:'',contacto_emergencia_parentesco:''};
const availabilityOptions:Availability[]=['Sin evaluar','Disponible','Disponible con restricción','En recuperación','No disponible'];
const injuryStates=['Activa','Recuperación','Entrenamiento parcial','Entrenamiento completo','Cerrada'];
const date=(value?:string|null)=>value?new Date(`${String(value).slice(0,10)}T12:00:00`).toLocaleDateString('es-CL'):'—';
const metric=(value:number|null|undefined,suffix='')=>value===null||value===undefined?'Sin datos':`${value}${suffix}`;
const labelClass='mb-1.5 block text-[11px] font-black uppercase tracking-[.09em] text-[#697468]';
const availabilityClass=(value:Availability)=>value==='Disponible'?'border-[#cde995] bg-[#f3fadf] text-[#4f6900]':value==='No disponible'?'border-red-200 bg-red-50 text-red-700':value==='En recuperación'||value==='Disponible con restricción'?'border-amber-200 bg-amber-50 text-amber-700':'border-[#d9e0d6] bg-[#f5f7f3] text-[#697468]';

export default function SaludDisponibilidad(){
 const {notify}=useAppDialog();
 const [selectedId,setSelectedId]=useState('');
 const [search,setSearch]=useState('');
 const [profile,setProfile]=useState<ProfileDraft>(emptyProfile);
 const [saving,setSaving]=useState(false);
 const [injury,setInjury]=useState({tipo:'',zona:'',rama_id:'',fecha_inicio:new Date().toISOString().slice(0,10),fecha_retorno_estimada:'',descripcion:'',restriccion:'',observaciones:''});
 const [certificate,setCertificate]=useState({tipo:'Certificado médico',fecha_emision:'',fecha_vencimiento:'',archivo_url:'',observaciones:''});
 const [creatingInjury,setCreatingInjury]=useState(false);
 const [creatingCertificate,setCreatingCertificate]=useState(false);

 const summaryQuery=useQuery({queryKey:['salud-resumen'],queryFn:async()=>((await api.get('/api/ficha-medica/resumen')).data.data as SummaryPayload),staleTime:30_000});
 const detailQuery=useQuery({queryKey:['salud-jugador',selectedId],enabled:Boolean(selectedId),queryFn:async()=>((await api.get(`/api/ficha-medica/jugador/${selectedId}`)).data.data as PlayerDetail)});
 const items=summaryQuery.data?.items||[];
 const filtered=useMemo(()=>items.filter(item=>item.nombre.toLowerCase().includes(search.toLowerCase().trim())),[items,search]);
 useEffect(()=>{if(!selectedId&&items.length)setSelectedId(items[0].id);},[items,selectedId]);
 useEffect(()=>{const h=detailQuery.data?.salud;if(!h)return;setProfile({estado_disponibilidad:h.estado_disponibilidad||'Sin evaluar',motivo_disponibilidad:'',restriccion:h.restriccion||'',grupo_sanguineo:h.grupo_sanguineo||'',alergias:h.alergias||'',medicamentos:h.medicamentos||'',enfermedades_cronicas:h.enfermedades_cronicas||'',observaciones:h.observaciones||'',contacto_emergencia_nombre:h.contacto_emergencia_nombre||'',contacto_emergencia_telefono:h.contacto_emergencia_telefono||'',contacto_emergencia_parentesco:h.contacto_emergencia_parentesco||''});},[detailQuery.data?.jugador.id]);
 const refresh=async()=>{await Promise.all([summaryQuery.refetch(),detailQuery.refetch()]);};
 const saveProfile=async()=>{if(!selectedId)return;setSaving(true);try{await api.put(`/api/ficha-medica/jugador/${selectedId}`,profile);await refresh();await notify('Salud y disponibilidad actualizadas.',{title:detailQuery.data?.jugador.nombre||'Deportista'});}catch(error:any){await notify(error?.response?.data?.error||'No fue posible guardar los cambios.',{title:'Salud y disponibilidad'});}finally{setSaving(false);}};
 const addInjury=async()=>{if(!selectedId||!injury.tipo.trim())return;setCreatingInjury(true);try{await api.post(`/api/ficha-medica/jugador/${selectedId}/lesiones`,injury);setInjury({tipo:'',zona:'',rama_id:'',fecha_inicio:new Date().toISOString().slice(0,10),fecha_retorno_estimada:'',descripcion:'',restriccion:'',observaciones:''});await refresh();}catch(error:any){await notify(error?.response?.data?.error||'No fue posible registrar el seguimiento.',{title:'Salud deportiva'});}finally{setCreatingInjury(false);}};
 const updateInjury=async(id:string,estado:string)=>{try{await api.patch(`/api/ficha-medica/lesiones/${id}`,{estado});await refresh();}catch(error:any){await notify(error?.response?.data?.error||'No fue posible actualizar el seguimiento.',{title:'Salud deportiva'});}};
 const addCertificate=async()=>{if(!selectedId)return;setCreatingCertificate(true);try{await api.post(`/api/ficha-medica/jugador/${selectedId}/certificados`,certificate);setCertificate({tipo:'Certificado médico',fecha_emision:'',fecha_vencimiento:'',archivo_url:'',observaciones:''});await refresh();}catch(error:any){await notify(error?.response?.data?.error||'No fue posible registrar el certificado.',{title:'Certificados'});}finally{setCreatingCertificate(false);}};

 if(summaryQuery.isLoading)return <DirectorPanel className="mx-auto max-w-6xl p-12 text-center text-sm font-bold text-[#697468]">Preparando salud y disponibilidad...</DirectorPanel>;
 if(summaryQuery.error)return <div className="rounded-[18px] border border-red-200 bg-red-50 p-6 text-red-700">No fue posible cargar este módulo.</div>;
 const detail=detailQuery.data;
 const total=summaryQuery.data?.resumen.total||0;

 return <DirectorPage className="max-w-[1500px]">
  <DirectorHero eyebrow="Alto Rendimiento" title="Salud y disponibilidad deportiva" description="Información operativa para saber quién está disponible, quién necesita restricciones y cómo se conecta salud, asistencia, evaluación y rendimiento. No reemplaza una evaluación ni indicación de profesionales de salud." aside={<div className="grid grid-cols-3 gap-2"><HeroMetric label="Deportistas" value={total}/><HeroMetric label="Disponibles" value={summaryQuery.data?.resumen.por_estado?.Disponible||0}/><HeroMetric label="Seguimientos" value={summaryQuery.data?.resumen.lesiones_activas||0}/></div>}/>

  <section className="grid gap-5 xl:grid-cols-[330px_1fr]">
   <DirectorPanel className="self-start p-4 xl:sticky xl:top-4">
    <div className="flex items-center justify-between"><div><p className="text-[11px] font-black uppercase tracking-[.14em] text-[#789600]">Plantel</p><h2 className="mt-1 text-xl font-black text-[#111711]">Deportistas</h2></div><button onClick={()=>void summaryQuery.refetch()} className={`${DIRECTOR_BUTTON_GHOST} min-h-10 px-3`}><ArrowPathIcon className="h-5 w-5"/></button></div>
    <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar deportista..." className={`${DIRECTOR_FIELD} mt-4`}/>
    <div className="mt-3 max-h-[680px] space-y-2 overflow-y-auto pr-1">{filtered.map(item=><button key={item.id} onClick={()=>setSelectedId(item.id)} className={`w-full rounded-[16px] border p-3 text-left transition ${selectedId===item.id?'border-[#9fcf00] bg-[#f3fadf]':'border-[#dfe5dc] bg-[#f8faf6] hover:border-[#aebaa9]'}`}><div className="flex items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-xl bg-[#111711]">{item.foto?<img src={item.foto} alt="" className="h-full w-full object-cover"/>:<UserIcon className="h-5 w-5 text-white"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-[#111711]">{item.nombre}</p><span className={`mt-1 inline-flex rounded-full border px-2 py-0.5 text-[9px] font-black uppercase ${availabilityClass(item.estado_disponibilidad)}`}>{item.estado_disponibilidad}</span></div>{item.lesiones_activas?<span className="rounded-full border border-amber-200 bg-amber-50 px-2 py-1 text-[10px] font-black text-amber-700">{item.lesiones_activas}</span>:null}</div></button>)}</div>
   </DirectorPanel>

   <div className="min-w-0 space-y-5">{detailQuery.isLoading?<DirectorPanel className="grid min-h-[45vh] place-items-center text-sm font-bold text-[#697468]">Construyendo Perfil 360°...</DirectorPanel>:!detail?<DirectorPanel className="grid min-h-[45vh] place-items-center text-sm text-[#697468]">Selecciona un deportista.</DirectorPanel>:<>
    <DirectorPanel className="overflow-hidden"><div className="flex flex-col gap-5 border-b border-[#e2e7df] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center overflow-hidden rounded-2xl bg-[#111711]">{detail.jugador.foto?<img src={detail.jugador.foto} alt="" className="h-full w-full object-cover"/>:<UserIcon className="h-8 w-8 text-white"/>}</div><div><p className="text-[11px] font-black uppercase tracking-[.14em] text-[#789600]">Perfil 360°</p><h2 className="mt-1 text-2xl font-black text-[#111711]">{detail.jugador.nombre}</h2><p className="mt-1 text-xs text-[#697468]">{detail.inscripciones.filter(i=>i.estado==='Activa').map(i=>[i.ramas?.disciplina||i.ramas?.nombre,i.categorias?.nombre].filter(Boolean).join(' · ')).join(' / ')||'Sin inscripción deportiva activa'}</p></div></div><span className={`self-start rounded-full border px-4 py-2 text-xs font-black uppercase ${availabilityClass(detail.salud.estado_disponibilidad||'Sin evaluar')}`}>{detail.salud.estado_disponibilidad||'Sin evaluar'}</span></div>
      <div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-5"><MiniStat label="Asistencia" value={metric(detail.perfil_360.asistencia.porcentaje,'%')} detail={`${detail.perfil_360.asistencia.presentes}/${detail.perfil_360.asistencia.registros} registros`}/><MiniStat label="Evaluación" value={metric(detail.perfil_360.evaluacion.promedio_actual)} detail={`${detail.perfil_360.evaluacion.evaluaciones} evaluaciones`}/><MiniStat label="Eventos" value={detail.perfil_360.competencia.eventos} detail={`${detail.perfil_360.competencia.participaciones} participaciones`}/><MiniStat label="Destacados" value={detail.perfil_360.competencia.destacados} detail={`${detail.perfil_360.competencia.minutos} min`}/><MiniStat label="PB / SB" value={`${detail.perfil_360.marcas.pb_vigentes} / ${detail.perfil_360.marcas.sb_vigentes}`} detail="Marcas vigentes"/></div>
    </DirectorPanel>

    <section className="grid gap-5 2xl:grid-cols-[1fr_.9fr]">
      <DirectorPanel className="p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[.14em] text-[#789600]">Disponibilidad actual</p><h3 className="mt-1 text-xl font-black text-[#111711]">Estado para entrenar o competir</h3><p className="mt-2 text-xs leading-5 text-[#697468]">Registra únicamente el estado operacional informado por la familia o profesional responsable.</p></div><ShieldCheckIcon className="h-7 w-7 text-[#789600]"/></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className={labelClass}>Disponibilidad</span><select value={profile.estado_disponibilidad} onChange={e=>setProfile({...profile,estado_disponibilidad:e.target.value as Availability})} className={DIRECTOR_FIELD}>{availabilityOptions.map(value=><option key={value}>{value}</option>)}</select></label><label><span className={labelClass}>Motivo del cambio</span><input value={profile.motivo_disponibilidad} onChange={e=>setProfile({...profile,motivo_disponibilidad:e.target.value})} placeholder="Ej. indicación familiar/profesional" className={DIRECTOR_FIELD}/></label><label><span className={labelClass}>Restricción operacional</span><input value={profile.restriccion} onChange={e=>setProfile({...profile,restriccion:e.target.value})} placeholder="Ej. evitar impacto / carga parcial" className={DIRECTOR_FIELD}/></label></div></DirectorPanel>
      <DirectorPanel className="p-5 sm:p-6"><p className="text-[11px] font-black uppercase tracking-[.14em] text-[#789600]">Información crítica</p><h3 className="mt-1 text-xl font-black text-[#111711]">Salud y emergencia</h3><div className="mt-5 grid gap-3 sm:grid-cols-2"><label><span className={labelClass}>Grupo sanguíneo</span><input value={profile.grupo_sanguineo} onChange={e=>setProfile({...profile,grupo_sanguineo:e.target.value})} className={DIRECTOR_FIELD}/></label><label><span className={labelClass}>Contacto emergencia</span><input value={profile.contacto_emergencia_nombre} onChange={e=>setProfile({...profile,contacto_emergencia_nombre:e.target.value})} className={DIRECTOR_FIELD}/></label><label><span className={labelClass}>Teléfono emergencia</span><input value={profile.contacto_emergencia_telefono} onChange={e=>setProfile({...profile,contacto_emergencia_telefono:e.target.value})} className={DIRECTOR_FIELD}/></label><label><span className={labelClass}>Parentesco</span><input value={profile.contacto_emergencia_parentesco} onChange={e=>setProfile({...profile,contacto_emergencia_parentesco:e.target.value})} className={DIRECTOR_FIELD}/></label></div></DirectorPanel>
    </section>

    <DirectorPanel className="p-5 sm:p-6"><div className="grid gap-4 lg:grid-cols-3"><label><span className={labelClass}>Alergias relevantes</span><textarea value={profile.alergias} onChange={e=>setProfile({...profile,alergias:e.target.value})} className={DIRECTOR_TEXTAREA}/></label><label><span className={labelClass}>Medicamentos informados</span><textarea value={profile.medicamentos} onChange={e=>setProfile({...profile,medicamentos:e.target.value})} className={DIRECTOR_TEXTAREA}/></label><label><span className={labelClass}>Condiciones crónicas informadas</span><textarea value={profile.enfermedades_cronicas} onChange={e=>setProfile({...profile,enfermedades_cronicas:e.target.value})} className={DIRECTOR_TEXTAREA}/></label></div><label className="mt-4 block"><span className={labelClass}>Observaciones de salud</span><textarea value={profile.observaciones} onChange={e=>setProfile({...profile,observaciones:e.target.value})} className={DIRECTOR_TEXTAREA}/></label><div className="mt-4 flex justify-end"><button disabled={saving} onClick={()=>void saveProfile()} className={DIRECTOR_BUTTON}>{saving?'Guardando...':'Guardar salud y disponibilidad'}</button></div></DirectorPanel>

    <section className="grid gap-5 2xl:grid-cols-[1.15fr_.85fr]">
      <DirectorPanel className="p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[11px] font-black uppercase tracking-[.14em] text-[#789600]">Seguimiento</p><h3 className="mt-1 text-xl font-black text-[#111711]">Lesiones, molestias y retorno deportivo</h3></div><HeartIcon className="h-7 w-7 text-[#789600]"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input value={injury.tipo} onChange={e=>setInjury({...injury,tipo:e.target.value})} placeholder="Tipo / motivo *" className={DIRECTOR_FIELD}/><input value={injury.zona} onChange={e=>setInjury({...injury,zona:e.target.value})} placeholder="Zona corporal" className={DIRECTOR_FIELD}/><input type="date" value={injury.fecha_inicio} onChange={e=>setInjury({...injury,fecha_inicio:e.target.value})} className={DIRECTOR_FIELD}/><input type="date" value={injury.fecha_retorno_estimada} onChange={e=>setInjury({...injury,fecha_retorno_estimada:e.target.value})} className={DIRECTOR_FIELD}/></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><textarea value={injury.descripcion} onChange={e=>setInjury({...injury,descripcion:e.target.value})} placeholder="Descripción informada" className={DIRECTOR_TEXTAREA}/><textarea value={injury.restriccion} onChange={e=>setInjury({...injury,restriccion:e.target.value})} placeholder="Restricción operacional" className={DIRECTOR_TEXTAREA}/></div><div className="mt-3 flex justify-end"><button disabled={!injury.tipo.trim()||creatingInjury} onClick={()=>void addInjury()} className={DIRECTOR_BUTTON}>Registrar seguimiento</button></div><div className="mt-5 space-y-3">{detail.lesiones.map(row=><article key={row.id} className="rounded-[18px] border border-[#dfe5dc] bg-[#f8faf6] p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-black text-[#111711]">{row.tipo}{row.zona?` · ${row.zona}`:''}</p><span className="rounded-full border border-amber-200 bg-amber-50 px-2 py-0.5 text-[10px] font-black text-amber-700">{row.estado}</span></div><p className="mt-1 text-xs text-[#697468]">Inicio {date(row.fecha_inicio)}{row.fecha_retorno_estimada?` · retorno estimado ${date(row.fecha_retorno_estimada)}`:''}</p>{row.descripcion?<p className="mt-2 text-sm text-[#4f594f]">{row.descripcion}</p>:null}{row.restriccion?<p className="mt-1 text-xs font-bold text-amber-700">Restricción: {row.restriccion}</p>:null}</div>{row.estado!=='Cerrada'?<select value={row.estado} onChange={e=>void updateInjury(row.id,e.target.value)} className={`${DIRECTOR_FIELD} max-w-[220px]`}>{injuryStates.map(value=><option key={value}>{value}</option>)}</select>:<CheckCircleIcon className="h-6 w-6 text-[#5f7900]"/>}</div></article>)}{!detail.lesiones.length?<div className="rounded-[18px] border border-dashed border-[#d9e0d6] p-7 text-center text-sm text-[#697468]">Sin seguimientos registrados.</div>:null}</div></DirectorPanel>

      <DirectorPanel className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[11px] font-black uppercase tracking-[.14em] text-[#789600]">Documentación</p><h3 className="mt-1 text-xl font-black text-[#111711]">Certificados deportivos</h3></div><DocumentCheckIcon className="h-7 w-7 text-[#789600]"/></div><div className="mt-5 space-y-3"><input value={certificate.tipo} onChange={e=>setCertificate({...certificate,tipo:e.target.value})} placeholder="Tipo de certificado" className={DIRECTOR_FIELD}/><div className="grid grid-cols-2 gap-3"><label><span className={labelClass}>Emisión</span><input type="date" value={certificate.fecha_emision} onChange={e=>setCertificate({...certificate,fecha_emision:e.target.value})} className={DIRECTOR_FIELD}/></label><label><span className={labelClass}>Vencimiento</span><input type="date" value={certificate.fecha_vencimiento} onChange={e=>setCertificate({...certificate,fecha_vencimiento:e.target.value})} className={DIRECTOR_FIELD}/></label></div><input value={certificate.archivo_url} onChange={e=>setCertificate({...certificate,archivo_url:e.target.value})} placeholder="Enlace al documento (opcional)" className={DIRECTOR_FIELD}/><textarea value={certificate.observaciones} onChange={e=>setCertificate({...certificate,observaciones:e.target.value})} placeholder="Observaciones" className={DIRECTOR_TEXTAREA}/><button disabled={creatingCertificate} onClick={()=>void addCertificate()} className={`${DIRECTOR_BUTTON} w-full`}>Registrar certificado</button></div><div className="mt-5 space-y-3">{detail.certificados.map(row=><article key={row.id} className="rounded-[18px] border border-[#dfe5dc] bg-[#f8faf6] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-black text-[#111711]">{row.tipo}</p><p className="mt-1 text-xs text-[#697468]">Emisión {date(row.fecha_emision)} · Vence {date(row.fecha_vencimiento)}</p></div><span className={`rounded-full px-2 py-1 text-[9px] font-black uppercase ${row.estado_calculado==='Vigente'?'bg-[#e8f6d0] text-[#416400]':row.estado_calculado==='Por vencer'?'bg-amber-50 text-amber-700':row.estado_calculado==='Vencido'?'bg-red-50 text-red-700':'bg-[#eef1ec] text-[#697468]'}`}>{row.estado_calculado}</span></div>{row.archivo_url?<a href={row.archivo_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex text-xs font-black text-[#5f7900]">Abrir documento →</a>:null}</article>)}{!detail.certificados.length?<div className="rounded-[18px] border border-dashed border-[#d9e0d6] p-6 text-center text-sm text-[#697468]">Sin certificados registrados.</div>:null}</div></DirectorPanel>
    </section>
   </>}</div>
  </section>
 </DirectorPage>;
}

function HeroMetric({label,value}:{label:string;value:number}){return <div className="rounded-[16px] border border-white/15 bg-white/[.055] px-3 py-3 text-center"><p className="text-2xl font-black text-white">{value}</p><p className="mt-1 text-[9px] font-black uppercase tracking-[.08em] text-[#b7ff00]">{label}</p></div>}
function MiniStat({label,value,detail}:{label:string;value:string|number;detail:string}){return <div className="rounded-[16px] border border-[#dfe5dc] bg-[#f8faf6] p-3"><p className="text-[9px] font-black uppercase tracking-[.08em] text-[#758074]">{label}</p><p className="mt-1 text-lg font-black text-[#111711]">{value}</p><p className="mt-1 text-[10px] text-[#697468]">{detail}</p></div>}
