import { useEffect, useMemo, useState } from 'react';
import { CheckCircleIcon, CreditCardIcon, SparklesIcon, UserGroupIcon } from '@heroicons/react/24/outline';
import api from '../api/axiosConfig';

type Cycle='monthly'|'annual';
type Plan={code:string;name:string;priceClp:number;founderPriceClp:number;professorLimit:number;playerLimit:number|null;monthly:{netClp:number;grossClp:number};annual:{netClp:number;grossClp:number;regularNetClp:number;monthsIncluded:number;monthsCharged:number;equivalentMonthlyNetClp:number};founder:{netClp:number;grossClp:number;durationMonths:number}};
type AddonQuote={chargedNetClp:number;chargedGrossClp:number;regularNetClp:number};
type Payload={plans:Plan[];guardianAddon:{name:string;priceClp:number;grossClp:number;monthly:AddonQuote;annual:AddonQuote;features:string[]};currentGuardianLicense:{active:boolean;trialIncluded:boolean;endsAt?:string|null};founder:{available:boolean;remainingSlots:number;existingFounder:boolean;founderNumber?:number|null;guaranteeEndsAt?:string|null};currentSubscription?:{trial?:boolean;daysRemaining?:number;status?:string;reason?:string}|null};
type MpStatus={capabilities:{platformCheckout:boolean}};
const money=(v:number)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(v||0);
const planFeatures:Record<string,string[]>={formacion:['Hasta 100 alumnos','5 profesores','1 sede y 1 rama','Matrícula, asistencia, finanzas y uniformes','Evaluaciones deportivas estándar','Amistosos programables','Exportación básica y avisos operacionales'],competencia:['Hasta 300 alumnos','10 profesores','2 sedes y 2 ramas','Campeonatos, eventos y resultados multideporte','Preparación de partidos y alertas','Criterios de evaluación personalizados','Grupos WhatsApp y exportaciones deportivas'],alto_rendimiento:['Alumnos sin límite · 30 profesores','Sedes y ramas sin límite','Perfil 360° y analítica longitudinal','Salud y disponibilidad deportiva','Seguimiento de lesiones, retorno y certificados']};
export default function SubscriptionCommercialV2(){
 const [data,setData]=useState<Payload|null>(null);const [mp,setMp]=useState<MpStatus|null>(null);const [error,setError]=useState('');const [cycle,setCycle]=useState<Cycle>('monthly');const [founder,setFounder]=useState(false);const [guardians,setGuardians]=useState(false);const [loadingPlan,setLoadingPlan]=useState<string|null>(null);
 const load=async()=>{try{const [plans,status]=await Promise.all([api.get('/api/subscriptions/plans'),api.get('/api/mercadopago/status')]);setData(plans.data.data);setMp(status.data.data);setGuardians(Boolean(plans.data.data?.currentGuardianLicense?.active&&!plans.data.data?.currentGuardianLicense?.trialIncluded));}catch(err:any){setError(err.response?.data?.error||'No fue posible cargar los planes.');}};
 useEffect(()=>{void load();},[]);useEffect(()=>{if(cycle==='annual')setFounder(false);},[cycle]);
 const addonNet=useMemo(()=>!data||!guardians?0:(cycle==='annual'?data.guardianAddon.annual.chargedNetClp:data.guardianAddon.monthly.chargedNetClp),[data,guardians,cycle]);
 const checkout=async(plan:Plan)=>{setLoadingPlan(plan.code);setError('');try{const r=await api.post('/api/mercadopago/platform-subscription/plan',{plan_code:plan.code,billing_cycle:cycle,promotion_code:founder?'founder':null,guardian_license:guardians});window.location.assign(r.data.data.checkoutUrl);}catch(err:any){setError(err.response?.data?.error||'No fue posible preparar el pago.');setLoadingPlan(null);}};
 if(!data)return <div className="mx-auto max-w-6xl py-20 text-center text-[#8995a4]">{error||'Cargando planes...'}</div>;
 const checkoutReady=mp?.capabilities.platformCheckout===true;
 return <div className="mx-auto max-w-7xl space-y-7 pb-16"><section className="rounded-[32px] border border-[#289E9D]/25 bg-[radial-gradient(circle_at_top_right,rgba(40,158,157,.18),transparent_38%),linear-gradient(135deg,#172530,#101620)] p-7 sm:p-9"><p className="text-xs font-black uppercase tracking-[.18em] text-[#70e4df]">Licencia Lestra Deportivo</p><h1 className="mt-2 text-4xl font-black text-white">Elige tu plan</h1><p className="mt-3 max-w-3xl leading-7 text-[#9aa6b5]">El monto final se envía directamente a Mercado Pago. Cuando la operación es aprobada, Lestra activa la licencia automáticamente; no necesitas informar ni enviar comprobantes.</p>{data.currentSubscription?.trial?<p className="mt-4 inline-flex rounded-full border border-emerald-400/25 bg-emerald-500/10 px-4 py-2 text-sm font-bold text-emerald-200">Prueba Full · {data.currentSubscription.daysRemaining??0} días restantes</p>:null}</section>{error?<div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-red-200">{error}</div>:null}{!checkoutReady?<div className="rounded-2xl border border-amber-400/25 bg-amber-500/10 p-4 text-amber-200">Checkout Pro todavía necesita las credenciales de producción de Mercado Pago de Lestra. Los planes no se pueden cobrar hasta completar esa configuración.</div>:null}
 <section className="grid gap-4 md:grid-cols-3"><button onClick={()=>setCycle('monthly')} className={`rounded-2xl border p-5 text-left ${cycle==='monthly'?'border-[#289E9D] bg-[#289E9D]/10':'border-white/10 bg-[#151b25]'}`}><b className="text-white">Mensual</b><p className="mt-1 text-sm text-[#8995a4]">Flexibilidad mes a mes</p></button><button onClick={()=>setCycle('annual')} className={`rounded-2xl border p-5 text-left ${cycle==='annual'?'border-[#C8A96B] bg-[#C8A96B]/10':'border-white/10 bg-[#151b25]'}`}><b className="text-white">Anual · 2 meses gratis</b><p className="mt-1 text-sm text-[#D8BE87]">12 meses pagando 10</p></button><button disabled={cycle==='annual'||!data.founder.available} onClick={()=>setFounder(!founder)} className={`rounded-2xl border p-5 text-left disabled:opacity-35 ${founder?'border-violet-400 bg-violet-500/10':'border-white/10 bg-[#151b25]'}`}><b className="flex items-center gap-2 text-white"><SparklesIcon className="h-5 w-5"/>Precio Fundador</b><p className="mt-1 text-sm text-[#8995a4]">{data.founder.remainingSlots} de 10 cupos disponibles · solo mensual</p></button></section>
 <section className={`rounded-3xl border p-6 ${guardians?'border-violet-400/40 bg-violet-500/10':'border-white/10 bg-[#151b25]'}`}><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-500/15"><UserGroupIcon className="h-7 w-7 text-violet-300"/></div><div><h2 className="text-xl font-black text-white">Apoderados PRO</h2><p className="mt-1 text-sm text-[#9aa6b5]">Complemento opcional para toda la academia.</p><p className="mt-2 font-black text-violet-200">{cycle==='annual'?`${money(data.guardianAddon.annual.chargedNetClp)} + IVA/año`:`${money(data.guardianAddon.monthly.chargedNetClp)} + IVA/mes`}</p></div></div><label className="inline-flex cursor-pointer items-center gap-3 rounded-xl border border-white/10 bg-[#0d1117] px-4 py-3"><input type="checkbox" checked={guardians} onChange={e=>setGuardians(e.target.checked)} className="h-5 w-5 accent-violet-500"/><span className="font-black text-white">{guardians?'Incluido en este pago':'Agregar al plan'}</span></label></div></section>
 <section className="grid gap-5 lg:grid-cols-3">{data.plans.map(plan=>{const base=founder?plan.founder.netClp:cycle==='annual'?plan.annual.netClp:plan.monthly.netClp;const total=base+addonNet;return <article key={plan.code} className={`rounded-3xl border bg-[#151b25] p-6 ${plan.code==='competencia'?'border-[#289E9D]/45':'border-white/10'}`}><p className="text-xs font-black uppercase tracking-wider text-[#70e4df]">{plan.code==='competencia'?'Más elegido':'Plan'}</p><h2 className="mt-2 text-2xl font-black text-white">{plan.name}</h2><p className="mt-4 text-3xl font-black text-white">{money(total)} <span className="text-xs font-bold text-[#8995a4]">+ IVA{cycle==='annual'?'/año':'/mes'}</span></p><ul className="mt-5 space-y-2">{(planFeatures[plan.code]||[]).map(f=><li key={f} className="flex gap-2 text-sm text-[#c7d0da]"><CheckCircleIcon className="h-5 w-5 shrink-0 text-emerald-300"/>{f}</li>)}</ul><button disabled={loadingPlan===plan.code||!checkoutReady} onClick={()=>void checkout(plan)} className="mt-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#009ee3] px-4 font-black text-white disabled:opacity-40"><CreditCardIcon className="h-5 w-5"/>{loadingPlan===plan.code?'Conectando con Mercado Pago...':`Pagar ${money(Math.round(total*1.19))}`}</button></article>})}</section><p className="text-center text-xs text-[#697586]">Valores netos + IVA. Mercado Pago procesa la transacción; Lestra concilia la confirmación automáticamente mediante webhook.</p></div>;
}
