import { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import { CheckCircleIcon, ClockIcon, ShieldCheckIcon } from '@heroicons/react/24/outline';
import api from '../api/axiosConfig';
import { useAppDialog } from '../contexts/DialogContext';

type Plan = { code: string; name: string; priceClp: number; professorLimit: number; playerLimit: number | null; grossClp: number };
type Payload = { plans: Plan[]; guardianAddon: { priceClp: number; grossClp: number }; gateway: { provider: string; configured: boolean }; currentSubscription?: { trial?: boolean; remainingDays?: number } };
const money = (value: number) => new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 }).format(value || 0);
const featureMap: Record<string, string[]> = {
  formacion: ['Operación diaria completa', 'Finanzas, uniformes y partidos', 'Hasta 100 jugadores', 'Hasta 3 profesores'],
  competencia: ['Todo Formación', 'Torneos y preparación de partidos', 'Evaluaciones, alertas y exportaciones', '300 jugadores · 10 profesores'],
  alto_rendimiento: ['Todo Competencia', 'Ficha médica y analítica avanzada', 'Marca personalizada', 'Jugadores sin límite · 30 profesores'],
};

const Subscription = () => {
  const { notify } = useAppDialog(); const [guardians, setGuardians] = useState(false); const [paying, setPaying] = useState<string | null>(null); const [paymentState, setPaymentState] = useState<'checking' | 'paid' | 'pending' | null>(null); const [params, setParams] = useSearchParams(); const queryClient = useQueryClient();
  const { data, isLoading } = useQuery({ queryKey: ['subscription-plans'], queryFn: async () => (await api.get('/api/subscriptions/plans')).data.data as Payload });
  useEffect(() => { const token = params.get('flow_token'); if (!token) return; let active = true; setPaymentState('checking'); api.get(`/api/subscriptions/payment-status?token=${encodeURIComponent(token)}`).then(async (response) => { if (!active) return; const paid = response.data.data.estado === 'pagado'; setPaymentState(paid ? 'paid' : 'pending'); if (paid) { await queryClient.invalidateQueries({ queryKey: ['mi-plan'] }); await queryClient.invalidateQueries({ queryKey: ['subscription-plans'] }); } setParams({}, { replace: true }); }).catch(() => { if (active) setPaymentState('pending'); }); return () => { active = false; }; }, [params, queryClient, setParams]);
  const checkout = async (plan: Plan) => { setPaying(plan.code); try { const response = await api.post('/api/subscriptions/checkout', { plan_code: plan.code, guardian_license: guardians }); window.location.assign(response.data.data.checkoutUrl); } catch (err: any) { await notify(err.response?.data?.error || 'No fue posible iniciar el pago.', { title: 'Contratar Syncademia' }); } finally { setPaying(null); } };
  if (isLoading || !data) return <div className="py-20 text-center text-[#91a0b2]">Preparando planes...</div>;
  return <div className="mx-auto max-w-6xl space-y-8 pb-12">{paymentState ? <div className={`flex items-center gap-3 rounded-2xl border p-5 ${paymentState === 'paid' ? 'border-emerald-400/25 bg-emerald-500/10 text-emerald-100' : 'border-amber-400/25 bg-amber-500/10 text-amber-100'}`}>{paymentState === 'paid' ? <CheckCircleIcon className="h-7 w-7 shrink-0" /> : <ClockIcon className="h-7 w-7 shrink-0" />}<div><p className="font-black">{paymentState === 'checking' ? 'Verificando tu pago...' : paymentState === 'paid' ? 'Licencia activada correctamente' : 'El pago todavía está pendiente'}</p><p className="mt-1 text-sm opacity-75">{paymentState === 'paid' ? 'Tu academia ya puede continuar con el plan contratado.' : 'Si ya pagaste, Flow confirmará la operación automáticamente.'}</p></div></div> : null}<header className="text-center"><p className="text-xs font-black uppercase tracking-[0.22em] text-[#48d8d0]">Tu siguiente etapa</p><h1 className="mt-3 text-4xl font-black text-white sm:text-5xl">Elige el nivel de gestión ideal</h1><p className="mx-auto mt-4 max-w-2xl text-[#9aa6b5]">Precios mensuales en pesos chilenos + IVA. El pago corresponde únicamente a la licencia de Syncademia; nunca procesamos el dinero de tus apoderados.</p></header>
    <label className="mx-auto flex max-w-xl cursor-pointer items-center justify-between gap-4 rounded-2xl border border-violet-400/25 bg-violet-500/10 p-5"><div><p className="font-black text-violet-200">Añadir Apoderados PRO</p><p className="mt-1 text-sm text-violet-200/70">{money(data.guardianAddon.priceClp)} + IVA · {money(data.guardianAddon.grossClp)} total</p></div><input type="checkbox" checked={guardians} onChange={(e) => setGuardians(e.target.checked)} className="h-6 w-6 accent-violet-500" /></label>
    <section className="grid gap-5 lg:grid-cols-3">{data.plans.map((plan) => <article key={plan.code} className={`relative flex flex-col rounded-[26px] border p-6 ${plan.code === 'competencia' ? 'border-[#48d8d0] bg-[#18252d] shadow-[0_20px_60px_rgba(40,158,157,0.18)]' : 'border-white/10 bg-[#151b25]'}`}>{plan.code === 'competencia' ? <span className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-[#289E9D] px-4 py-1 text-xs font-black text-white">MÁS EQUILIBRADO</span> : null}<h2 className="text-2xl font-black text-white">{plan.name}</h2><div className="mt-5"><span className="text-4xl font-black text-[#70e4df]">{money(plan.priceClp)}</span><span className="text-sm text-[#91a0b2]"> + IVA / mes</span><p className="mt-1 text-sm text-[#91a0b2]">{money(plan.grossClp + (guardians ? data.guardianAddon.grossClp : 0))} total con IVA</p></div><ul className="mt-6 flex-1 space-y-3">{featureMap[plan.code].map((feature) => <li key={feature} className="flex gap-2 text-sm text-[#d6dde5]"><CheckCircleIcon className="h-5 w-5 shrink-0 text-[#48d8d0]" />{feature}</li>)}</ul><button disabled={paying !== null || !data.gateway.configured} onClick={() => void checkout(plan)} className="btn-primary mt-7 min-h-12 w-full disabled:cursor-not-allowed disabled:opacity-50">{paying === plan.code ? 'Conectando con Flow...' : data.gateway.configured ? `Contratar ${plan.name}` : 'Pago online en configuración'}</button></article>)}</section>
    <div className="flex items-start gap-3 rounded-2xl border border-emerald-400/20 bg-emerald-500/10 p-5"><ShieldCheckIcon className="h-7 w-7 shrink-0 text-emerald-300" /><p className="text-sm leading-6 text-emerald-100">La contratación será procesada por Flow. Syncademia no almacena números de tarjeta ni credenciales bancarias. Mientras conectamos las credenciales comerciales, tus datos y tu prueba permanecen intactos.</p></div>
  </div>;
};

export default Subscription;
