import { useEffect, useMemo, useState } from 'react';
import { CheckCircleIcon, CreditCardIcon, SparklesIcon, UserGroupIcon } from '@heroicons/react/24/outline';
import api from '../api/axiosConfig';
import { useAppDialog } from '../contexts/DialogContext';

type Cycle='monthly'|'annual';
type Plan={code:string;name:string;priceClp:number;founderPriceClp:number;professorLimit:number;playerLimit:number|null;monthly:{netClp:number;grossClp:number};annual:{netClp:number;grossClp:number;regularNetClp:number;monthsIncluded:number;monthsCharged:number;equivalentMonthlyNetClp:number};founder:{netClp:number;grossClp:number;durationMonths:number}};
type AddonQuote={chargedNetClp:number;chargedGrossClp:number;regularNetClp:number};
type Payload={plans:Plan[];guardianAddon:{name:string;priceClp:number;grossClp:number;monthly:AddonQuote;annual:AddonQuote;features:string[]};currentGuardianLicense:{active:boolean;trialIncluded:boolean;endsAt?:string|null};founder:{available:boolean;remainingSlots:number;existingFounder:boolean;founderNumber?:number|null;guaranteeEndsAt?:string|null};gateway:{configured:boolean;provider:string};currentSubscription?:{trial?:boolean;daysRemaining?:number;status?:string;reason?:string}|null};
type Checkout={chargeId:string;checkoutUrl:string;amountClp:number;netAmountClp:number;planName:string;guardianLicense:boolean;billingCycle:Cycle;promotionCode?:string|null;founderSlot?:number|null;discountClp:number;expiresAt:string};
const money=(v:number)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(v||0);
const planFeatures:Record<string,string[]>={
 formacion:['Hasta 100 alumnos','3 profesores','Matrícula, asistencia y finanzas','Evaluaciones deportivas estándar','1 sede y 1 rama'],
 competencia:['Hasta 300 alumnos','10 profesores','2 sedes y 2 ramas','Campeonatos, eventos y resultados multideporte','Preparación de partidos y alertas','Criterios de evaluación personalizados','Grupos WhatsApp y exportaciones'],
 alto_rendimiento:['Alumnos sin límite','30 profesores','Sedes y ramas sin límite','Ficha médica y analítica avanzada','Marca personalizada y comunicaciones avanzadas']
};
export default function SubscriptionCommercial(){
 const {notify}=useAppDialog();
 const [data,setData]=useState<Payload|null>(null);const [error,setError]=useState('');const [cycle,setCycle]=useState<Cycle>('monthly');const [founder,setFounder]=useState(false);const [guardians,setGuardians]=useState(false);const [loadingPlan,setLoadingPlan]=useState<string|null>(null);const [order,setOrder]=useState<Checkout|null>(null);const [payer,setPayer]=useState('');const [reference,setReference]=useState('');const [checking,setChecking]=useState(false);
 const load=()=>api.get('/api/subscriptions/plans').then(r=>{setData(r.data.data);setGuardians(Boolean(r.data.data?.currentGuardianLicense?.active&&!r.data.data?.currentGuardianLicense?.trialIncluded));}).catch((err)=>setError(err.response?.data?.error||'No fue posible cargar los planes.'));
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(cycle==='annual')setFounder(false);},[cycle]);
 const addonNet=useMemo(()=>!data||!guardians?0:(cycle==='annual'?data.guardianAddon.annual.chargedNetClp:data.guardianAddon.monthly.chargedNetClp),[data,guardians,cycle]);
 if(!data)return <div className="mx-auto max-w-6xl py-20 text-center text-[#8995a4]">{error||'Cargando planes...'}</div>;
 const checkout=async(plan:Plan)=>{setLoadingPlan(plan.code);setError('');try{const r=await api.post('/api/subscriptions/checkout',{plan_code:plan.code,billing_cycle:cycle,promotion_code:founder?'founder':null,guardian_license:guardians});setOrder(r.data.data);}catch(err:any){setError(err.response?.data?.error||'No fue posible preparar el pago.');}finally{setLoadingPlan(null);}};
 const inform=async()=>{if(!order)return;try{await api.patch(`/api/subscriptions/payment-notice/${order.chargeId}`,{payer_name:payer,reference});await notify('Pago informado. La activación quedará lista cuando se valide el abono.',{title:'Pago informado'});}catch(err:any){await notify(err.response?.data?.error||'No fue posible informar el pago.');}};
 const check=async()=>{if(!order)return;setChecking(true);try{const r=await api.get(`/api/subscriptions/payment-status?chargeId=${encodeURIComponent(order.chargeId)}`);if(r.data.data.estado==='pagado'){setOrder(null);await load();await notify('Tu suscripción fue activada correctamente.',{title:'Suscripción activa'});}else await notify('El pago aún está pendiente de validación.',{title:'Validación pendiente'});}catch(err:any){await notify(err.response?.data?.error||'No fue posible revisar el pago.');}finally{setChecking(false);}};
 return <div className="mx-auto max-w-7xl space-y-7 pb-16">
  <section className="rounded-[32px] border border-[#289E9D]/25 bg-[radial-gradient(circle_at_top_right,rgba(40,158,157,.18),transparent_38%),linear-gradient(135deg,#172530,#101620)] p-7 sm:p-9"><p className="text-xs font-black uppercase tracking-[.18em] text-[#70e4df]">Licencia Lestra</p><h1 className="mt-2 text-4xl font-black text-white">Plan base + complementos que tú eliges</h1><p className="mt-3 max-w-3xl leading-7 text-[#9aa6b5]">El plan cubre la operación de la academia. <b className="text-violet-200">Apoderados PRO se contrata aparte</b> para habilitar portal familiar, comunicaciones y solicitudes deportivas para todas las familias.</p>{data.currentSubscription?.trial?<p className="mt-4 inline-flex rounded-full border border-emerald-400/25 bg-emerald-500/10 px-4 py-2 text-sm font-bold text-emerald-200">Prueba Full: Apoderados PRO incluido · {data.currentSubscription.daysRemaining??0} días restantes</p>:null}</section>
  {error?<div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-red-200">{error}</div>:null}
  <section className="grid gap-4 md:grid-cols-3"><button onClick={()=>setCycle('monthly')} className={`rounded-2xl border p-5 text-left ${cycle==='monthly'?'border-[#289E9D] bg-[#289E9D]/10':'border-white/10 bg-[#151b25]'}`}><b className="text-white">Mensual</b><p className="mt-1 text-sm text-[#8995a4]">Flexibilidad mes a mes</p></button><button onClick={()=>setCycle('annual')} className={`rounded-2xl border p-5 text-left ${cycle==='annual'?'border-[#C8A96B] bg-[#C8A96B]/10':'border-white/10 bg-[#151b25]'}`}><b className="text-white">Anual · 2 meses gratis</b><p className="mt-1 text-sm text-[#D8BE87]">12 meses pagando 10</p></button><button disabled={cycle==='annual'||!data.founder.available} onClick={()=>setFounder(!founder)} className={`rounded-2xl border p-5 text-left disabled:opacity-35 ${founder?'border-violet-400 bg-violet-500/10':'border-white/10 bg-[#151b25]'}`}><b className="flex items-center gap-2 text-white"><SparklesIcon className="h-5 w-5"/>Precio Fundador</b><p className="mt-1 text-sm text-[#8995a4]">{data.founder.remainingSlots} de 10 cupos disponibles · solo mensual</p></button></section>
  <section className={`rounded-3xl border p-6 ${guardians?'border-violet-400/40 bg-violet-500/10':'border-white/10 bg-[#151b25]'}`}><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-500/15"><UserGroupIcon className="h-7 w-7 text-violet-300"/></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-black text-white">Apoderados PRO</h2><span className="rounded-full bg-violet-500/15 px-2 py-1 text-[10px] font-black uppercase text-violet-300">Complemento opcional</span></div><p className="mt-1 text-sm text-[#9aa6b5]">Una licencia para toda la academia, no por apoderado. Portal familiar, cuenta, chat, privacidad y solicitud de nuevas disciplinas.</p><p className="mt-2 font-black text-violet-200">{cycle==='annual'?`${money(data.guardianAddon.annual.chargedNetClp)} + IVA/año`:`${money(data.guardianAddon.monthly.chargedNetClp)} + IVA/mes`}{cycle==='annual'?<span className="ml-2 text-xs text-[#D8BE87]">12 meses pagando 10</span>:null}</p></div></div><label className="inline-flex cursor-pointer items-center gap-3 rounded-xl border border-white/10 bg-[#0d1117] px-4 py-3"><input type="checkbox" checked={guardians} onChange={(e)=>setGuardians(e.target.checked)} className="h-5 w-5 accent-violet-500"/><span className="font-black text-white">{guardians?'Incluido en este pago':'Agregar al plan'}</span></label></div>{data.currentGuardianLicense.active?<p className="mt-4 text-xs text-emerald-300">Actualmente activo{data.currentGuardianLicense.trialIncluded?' por la prueba Full':data.currentGuardianLicense.endsAt?` hasta ${new Date(`${data.currentGuardianLicense.endsAt}T12:00:00`).toLocaleDateString('es-CL')}`:''}.</p>:null}</section>
  <section className="grid gap-5 lg:grid-cols-3">{data.plans.map((plan)=>{const base=founder?plan.founder.netClp:cycle==='annual'?plan.annual.netClp:plan.monthly.netClp;const total=base+addonNet;return <article key={plan.code} className={`rounded-3xl border bg-[#151b25] p-6 ${plan.code==='competencia'?'border-[#289E9D]/45':'border-white/10'}`}><p className="text-xs font-black uppercase tracking-wider text-[#70e4df]">{plan.code==='competencia'?'Más elegido':'Plan'}</p><h2 className="mt-2 text-2xl font-black text-white">{plan.name}</h2><p className="mt-4 text-3xl font-black text-white">{money(total)} <span className="text-xs font-bold text-[#8995a4]">+ IVA{cycle==='annual'?'/año':'/mes'}</span></p>{guardians?<p className="mt-1 text-xs text-violet-300">Incluye {money(addonNet)} netos de Apoderados PRO en este período</p>:<p className="mt-1 text-xs text-[#697586]">Sin portal familiar</p>}<ul className="mt-5 space-y-2">{(planFeatures[plan.code]||[]).map(f=><li key={f} className="flex gap-2 text-sm text-[#c7d0da]"><CheckCircleIcon className="h-5 w-5 shrink-0 text-emerald-300"/>{f}</li>)}</ul><button disabled={loadingPlan===plan.code||!data.gateway.configured} onClick={()=>void checkout(plan)} className="mt-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#289E9D] px-4 font-black text-white disabled:opacity-40"><CreditCardIcon className="h-5 w-5"/>{loadingPlan===plan.code?'Preparando...':'Contratar con Mercado Pago'}</button></article>})}</section>
  <p className="text-center text-xs text-[#697586]">Valores netos + IVA. Precio Fundador no se acumula con anualidad. El descuento Fundador aplica al plan base; Apoderados PRO mantiene su precio de lista.</p>
  {order?<div className="fixed inset-0 z-[90] grid place-items-center overflow-y-auto bg-black/80 p-4 backdrop-blur"><div className="w-full max-w-xl rounded-3xl border border-[#289E9D]/30 bg-[#151b25] p-6"><h2 className="text-2xl font-black text-white">Completar pago</h2><p className="mt-2 text-[#9aa6b5]">{order.planName}{order.guardianLicense?' + Apoderados PRO':''}</p><p className="mt-3 text-3xl font-black text-white">{money(order.amountClp)}</p><p className="text-xs text-[#8995a4]">monto final con IVA</p><a href={order.checkoutUrl} target="_blank" rel="noreferrer" className="mt-5 block rounded-xl bg-[#009ee3] px-5 py-3 text-center font-black text-white">Abrir Mercado Pago</a><div className="mt-5 grid gap-3 sm:grid-cols-2"><input value={payer} onChange={(e)=>setPayer(e.target.value)} placeholder="Nombre del pagador" className="rounded-xl border border-white/10 bg-[#0d1117] px-4 py-3"/><input value={reference} onChange={(e)=>setReference(e.target.value)} placeholder="Referencia opcional" className="rounded-xl border border-white/10 bg-[#0d1117] px-4 py-3"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><button onClick={()=>void inform()} className="rounded-xl border border-white/10 px-4 py-3 font-black">Ya pagué</button><button disabled={checking} onClick={()=>void check()} className="rounded-xl bg-emerald-500 px-4 py-3 font-black text-emerald-950">{checking?'Revisando...':'Revisar activación'}</button></div><button onClick={()=>setOrder(null)} className="mt-4 w-full text-sm text-[#8995a4]">Cerrar</button></div></div>:null}
 </div>;
}
