import { useCallback, useEffect, useMemo, useState } from 'react';
import api from '../api/axiosConfig';
import { useAppDialog } from '../contexts/DialogContext';

type Branch={id:string;nombre:string;disciplina:string;sede_id:string;sedes?:{id:string;nombre:string}|null};
type Garment={id:string;nombre:string;precio:number;tipo_operacion:'Stock'|'Taller';stock_disponible:number;aplica_numero:boolean;aplica_nombre_estampado:boolean;rama_id?:string|null;sede_id?:string|null;ramas?:Branch|null;sedes?:{id:string;nombre:string}|null};
type Enrollment={id:string;sede_id:string;rama_id:string;categoria_id?:string|null;rol_especialidad?:string|null};
type Student={id:string;nombre:string;foto_base64?:string|null;foto_url?:string|null;avatar_url?:string|null;inscripciones:Enrollment[]};
type Order={id:string;jugador_id:string;inscripcion_id?:string|null;rama_id?:string|null;sede_id?:string|null;prenda_id?:string|null;prenda_nombre:string;talla:string;monto:number;estado_pago:string;estado_entrega:string;numero_estampado?:number|null;nombre_estampado?:string|null;jugadores?:{id:string;nombre:string}|null;ramas?:{id:string;nombre:string;disciplina:string}|null;sedes?:{id:string;nombre:string}|null};
type Payload={ramas:Branch[];rama_seleccionada_id?:string|null;catalogo:Garment[];pedidos:Order[];alumnos:Student[];resumenTaller:Record<string,number>};

const field='w-full rounded-xl border border-[#30363d] bg-[#0d1117] px-3 py-2.5 text-sm text-white outline-none focus:border-[#289E9D]';
const panel='rounded-[24px] border border-white/10 bg-[#151b25]';
const money=(value:number)=>`$${Math.round(Number(value)||0).toLocaleString('es-CL')}`;

export default function UniformesMultirama(){
  const {notify}=useAppDialog();
  const [data,setData]=useState<Payload>({ramas:[],catalogo:[],pedidos:[],alumnos:[],resumenTaller:{}});
  const [branchId,setBranchId]=useState('');
  const [loading,setLoading]=useState(true);
  const [catalogOpen,setCatalogOpen]=useState(false);
  const [orderOpen,setOrderOpen]=useState(false);
  const [catalogForm,setCatalogForm]=useState({nombre:'',precio:'0',tipo_operacion:'Taller',stock_disponible:'0',aplica_numero:false,aplica_nombre_estampado:false,rama_id:''});
  const [orderForm,setOrderForm]=useState({jugador_id:'',rama_id:'',prenda_id:'',talla:'',numero_estampado:'',nombre_estampado:'',estado_pago:'Pendiente de Pago',generar_cobro:true});

  const load=useCallback(async(selectedBranch=branchId)=>{
    setLoading(true);
    try{
      const response=await api.get('/api/uniformes',{params:selectedBranch?{rama_id:selectedBranch}:undefined});
      const payload=response.data.data as Payload;
      setData(payload);
      if(!selectedBranch&&payload.ramas.length===1)setBranchId(payload.ramas[0].id);
    }catch(error:any){await notify(error.response?.data?.error||'No fue posible cargar Uniformes.');}
    finally{setLoading(false);}
  },[branchId,notify]);
  useEffect(()=>{void load(branchId);},[branchId]); // eslint-disable-line react-hooks/exhaustive-deps

  const branch=useMemo(()=>data.ramas.find((item)=>item.id===branchId)||null,[data.ramas,branchId]);
  const eligibleGarments=useMemo(()=>data.catalogo.filter((item)=>!orderForm.rama_id||!item.rama_id||item.rama_id===orderForm.rama_id),[data.catalogo,orderForm.rama_id]);
  const selectedGarment=eligibleGarments.find((item)=>item.id===orderForm.prenda_id)||null;

  const openOrder=(student?:Student)=>{
    const enrollment=student?.inscripciones.find((item)=>item.rama_id===branchId)||student?.inscripciones[0];
    setOrderForm({jugador_id:student?.id||'',rama_id:enrollment?.rama_id||branchId||'',prenda_id:'',talla:'',numero_estampado:'',nombre_estampado:'',estado_pago:'Pendiente de Pago',generar_cobro:true});
    setOrderOpen(true);
  };
  const saveCatalog=async()=>{
    try{
      await api.post('/api/uniformes/catalogo',{...catalogForm,precio:Number(catalogForm.precio)||0,stock_disponible:Number(catalogForm.stock_disponible)||0,rama_id:catalogForm.rama_id||null});
      setCatalogOpen(false);setCatalogForm({nombre:'',precio:'0',tipo_operacion:'Taller',stock_disponible:'0',aplica_numero:false,aplica_nombre_estampado:false,rama_id:branchId});await load(branchId);
    }catch(error:any){await notify(error.response?.data?.error||'No fue posible crear la prenda.');}
  };
  const saveOrder=async()=>{
    if(!orderForm.jugador_id||!orderForm.rama_id||!orderForm.prenda_id||!orderForm.talla)return void notify('Selecciona alumno, rama, prenda y talla.');
    try{
      await api.post('/api/uniformes/pedidos',{...orderForm,numero_estampado:orderForm.numero_estampado||null,monto:selectedGarment?.precio||0,prenda_nombre:selectedGarment?.nombre,generar_cobro:orderForm.generar_cobro});
      setOrderOpen(false);await load(branchId);await notify('Prenda asignada a la inscripción deportiva seleccionada.');
    }catch(error:any){await notify(error.response?.data?.error||'No fue posible asignar la prenda.');}
  };
  const updateOrder=async(order:Order,patch:Record<string,string>)=>{
    try{await api.put(`/api/uniformes/pedidos/${order.id}/actualizar`,patch);await load(branchId);}catch(error:any){await notify(error.response?.data?.error||'No fue posible actualizar el pedido.');}
  };

  return <div className="mx-auto max-w-7xl space-y-6 pb-16">
    <section className="rounded-[28px] border border-purple-400/20 bg-[radial-gradient(circle_at_top_right,rgba(168,85,247,.16),transparent_36%),#151b25] p-6 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-purple-300">Indumentaria multirrama</p><h1 className="mt-2 text-3xl font-black text-white">Uniformes e inventario</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#8b949e]">Cada pedido queda vinculado a la inscripción deportiva del alumno. Una prenda puede ser general para toda la academia o exclusiva de una rama.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>{setCatalogForm((current)=>({...current,rama_id:branchId}));setCatalogOpen(true);}} className="rounded-xl border border-purple-400/30 bg-purple-500/10 px-4 py-2.5 text-sm font-black text-purple-200">+ Nueva prenda</button><button onClick={()=>openOrder()} disabled={!branchId} className="rounded-xl bg-[#289E9D] px-4 py-2.5 text-sm font-black text-white disabled:opacity-40">Asignar prenda</button></div></div></section>

    <section className={`${panel} p-4`}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase text-[#70e4df]">Alcance de trabajo</p><p className="mt-1 text-sm text-[#8b949e]">Selecciona la rama para ver pedidos, alumnos y stock correspondiente.</p></div><select value={branchId} onChange={(event)=>setBranchId(event.target.value)} className={`${field} sm:max-w-sm`}><option value="">Vista global de la academia</option>{data.ramas.map((item)=><option key={item.id} value={item.id}>{item.disciplina} · {item.nombre}{item.sedes?.nombre?` · ${item.sedes.nombre}`:''}</option>)}</select></div></section>

    {loading?<div className={`${panel} p-10 text-center text-[#8b949e]`}>Cargando uniformes...</div>:<>
      <section className="grid gap-4 lg:grid-cols-[1fr_.7fr]"><div className={`${panel} p-5`}><div className="flex items-center justify-between"><div><h2 className="text-xl font-black text-white">Catálogo disponible</h2><p className="text-xs text-[#8b949e]">General + {branch?.nombre||'todas las ramas'}</p></div><span className="rounded-full bg-white/5 px-3 py-1 text-xs font-black text-[#8995a4]">{data.catalogo.length}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.catalogo.map((garment)=><article key={garment.id} className="rounded-2xl border border-white/10 bg-[#0d1117] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-black text-white">{garment.nombre}</p><p className="mt-1 text-xs text-[#8b949e]">{garment.rama_id?`${garment.ramas?.disciplina||''} · ${garment.ramas?.nombre||'Rama'}`:'Toda la academia'}</p></div><span className="font-black text-emerald-300">{money(garment.precio)}</span></div><div className="mt-3 flex gap-2 text-[10px] font-black uppercase"><span className="rounded-full bg-purple-500/10 px-2 py-1 text-purple-300">{garment.tipo_operacion}</span>{garment.tipo_operacion==='Stock'?<span className="rounded-full bg-white/5 px-2 py-1 text-[#8995a4]">Stock {garment.stock_disponible}</span>:null}</div></article>)}</div>{!data.catalogo.length?<p className="mt-5 text-sm text-[#697586]">No hay prendas en este alcance.</p>:null}</div>
      <div className={`${panel} p-5`}><h2 className="text-xl font-black text-white">Pendiente de taller</h2><p className="mt-1 text-xs text-[#8b949e]">Resumen de producción para el alcance seleccionado.</p><div className="mt-4 space-y-2">{Object.entries(data.resumenTaller).map(([key,value])=><div key={key} className="flex items-center justify-between rounded-xl border border-white/10 bg-[#0d1117] px-3 py-2"><span className="text-sm text-[#c3ccd6]">{key}</span><span className="font-black text-purple-300">{value}</span></div>)}{!Object.keys(data.resumenTaller).length?<p className="text-sm text-[#697586]">Sin pedidos de taller pendientes.</p>:null}</div></div></section>

      <section className={`${panel} overflow-hidden`}><div className="border-b border-white/10 p-5"><h2 className="text-xl font-black text-white">Pedidos</h2><p className="mt-1 text-xs text-[#8b949e]">Cada fila conserva su rama para que no se mezclen indumentarias entre disciplinas.</p></div><div className="divide-y divide-white/10">{data.pedidos.map((order)=><article key={order.id} className="grid gap-3 p-4 md:grid-cols-[1.2fr_1fr_.7fr_.8fr_auto] md:items-center"><div><p className="font-black text-white">{order.jugadores?.nombre||'Alumno'}</p><p className="mt-1 text-xs text-violet-300">{order.ramas?.disciplina||'Histórico'} · {order.ramas?.nombre||'Sin rama'}</p></div><div><p className="text-sm font-bold text-[#c3ccd6]">{order.prenda_nombre}</p><p className="text-xs text-[#697586]">Talla {order.talla}{order.numero_estampado?` · #${order.numero_estampado}`:''}</p></div><p className="font-black text-emerald-300">{money(order.monto)}</p><div className="flex flex-wrap gap-1"><span className="rounded-full bg-amber-500/10 px-2 py-1 text-[10px] font-black text-amber-300">{order.estado_pago}</span><span className="rounded-full bg-[#289E9D]/10 px-2 py-1 text-[10px] font-black text-[#70e4df]">{order.estado_entrega}</span></div><select value={order.estado_entrega} onChange={(event)=>void updateOrder(order,{estado_entrega:event.target.value})} className={`${field} py-2 md:w-44`}><option>Pendiente</option><option>En Taller</option><option>Listo para Entrega</option><option>Entregado</option></select></article>)}{!data.pedidos.length?<div className="p-8 text-center text-sm text-[#697586]">No hay pedidos para este alcance.</div>:null}</div></section>
    </>}

    {catalogOpen?<div className="fixed inset-0 z-[70] grid place-items-center bg-black/80 p-4"><div className="w-full max-w-lg rounded-[26px] border border-white/10 bg-[#151b25] p-6"><h2 className="text-2xl font-black text-white">Nueva prenda</h2><div className="mt-5 space-y-3"><input value={catalogForm.nombre} onChange={(event)=>setCatalogForm({...catalogForm,nombre:event.target.value})} placeholder="Nombre de prenda" className={field}/><div className="grid grid-cols-2 gap-3"><input type="number" min="0" value={catalogForm.precio} onChange={(event)=>setCatalogForm({...catalogForm,precio:event.target.value})} className={field} placeholder="Precio"/><select value={catalogForm.tipo_operacion} onChange={(event)=>setCatalogForm({...catalogForm,tipo_operacion:event.target.value})} className={field}><option>Taller</option><option>Stock</option></select></div>{catalogForm.tipo_operacion==='Stock'?<input type="number" min="0" value={catalogForm.stock_disponible} onChange={(event)=>setCatalogForm({...catalogForm,stock_disponible:event.target.value})} className={field} placeholder="Stock disponible"/>:null}<select value={catalogForm.rama_id} onChange={(event)=>setCatalogForm({...catalogForm,rama_id:event.target.value})} className={field}><option value="">Prenda general · toda la academia</option>{data.ramas.map((item)=><option key={item.id} value={item.id}>{item.disciplina} · {item.nombre}</option>)}</select><label className="flex items-center gap-2 text-sm text-[#c3ccd6]"><input type="checkbox" checked={catalogForm.aplica_numero} onChange={(event)=>setCatalogForm({...catalogForm,aplica_numero:event.target.checked})}/>Permite número estampado</label><label className="flex items-center gap-2 text-sm text-[#c3ccd6]"><input type="checkbox" checked={catalogForm.aplica_nombre_estampado} onChange={(event)=>setCatalogForm({...catalogForm,aplica_nombre_estampado:event.target.checked})}/>Permite nombre estampado</label></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setCatalogOpen(false)} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-black">Cancelar</button><button onClick={()=>void saveCatalog()} className="rounded-xl bg-purple-500 px-4 py-2.5 text-sm font-black">Guardar prenda</button></div></div></div>:null}

    {orderOpen?<div className="fixed inset-0 z-[70] grid place-items-center bg-black/80 p-4"><div className="w-full max-w-lg rounded-[26px] border border-white/10 bg-[#151b25] p-6"><h2 className="text-2xl font-black text-white">Asignar prenda</h2><p className="mt-1 text-xs text-[#8b949e]">Elige la inscripción deportiva, no solo la persona.</p><div className="mt-5 space-y-3"><select value={orderForm.jugador_id} onChange={(event)=>{const student=data.alumnos.find((item)=>item.id===event.target.value);const enrollment=student?.inscripciones.find((item)=>item.rama_id===branchId)||student?.inscripciones[0];setOrderForm({...orderForm,jugador_id:event.target.value,rama_id:enrollment?.rama_id||'',prenda_id:''});}} className={field}><option value="">Selecciona alumno</option>{data.alumnos.map((student)=><option key={student.id} value={student.id}>{student.nombre}</option>)}</select><select value={orderForm.rama_id} onChange={(event)=>setOrderForm({...orderForm,rama_id:event.target.value,prenda_id:''})} className={field}><option value="">Selecciona rama de la inscripción</option>{data.alumnos.find((item)=>item.id===orderForm.jugador_id)?.inscripciones.map((enrollment)=>{const b=data.ramas.find((item)=>item.id===enrollment.rama_id);return <option key={enrollment.id} value={enrollment.rama_id}>{b?`${b.disciplina} · ${b.nombre}`:enrollment.rama_id}</option>})}</select><select value={orderForm.prenda_id} onChange={(event)=>setOrderForm({...orderForm,prenda_id:event.target.value})} className={field}><option value="">Selecciona prenda compatible</option>{eligibleGarments.map((garment)=><option key={garment.id} value={garment.id}>{garment.nombre} · {money(garment.precio)}{garment.rama_id?' · rama':' · general'}</option>)}</select><input value={orderForm.talla} onChange={(event)=>setOrderForm({...orderForm,talla:event.target.value})} className={field} placeholder="Talla"/>{selectedGarment?.aplica_numero?<input value={orderForm.numero_estampado} onChange={(event)=>setOrderForm({...orderForm,numero_estampado:event.target.value})} className={field} placeholder="Número estampado"/>:null}{selectedGarment?.aplica_nombre_estampado?<input value={orderForm.nombre_estampado} onChange={(event)=>setOrderForm({...orderForm,nombre_estampado:event.target.value})} className={field} placeholder="Nombre estampado"/>:null}<label className="flex items-center gap-2 text-sm text-[#c3ccd6]"><input type="checkbox" checked={orderForm.generar_cobro} onChange={(event)=>setOrderForm({...orderForm,generar_cobro:event.target.checked})}/>Generar cobro en la misma rama</label></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setOrderOpen(false)} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-black">Cancelar</button><button onClick={()=>void saveOrder()} className="rounded-xl bg-[#289E9D] px-4 py-2.5 text-sm font-black">Asignar</button></div></div></div>:null}
  </div>;
}
